export const exactSalesLine = (overrides = {}) => ({
  quantity: '1.000000',
  free_quantity: '0.000000',
  free_supply_tax_treatment: 'excluded_from_taxable_value',
  subtotal: '0.10',
  discount_amount: '0.00',
  taxable_amount: '0.10',
  cgst_amount: '0.01',
  sgst_amount: '0.01',
  igst_amount: '0.00',
  total_tax: '0.02',
  total_tax_amount: '0.02',
  line_total: '0.12',
  gst_percent: '18.000000',
  ...overrides,
});

export const exactInvoiceResponse = (overrides = {}) => ({
  success: true,
  gst_type: 'CGST/SGST',
  calculation_timestamp: 1,
  line_items: [exactSalesLine()],
  totals: {
    subtotal_amount: '0.10',
    discount_amount: '0.00',
    scheme_discount: '0.00',
    scheme_discount_percent: '0.000000',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    total_tax_amount: '0.02',
    freight_charges: '0.00',
    insurance_charges: '0.00',
    other_charges: '0.00',
    round_off_amount: '0.00',
    final_amount: '0.12',
  },
  ...overrides,
});

export const exactChallanResponse = (overrides = {}) => ({
  success: true,
  gst_type: 'CGST/SGST',
  calculation_timestamp: 1,
  line_items: [exactSalesLine()],
  totals: {
    subtotal_amount: '0.10',
    discount_amount: '0.00',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    total_tax_amount: '0.02',
    freight_charges: '0.00',
    final_amount: '0.12',
  },
  ...overrides,
});

export const exactPurchaseResponse = (overrides = {}) => ({
  success: true,
  gst_type: 'CGST/SGST',
  calculation_timestamp: 1,
  line_items: [{
    quantity: '1.000000',
    unit_price: '0.100000',
    discount_percent: '0.000000',
    discount_amount: '0.00',
    tax_percent: '18.000000',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    tax_amount: '0.02',
    line_total: '0.10',
    mrp: '0.100000',
  }],
  totals: {
    subtotal_amount: '0.10',
    discount_amount: '0.00',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    tax_amount: '0.02',
    freight_charges: '0.00',
    insurance_charges: '0.00',
    other_charges: '0.00',
    round_off_amount: '-0.12',
    total_amount: '0.00',
    invoice_total: '0.00',
  },
  ...overrides,
});

export const exactNoteResponse = (overrides = {}) => ({
  success: true,
  gst_type: 'CGST/SGST',
  calculation_timestamp: 1,
  line_items: [{
    quantity: '1.000000',
    free_quantity: '0.000000',
    free_supply_tax_treatment: 'excluded_from_taxable_value',
    unit_price: '0.100000',
    mrp: '0.100000',
    discount_percent: '0.000000',
    gst_percent: '18.000000',
    subtotal_amount: '0.10',
    discount_amount: '0.00',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    tax_amount: '0.02',
    total_amount: '0.12',
  }],
  totals: {
    subtotal_amount: '0.10',
    discount_amount: '0.00',
    taxable_amount: '0.10',
    cgst_amount: '0.01',
    sgst_amount: '0.01',
    igst_amount: '0.00',
    tax_amount: '0.02',
    total_amount: '0.12',
  },
  ...overrides,
});

test('exact calculation fixtures use string decimals', () => {
  expect(exactInvoiceResponse().totals.final_amount).toBe('0.12');
  expect(typeof exactPurchaseResponse().line_items[0].quantity).toBe('string');
});
