import { apiHelpers } from '../api/apiClient';
import {
  customersApi,
  toCanonicalCustomerCreate,
} from '../api/modules/master/customers.api';
import {
  suppliersApi,
  toCanonicalSupplierCreate,
} from '../api/modules/master/suppliers.api';
import { apiErrorMessage, apiErrorMessages } from '../api/utils/apiError';

jest.mock('../api/apiClient', () => ({
  apiHelpers: {
    get: jest.fn(),
    post: jest.fn(),
    put: jest.fn(),
    patch: jest.fn(),
    delete: jest.fn(),
  },
}));

describe('canonical party creation contracts', () => {
  beforeEach(() => jest.clearAllMocks());

  it('maps the active customer form without legacy or tenant-owned fields', () => {
    const payload = toCanonicalCustomerCreate({
      customer_name: ' Browser Customer ',
      customer_type: 'organization',
      primary_phone: '+91 98765-43210',
      primary_email: 'buyer@example.com',
      whatsapp_number: '9876543210',
      drug_license_number: 'UI-ONLY-LICENCE',
      org_id: 'must-not-cross-the-boundary',
      credit_limit: '0.00',
      credit_days: 0,
      address_line1: 'Test Lane 1',
      city: 'Mumbai',
      state_code: '27',
      pincode: '400001',
    });

    expect(payload).toEqual({
      customer_name: ' Browser Customer ',
      customer_type: 'organization',
      primary_phone: '9876543210',
      primary_email: 'buyer@example.com',
      address_line1: 'Test Lane 1',
      city: 'Mumbai',
      state_code: '27',
      pincode: '400001',
      credit_limit: '0.00',
      credit_days: 0,
    });
  });

  it('rejects browser-owned customer codes', () => {
    expect(() => toCanonicalCustomerCreate({
      customer_name: 'Injected Customer', customer_code: 'CUST-INJECTED',
      customer_type: 'organization', primary_phone: '9876543210',
      credit_limit: '0.00', credit_days: 0,
    })).toThrow('Customer code is generated by the canonical service.');
  });

  it('rejects missing customer classifications and commercial terms', () => {
    const complete = {
      customer_name: 'Explicit Customer',
      customer_type: 'organization',
      primary_phone: '9876543210',
      credit_limit: '0.00',
      credit_days: 0,
    };

    for (const field of ['customer_type', 'credit_limit', 'credit_days'] as const) {
      const input = { ...complete } as Record<string, unknown>;
      delete input[field];
      expect(() => toCanonicalCustomerCreate(input)).toThrow();
    }
  });

  it('maps only reviewed canonical supplier fields', () => {
    const payload = toCanonicalSupplierCreate({
      supplier_name: 'Browser Supplier',
      primary_phone: '98765 43210',
      primary_email: 'supplier@example.com',
      address_line1: 'Supplier Lane 1',
      city: 'Mumbai',
      state_code: '27',
      pincode: '400001',
      payment_days: '45',
      bank_name: 'must not cross',
      internal_notes: 'must not cross',
      org_id: 'must not cross',
    });

    expect(payload).toEqual({
      supplier_name: 'Browser Supplier',
      primary_phone: '9876543210',
      primary_email: 'supplier@example.com',
      address_line1: 'Supplier Lane 1',
      city: 'Mumbai',
      state_code: '27',
      pincode: '400001',
      payment_days: 45,
    });
  });

  it('rejects browser-owned supplier codes and missing payment days', () => {
    expect(() => toCanonicalSupplierCreate({
      supplier_name: 'Injected supplier', supplier_code: 'SUP-INJECTED', payment_days: 0,
    })).toThrow('Supplier code is generated by the canonical service.');
    expect(() => toCanonicalSupplierCreate({
      supplier_name: 'No terms',
    })).toThrow(
      'Supplier payment days must be selected explicitly.',
    );
  });

  it('rejects state names and GSTIN/address state-code mismatches before transport', () => {
    const customer = {
      customer_name: 'Mismatch Customer',
      customer_type: 'organization',
      primary_phone: '9876543210',
      credit_limit: '0.00',
      credit_days: 0,
      state_code: 'Maharashtra',
    };
    expect(() => toCanonicalCustomerCreate(customer)).toThrow(
      'GST state code must contain exactly 2 digits.',
    );
    expect(() => toCanonicalCustomerCreate({
      ...customer,
      state_code: undefined,
      state: 'Maharashtra',
    })).toThrow('State names are not accepted; enter the 2-digit GST state code.');

    expect(() => toCanonicalSupplierCreate({
      supplier_name: 'Mismatch Supplier',
      payment_days: 0,
      state_code: '29',
      gst_number: '27AAPFU0939F1ZV',
    })).toThrow('GSTIN state code must match the address GST state code.');
    expect(apiHelpers.post).not.toHaveBeenCalled();
  });

  it('requires canonical state_code for customer address mutations', () => {
    expect(() => customersApi.createAddress('customer-uuid', {
      address_line1: 'Test Lane', city: 'Mumbai', state: 'Maharashtra', pincode: '400001',
    })).toThrow('GST state code is required.');

    customersApi.createAddress('customer-uuid', {
      address_line1: 'Test Lane', city: 'Mumbai', state_code: '27', pincode: '400001',
      address_type: 'billing', is_default: true,
    });
    expect(apiHelpers.post).toHaveBeenCalledWith('/customers/customer-uuid/addresses/', {
      address_line1: 'Test Lane', city: 'Mumbai', state_code: '27', pincode: '400001',
      address_type: 'billing', is_default: true,
    });
  });

  it('turns FastAPI validation arrays into render-safe strings', () => {
    const error = {
      response: {
        data: {
          detail: [
            { loc: ['body', 'primary_phone'], msg: 'String should match pattern' },
            { loc: ['body', 'pincode'], msg: 'Field required' },
          ],
        },
      },
    };

    expect(apiErrorMessages(error, 'fallback')).toEqual([
      'body.primary_phone: String should match pattern',
      'body.pincode: Field required',
    ]);
    expect(apiErrorMessage(error, 'fallback')).toBe(
      'body.primary_phone: String should match pattern; body.pincode: Field required',
    );
  });

  it('uses canonical PATCH routes and keeps destructive party writes unavailable', async () => {
    await customersApi.update(
      'd3000000-0000-7000-8000-000000000011',
      { account_row_version: 2, party_row_version: 3, customer_name: 'Changed' },
      'erp-web-master-customer-update:d3000000-0000-7000-8000-000000000031',
    );
    await expect(customersApi.delete('customer-uuid'))
      .rejects.toMatchObject({ code: 'CANONICAL_WRITE_UNAVAILABLE' });
    expect(customersApi).not.toHaveProperty('updateCreditLimit');
    expect(customersApi).not.toHaveProperty('sendSMS');
    await suppliersApi.update(
      'd3000000-0000-7000-8000-000000000012',
      { account_row_version: 4, party_row_version: 5, supplier_name: 'Changed' },
      'erp-web-master-supplier-update:d3000000-0000-7000-8000-000000000032',
    );
    await expect(suppliersApi.delete('supplier-uuid'))
      .rejects.toMatchObject({ code: 'CANONICAL_WRITE_UNAVAILABLE' });

    expect(apiHelpers.patch).toHaveBeenNthCalledWith(1,
      '/customers/d3000000-0000-7000-8000-000000000011',
      { account_row_version: 2, party_row_version: 3, customer_name: 'Changed' },
      { headers: { 'X-Idempotency-Key': 'erp-web-master-customer-update:d3000000-0000-7000-8000-000000000031' } },
    );
    expect(apiHelpers.patch).toHaveBeenNthCalledWith(2,
      '/suppliers/d3000000-0000-7000-8000-000000000012',
      { account_row_version: 4, party_row_version: 5, supplier_name: 'Changed' },
      { headers: { 'X-Idempotency-Key': 'erp-web-master-supplier-update:d3000000-0000-7000-8000-000000000032' } },
    );
    expect(apiHelpers.put).not.toHaveBeenCalled();
    expect(apiHelpers.delete).not.toHaveBeenCalled();
    expect(apiHelpers.post).not.toHaveBeenCalled();
  });
});
