#!/usr/bin/env python3
"""Package canonical sales-order delivery-date authority for Alembic."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
ARTIFACT_PATH = (
    REPOSITORY_ROOT
    / "database/canonical/commands_automation/baseline-automation-command-enforcements.json"
)
OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "backend/alembic/sql/20260828_0036_sales_order_delivery_date.sql"
)
FUNCTION_NAMES = (
    "resolve_sales_order_prepare",
    "persist_sales_order_prepare",
)


def _definition(function_name: str) -> str:
    artifact = json.loads(ARTIFACT_PATH.read_text(encoding="utf-8"))
    prefix = (
        'CREATE FUNCTION "erp_automation_commands".'
        f'"{function_name}"('
    )
    matches = [
        statement
        for enforcement in artifact["enforcements"]
        for statement in enforcement["statements"]
        if statement.startswith(prefix)
    ]
    if len(matches) != 1:
        raise RuntimeError(f"expected one canonical definition for {function_name}")
    definition = matches[0].replace(
        "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1
    )
    if function_name == "resolve_sales_order_prepare":
        required = (
            "requested_delivery_date date := NULLIF(request_document->>'requested_delivery_date','')::date",
            "requested_delivery_date IS NULL",
            "requested_delivery_date<order_date",
            "'requested_delivery_date',requested_delivery_date",
            "delivery_address_id uuid := NULLIF(request_document->>'delivery_address_id','')::uuid",
            "row_version=delivery_address_row_version",
            "selected delivery address lacks exact supported India address facts",
        )
    else:
        required = (
            "requested_delivery_date,status",
            "(resolved_document->>'requested_delivery_date')::date,'submitted'",
        )
    missing = [fragment for fragment in required if fragment not in definition]
    if missing:
        raise RuntimeError(
            f"{function_name} lacks canonical requested-delivery authority: {missing}"
        )
    return definition


def generate_sql() -> str:
    definitions = ";\n".join(_definition(name) for name in FUNCTION_NAMES)
    return (
        "-- Generated by backend/scripts/generate_sales_order_delivery_date_migration.py.\n"
        "-- Alembic owns the transaction; this file must not be applied directly.\n"
        "SET LOCAL ROLE erp_migration_owner;\n"
        f"{definitions};\n"
        "RESET ROLE;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    generated = generate_sql()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            raise RuntimeError("sales-order delivery-date migration is stale")
        print("sales-order delivery-date migration: current")
    else:
        OUTPUT_PATH.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
