#!/usr/bin/env python3
"""Package transferred-stock landed-cost lineage and prepare review authority."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TRADE_ARTIFACT = (
    ROOT
    / "database/canonical/commands_trade_v2/baseline-trade-posting-enforcements.json"
)
AUTOMATION_ARTIFACT = (
    ROOT
    / "database/canonical/commands_automation/baseline-automation-command-enforcements.json"
)
OUTPUT = (
    ROOT
    / "backend/alembic/sql/20260828_0045_supplier_invoice_transfer_lineage.sql"
)

TRADE_FUNCTIONS = (
    "landed_cost_lineage_from_receipts",
    "landed_cost_receipt_lineage_state",
    "landed_cost_lineage_state",
    "eligible_landed_cost_pool",
    "assert_landed_cost_document",
    "prepare_supplier_invoice_landed_cost_adjustment",
)
AUTOMATION_FUNCTIONS = ("resolve_supplier_invoice_prepare",)


def _statements(path: Path) -> list[str]:
    artifact = json.loads(path.read_text(encoding="utf-8"))
    return [
        statement
        for enforcement in artifact["enforcements"]
        for statement in enforcement["statements"]
    ]


def _function_bundle(
    statements: list[str], schema: str, function_name: str
) -> list[str]:
    create_prefix = f'CREATE FUNCTION "{schema}"."{function_name}"('
    definitions = [
        statement for statement in statements if statement.startswith(create_prefix)
    ]
    if len(definitions) != 1:
        raise RuntimeError(f"expected one canonical {schema}.{function_name} definition")
    identity_prefix = f'"{schema}"."{function_name}"('
    acl = [
        statement
        for statement in statements
        if identity_prefix in statement
        and statement.startswith(
            ("ALTER FUNCTION ", "REVOKE ALL ON FUNCTION ", "GRANT EXECUTE ON FUNCTION ")
        )
    ]
    if not any(statement.startswith("ALTER FUNCTION ") for statement in acl):
        raise RuntimeError(f"canonical {schema}.{function_name} owner is missing")
    if not any(statement.startswith("REVOKE ALL ON FUNCTION ") for statement in acl):
        raise RuntimeError(f"canonical {schema}.{function_name} revocation is missing")
    return [
        definitions[0].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1),
        *acl,
    ]


def generated_sql() -> str:
    trade = _statements(TRADE_ARTIFACT)
    automation = _statements(AUTOMATION_ARTIFACT)
    bundles = [
        *_function_bundle(trade, "erp_trade_commands_v2", TRADE_FUNCTIONS[0]),
    ]
    for name in TRADE_FUNCTIONS[1:]:
        bundles.extend(_function_bundle(trade, "erp_trade_commands_v2", name))
    for name in AUTOMATION_FUNCTIONS:
        bundles.extend(_function_bundle(automation, "erp_automation_commands", name))
    sql = "\n\n".join(statement.rstrip(";") + ";" for statement in bundles) + "\n"
    required = (
        "supplier_invoice_landed_cost_lineage_v1",
        "landed_cost_receipt_lineage_state",
        "'resource_type','landed_cost_stock_target'",
        "'last_ledger_entry_id',landed_cost_target->>'last_ledger_entry_id'",
        "landed-cost remaining stock is ambiguous because receipt lineage is co-mingled",
    )
    missing = [fragment for fragment in required if fragment not in sql]
    if missing:
        raise RuntimeError(f"supplier-invoice transfer lineage is incomplete: {missing}")
    for private_name in TRADE_FUNCTIONS[:3]:
        identity = f'"erp_trade_commands_v2"."{private_name}"('
        if any(
            statement.startswith("GRANT EXECUTE")
            and identity in statement
            and ('TO "erp_runtime"' in statement or 'TO "erp_app"' in statement)
            for statement in bundles
        ):
            raise RuntimeError(f"private lineage helper {private_name} is runtime callable")
    return (
        "-- Generated by backend/scripts/generate_supplier_invoice_transfer_lineage_migration.py.\n"
        "-- Source owners: canonical trade-v2 and automation command generators.\n\n"
        "SET LOCAL ROLE erp_migration_owner;\n\n"
        + sql
        + "\nRESET ROLE;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_sql()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("supplier-invoice transfer-lineage migration is stale")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
