#!/usr/bin/env python3
"""Generate the reviewed sales-invoice auto-FEFO resolver migration."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_PATH = (
    REPOSITORY_ROOT
    / "database/canonical/commands_automation/baseline-automation-command-enforcements.json"
)
OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "backend/alembic/sql/20260825_0016_sales_invoice_auto_fefo.sql"
)
SIGNATURE = (
    '"erp_automation_commands"."resolve_sales_invoice_prepare"'
    "(organization_id uuid, membership_id uuid, auth_user_id uuid, "
    "application_user_id uuid, grant_id uuid, caller_client_id varchar, "
    "invoice_id uuid, request_document jsonb)"
)
# PostgreSQL 15 pg_get_functiondef() SHA-256 for the exact resolver emitted by
# the regenerated canonical baseline. This permits a fresh baseline chain to
# cross the incremental revision without treating an arbitrary auto-FEFO marker
# as proof that the reviewed definition is installed.
LEGACY_DEFINITION_SHA256 = (
    "bb2f61f4bbcceb5acaf571f6d92a02394aa4163fed356e126a0747fda8bd2ceb"
)
CURRENT_DEFINITION_SHA256 = (
    "2e59057ad1155566aa41632c8940b6031a137e8c78ebc07fa36cee7b357e0c70"
)


def _reviewed_statements() -> list[str]:
    artifact = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    matches = [
        statement
        for enforcement in artifact["enforcements"]
        for statement in enforcement["statements"]
        if SIGNATURE in statement
    ]
    expected_prefixes = (
        "CREATE FUNCTION ",
        "ALTER FUNCTION ",
        "REVOKE ALL ON FUNCTION ",
        "GRANT EXECUTE ON FUNCTION ",
        "GRANT EXECUTE ON FUNCTION ",
    )
    if len(matches) != len(expected_prefixes) or tuple(
        statement.split(SIGNATURE, 1)[0] for statement in matches
    ) != expected_prefixes:
        raise RuntimeError("reviewed sales-invoice resolver authority is incomplete")
    matches[0] = matches[0].replace(
        "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1
    )
    return [
        "\n".join(line.rstrip() for line in statement.splitlines())
        for statement in matches
    ]


def generate_sql() -> str:
    statements = _reviewed_statements()
    return (
        "-- Generated by backend/scripts/generate_sales_invoice_auto_fefo_migration.py.\n"
        "-- Alembic owns the transaction; this file must not be applied directly.\n"
        "SET LOCAL ROLE erp_migration_owner;\n\n"
        "DO $migration$\n"
        "DECLARE definition text; definition_sha256 text;\n"
        "BEGIN\n"
        "  SELECT pg_catalog.pg_get_functiondef(\n"
        "    'erp_automation_commands.resolve_sales_invoice_prepare"
        "(uuid,uuid,uuid,uuid,uuid,character varying,uuid,jsonb)'::pg_catalog.regprocedure\n"
        "  ) INTO STRICT definition;\n"
        "  definition_sha256:=pg_catalog.encode(extensions.digest(\n"
        "    pg_catalog.convert_to(definition,'UTF8'),'sha256'),'hex');\n"
        "  IF (definition_sha256='"
        f"{CURRENT_DEFINITION_SHA256}'\n"
        "      AND pg_catalog.strpos(definition,'sales_invoice_auto_fefo_v1')<>0)\n"
        "     OR (definition_sha256='"
        f"{LEGACY_DEFINITION_SHA256}'\n"
        "      AND pg_catalog.strpos(definition,'sales_invoice_auto_fefo_v1')=0\n"
        "      AND pg_catalog.strpos(definition,'delivery_address_row_version bigint')<>0\n"
        "      AND pg_catalog.strpos(definition,'sales_invoice_fefo_expiry_date_equivalence_v1')<>0\n"
        "      AND pg_catalog.strpos(definition,'direct invoice batch allocations are invalid')<>0) THEN\n"
        "    NULL;\n"
        "  ELSE\n"
        "    RAISE EXCEPTION USING ERRCODE='55000',\n"
        "      MESSAGE='sales-invoice resolver differs from reviewed auto-FEFO migration precondition';\n"
        "  END IF;\n"
        "END\n"
        "$migration$;\n\n"
        + ";\n".join(statements)
        + ";\n\nRESET ROLE;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    generated = generate_sql()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            raise RuntimeError("sales-invoice auto-FEFO migration package is stale")
        print("sales-invoice auto-FEFO migration: current")
    else:
        OUTPUT_PATH.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
