"""Package current named source owners for the scoped product tax revision."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CANONICAL = ROOT / "database/canonical"
OUTPUT = ROOT / "backend/alembic/sql/20260907_0077_scoped_product_tax.sql"
OWNERS = (
    "operations/tax/product_tax_authority.sql",
    "operations/automation/historical_product_inventory_cutover.sql",
)
TARGETS = {
    "commands_regulatory/baseline-regulatory-command-enforcements.json": {
        "guard_release", "guard_tax_code_version", "product_ready", "guard_product_use",
    },
    "commands_automation/baseline-automation-command-enforcements.json": {
        "resolve_sales_order_prepare", "resolve_purchase_order_prepare",
        "resolve_supplier_invoice_prepare", "resolve_sales_invoice_prepare",
    },
    "commands_trade_v2/baseline-trade-posting-enforcements.json": {
        "assert_purchase_order_artifact", "assert_sales_order_artifact",
    },
    "commands_commercial/baseline-commercial-command-enforcements.json": {
        "assert_purchase_return_artifact", "assert_supplier_invoice_artifact", "post_supplier_invoice",
        "assert_sales_invoice_artifact", "post_sales_invoice", "assert_sales_return_artifact",
    },
}


def statements(value):
    if isinstance(value, dict):
        for item in value.values():
            yield from statements(item)
    elif isinstance(value, list):
        for item in value:
            yield from statements(item)
    elif isinstance(value, str) and value.startswith("CREATE FUNCTION"):
        yield value


def render():
    chunks = ["-- Generated by backend/scripts/generate_scoped_product_tax_migration.py\nSET LOCAL ROLE erp_migration_owner;"]
    for owner in OWNERS:
        chunks.append((CANONICAL / owner).read_text().strip())
    for owner, names in TARGETS.items():
        found = set()
        for statement in statements(json.loads((CANONICAL / owner).read_text())):
            name = statement.split('"')[3]
            if name in names:
                chunks.append(statement.replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1).rstrip(";") + ";")
                found.add(name)
        if found != names:
            raise ValueError(f"Missing named tax migration owners: {names - found}")
    chunks.append("RESET ROLE;")
    return "\n\n".join(chunks) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sql = render()
    if args.check:
        assert OUTPUT.read_text() == sql, "scoped product tax migration is stale"
    else:
        OUTPUT.write_text(sql)
    print(hashlib.sha256(sql.encode()).hexdigest())
