from __future__ import annotations

import hashlib
import importlib.util
from pathlib import Path


ROOT = Path(__file__).parents[3]
GENERATOR = ROOT / "backend/scripts/generate_tenant_timestamp_date_migration.py"
SQL_PATH = ROOT / "backend/alembic/sql/20260828_0039_tenant_timestamp_dates.sql"
REVISION_PATH = ROOT / "backend/alembic/versions/20260828_0039_tenant_timestamp_dates.py"
POSTGRES_CHECK = ROOT / "backend/tests/postgres/check_tenant_timestamp_date_runtime_role.py"
POSTGRES_GATE = ROOT / "database/canonical/ci/run_alembic_postgres15_gate.sh"


def _load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_tenant_timestamp_date_migration_is_generator_owned_hash_bound_and_linear() -> None:
    generator = _load(GENERATOR, "tenant_timestamp_date_generator")
    revision = _load(REVISION_PATH, "tenant_timestamp_date_revision")
    sql = SQL_PATH.read_text(encoding="utf-8")

    assert generator.generate_sql() == sql
    assert revision.revision == "20260828_0039"
    assert revision.down_revision == "20260828_0038"
    assert revision.EXPECTED_SQL_SHA256 == hashlib.sha256(sql.encode()).hexdigest()
    assert sql.count("CREATE OR REPLACE FUNCTION") == 8
    assert sql.startswith(
        "-- Generated by backend/scripts/generate_tenant_timestamp_date_migration.py."
    )
    assert sql.rstrip().endswith("RESET ROLE;")


def test_every_confirmed_timestamp_date_path_uses_a_locked_tenant_timezone() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")
    for fragment in (
        "NEW.created_at AT TIME ZONE organization_timezone",
        "NEW.received_at AT TIME ZONE organization.timezone",
        "ledger.posted_at AT TIME ZONE organization.timezone",
        "measured_at AT TIME ZONE organization.timezone",
        "filing.filed_at AT TIME ZONE organization.timezone",
        "FROM core.organizations",
        "FOR SHARE",
    ):
        assert fragment in sql
    for forbidden in (
        "NEW.created_at::date",
        "NEW.received_at::date",
        "ledger.posted_at::date",
        "measured_at::date",
        "filing.filed_at::date",
        "Asia/Kolkata",
        "CURRENT_DATE",
    ):
        assert forbidden not in sql


def test_postgres_gate_covers_runtime_definitions_and_direct_issue_boundary() -> None:
    gate = POSTGRES_GATE.read_text(encoding="utf-8")
    direct_issue = (
        ROOT / "backend/tests/postgres/check_sales_invoice_direct_issue_acceptance.py"
    ).read_text(encoding="utf-8")

    assert str(POSTGRES_CHECK.relative_to(ROOT)) in gate
    assert "_assert_batch_guard_uses_organization_date" in direct_issue
    assert "SET LOCAL TIME ZONE 'UTC'" in direct_issue
    assert "session_date < organization_date" in direct_issue
    assert "SELECT CURRENT_DATE" not in direct_issue
    assert "business_date=business_date" in direct_issue
    postgres_check = POSTGRES_CHECK.read_text(encoding="utf-8")
    for family in (
        "trade_invariant",
        "regulatory_guard",
        "compliance_commands",
        "commercial_commands",
        "automation_resolution",
    ):
        assert family in postgres_check
