from __future__ import annotations

import hashlib
from pathlib import Path

from scripts.generate_canonical_command_definition_migration import (
    FUNCTION_SOURCE_OVERRIDES,
    FUNCTION_TARGETS,
    generate_sql,
)


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
SQL_PATH = (
    REPOSITORY_ROOT
    / "backend/alembic/sql/20260825_0012_canonical_command_definitions.sql"
)
REVISION_PATH = (
    REPOSITORY_ROOT
    / "backend/alembic/versions/20260825_0012_canonical_command_definitions.py"
)
WORKFLOW_PATH = REPOSITORY_ROOT / ".github/workflows/canonical-staging.yml"


def test_command_definition_migration_is_generated_hash_bound_and_linear() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")
    revision = REVISION_PATH.read_text(encoding="utf-8")

    assert sql == generate_sql()
    assert hashlib.sha256(sql.encode("utf-8")).hexdigest() in revision
    assert 'revision = "20260825_0012"' in revision
    assert 'down_revision = "20260825_0011"' in revision
    assert "CanonicalBaselineError" in revision.split("def downgrade", 1)[1]


def test_migration_versions_every_former_staging_hot_patch() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")

    assert len(FUNCTION_TARGETS) == 33
    for _, schema, function in FUNCTION_TARGETS:
        assert sql.count(f'CREATE OR REPLACE FUNCTION "{schema}"."{function}"') == 1
    assert sql.startswith("-- Generated by")
    assert "SET LOCAL ROLE erp_migration_owner" in sql
    assert "SET ROLE erp_migration_owner" not in sql
    assert "ck_sales_returns_rounding_policy" in sql
    assert "ck_procurement_purchase_returns_rounding_policy" in sql
    assert "DROP TRIGGER IF EXISTS tax_portal_documents_immutable_trg" in sql


def test_incremental_command_owners_are_not_reverted_to_baseline() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")

    assert len(FUNCTION_SOURCE_OVERRIDES) == 3
    assert "guard_command_request_match" not in sql
    assert "WHEN 'finance.adjustment_note.post' THEN" in sql
    assert "adjustment note is neither approved nor a command-bound draft" in sql
    assert "purchase return requires one exact effective GST adjustment authority" in sql


def test_staging_workflow_only_verifies_migrated_definitions() -> None:
    workflow = WORKFLOW_PATH.read_text(encoding="utf-8")
    verification = workflow.split(
        "- name: Verify Alembic-owned canonical command definitions", 1
    )[1].split("- name: Verify baseline topology", 1)[0]

    assert "database/query/read-only" in verification
    assert "CREATE OR REPLACE FUNCTION" not in verification
    assert "reconciliation_sql" not in verification
    assert "--single-transaction" not in verification
    assert "Alembic head did not install every reviewed definition" in verification
