from __future__ import annotations

import hashlib
import importlib.util
from pathlib import Path


ROOT = Path(__file__).parents[3]
GENERATOR = ROOT / "backend/scripts/generate_posting_chronology_migration.py"
SQL_PATH = ROOT / "backend/alembic/sql/20260828_0038_posting_chronology.sql"
REVISION_PATH = ROOT / "backend/alembic/versions/20260828_0038_posting_chronology.py"
POSTGRES_CHECK = (
    ROOT / "backend/tests/postgres/check_posting_chronology_runtime_role.py"
)
POSTGRES_GATE = ROOT / "database/canonical/ci/run_alembic_postgres15_gate.sh"


def _load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _definition(sql: str, name: str) -> str:
    start = sql.index(
        f'CREATE OR REPLACE FUNCTION "erp_automation_commands"."{name}"('
    )
    body_start = sql.index("$function$", start) + len("$function$")
    end = sql.index("$function$", body_start)
    return sql[start:end]


def test_posting_chronology_migration_is_generator_owned_hash_bound_and_linear() -> None:
    generator = _load(GENERATOR, "posting_chronology_generator")
    revision = _load(REVISION_PATH, "posting_chronology_revision")
    sql = SQL_PATH.read_text(encoding="utf-8")

    assert generator.generate_sql() == sql
    assert revision.revision == "20260828_0038"
    assert revision.down_revision == "20260828_0037"
    assert revision.EXPECTED_SQL_SHA256 == hashlib.sha256(sql.encode()).hexdigest()
    assert sql.count("CREATE OR REPLACE FUNCTION") == 9
    assert sql.startswith(
        "-- Generated by backend/scripts/generate_posting_chronology_migration.py."
    )
    assert sql.rstrip().endswith("RESET ROLE;")


def test_actual_document_dates_use_the_authenticated_organization_clock() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")
    checks = {
        "resolve_sales_dispatch_prepare": "dispatch_date",
        "resolve_purchase_order_prepare": "order_date",
        "resolve_supplier_invoice_prepare": "invoice_date",
        "resolve_sales_invoice_prepare": "invoice_date",
        "resolve_sales_order_prepare": "order_date",
        "resolve_sales_return_prepare": "return_date",
        "resolve_purchase_return_prepare": "return_date",
        "resolve_adjustment_note_prepare_unchecked_v0013": "note_date",
    }
    business_clock = '"erp_core_commands"."current_organization_business_date"()'
    for name, date_field in checks.items():
        definition = _definition(sql, name)
        activation = definition.index(
            "erp_security.activate_context(auth_user_id,organization_id)"
        )
        chronology = definition.index(f"{date_field}>{business_clock}")
        assert activation < chronology

    supplier = _definition(sql, "resolve_supplier_invoice_prepare")
    assert f"received_date>{business_clock}" in supplier
    assert "expected_on>" + business_clock not in sql
    assert "requested_delivery_date>" + business_clock not in sql
    assert "CURRENT_DATE" not in sql
    assert "Asia/Kolkata" not in sql


def test_predecessor_dates_are_locked_rejected_and_bound_to_source_versions() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")
    dispatch = _definition(sql, "resolve_sales_invoice_prepare")
    receipt = _definition(sql, "resolve_goods_receipt_prepare")
    supplier = _definition(sql, "resolve_supplier_invoice_prepare")
    purchase_return = _definition(sql, "resolve_purchase_return_prepare")

    for fragment in (
        "invoice_date<dispatch_header.dispatch_date",
        "'dispatch_date',dispatch_header.dispatch_date",
        "'dispatch_row_version',dispatch_header.row_version",
        "FOR SHARE",
    ):
        assert fragment in dispatch
    for fragment in (
        "received_day<purchase_order.order_date",
        "'order_date',purchase_order.order_date",
    ):
        assert fragment in receipt
    for fragment in (
        "receipt_business_date:=(receipt.received_at AT TIME ZONE organization.timezone)::date",
        "received_date<receipt_business_date",
        "'goods_receipt_received_at',receipt.received_at",
        "'goods_receipt_business_date',receipt_business_date",
        "'received_at',receipt.received_at,'business_date',receipt_business_date",
    ):
        assert fragment in supplier
    assert "invoice_date<receipt_business_date" not in supplier
    assert "received_date<invoice_date" in supplier
    for fragment in (
        "portal_line.invoice_date>return_date",
        "'invoice_date',portal_line.invoice_date",
        "'supplier_invoice_date',invoice.supplier_invoice_date",
    ):
        assert fragment in purchase_return


def test_forward_replacements_preserve_every_later_alembic_owned_policy() -> None:
    sql = SQL_PATH.read_text(encoding="utf-8")
    purchase_return = _definition(sql, "resolve_purchase_return_prepare")
    sales_invoice = _definition(sql, "resolve_sales_invoice_prepare")
    adjustment_inner = _definition(
        sql, "resolve_adjustment_note_prepare_unchecked_v0013"
    )

    assert "reason_code NOT IN ('wrong_supply','excess_supply')" not in purchase_return
    assert "gst_adjustment_rule_versions" in purchase_return
    assert "sales_invoice_fefo_expiry_date_equivalence_v3" in sales_invoice
    assert "requested_conversion.multiplier" in sales_invoice
    assert "resolve_adjustment_note_prepare(" not in adjustment_inner
    assert "note_date<document_date" in adjustment_inner


def test_prepare_persistence_rechecks_chronology_before_owning_a_command() -> None:
    source = (
        ROOT
        / "database/canonical/commands_automation/baseline-automation-command-enforcements.json"
    ).read_text(encoding="utf-8")
    for name in (
        "persist_goods_receipt_prepare",
        "persist_supplier_invoice_prepare",
        "persist_sales_invoice_prepare",
        "persist_sales_return_prepare",
        "persist_purchase_return_prepare",
    ):
        start = source.index(f'\\"{name}\\"(')
        resolver = source.index("current_resolution", start)
        command = source.index("automation.command_requests", start)
        assert resolver < command
    assert "organization_id,membership_id,auth_user_id" in source
    assert "idempotency key has different exact input" in source


def test_postgres_runtime_acceptance_covers_negative_lifecycle_and_tenant_paths() -> None:
    check = POSTGRES_CHECK.read_text(encoding="utf-8")
    gate = POSTGRES_GATE.read_text(encoding="utf-8")

    assert str(POSTGRES_CHECK.relative_to(ROOT)) in gate
    for operation in (
        "procurement.purchase_order.prepare",
        "procurement.goods_receipt.prepare",
        "procurement.supplier_invoice.prepare",
        "procurement.purchase_return.prepare",
        "sales.order.prepare",
        "sales.dispatch.prepare",
        "sales.invoice.prepare",
        "sales.return.prepare",
        "finance.adjustment_note.prepare",
    ):
        assert operation in check
    for boundary in (
        "_expect_validation",
        "_expect_cross_tenant",
        "_assert_supplier_invoice_rollback",
        "_assert_return_rollback",
        "_bump_return_row_version",
        "fixture.reconcile_sales_return",
        "fixture.reconcile_purchase_return",
        "stale sales-return aggregate executed",
        "injected journal failure did not abort purchase return",
        "idempotency_replayed is True",
        "invoice_date",
        "received_date",
        "dispatch_date",
        "order_date",
    ):
        assert boundary in check
