/**
 * Customers API Module
 * Handles customer CRUD and related operations
 *
 * ENDPOINTS: /customers (backend: app/api/routes/master/customers.py)
 */

import { apiHelpers } from '../../apiClient';
import { cleanData } from '../../utils/dataUtils';
import { rejectCanonicalWrite } from '../../canonicalWritePolicy';
import { normalizeExactDecimal } from '../../../../utils/exactDecimal';
import {
  decodeCanonicalCustomerCreateResponse,
  masterCreateRequestConfig,
  type CanonicalCustomerCreateResponse,
} from './masterCreationContract';
import { decodeCanonicalCustomerList } from './canonicalMasterReads';
import { canonicalStateCode, gstinStateCodeError } from './partyStateCode';

// ============================================================================
// TYPES
// ============================================================================

export interface CustomerParams {
  limit?: number;
  offset?: number;
  search?: string;
  has_outstanding?: boolean;
  include_credit?: boolean;
}

interface MasterReadConfig {
  signal?: AbortSignal;
}

export interface CanonicalCustomerCreateInput {
  customer_name: string;
  customer_type: 'individual' | 'organization';
  primary_phone: string;
  primary_email?: string;
  contact_person_name?: string;
  address_line1?: string;
  address_line2?: string;
  city?: string;
  state_code?: string;
  pincode?: string;
  gst_number?: string;
  pan_number?: string;
  credit_limit: string;
  credit_days: number;
}

export interface CanonicalCustomerUpdateInput {
  account_row_version: number;
  party_row_version: number;
  customer_name?: string;
  customer_type?: 'individual' | 'organization';
  primary_phone?: string;
  primary_email?: string | null;
  contact_person_name?: string | null;
  pan_number?: string | null;
  credit_limit?: string;
  credit_days?: number;
}

export const toCanonicalCustomerUpdate = (
  input: CanonicalCustomerUpdateInput,
): CanonicalCustomerUpdateInput => {
  const payload = { ...input };
  if (payload.primary_phone !== undefined) payload.primary_phone = canonicalPhone(payload.primary_phone);
  if (payload.pan_number) payload.pan_number = payload.pan_number.trim().toUpperCase();
  if (payload.credit_limit !== undefined) {
    payload.credit_limit = normalizeExactDecimal(
      payload.credit_limit, 'Customer credit limit',
      { scale: 2, maximumWholeDigits: 18 },
    );
  }
  return payload;
};

const optionalText = (value: unknown): string | undefined => (
  typeof value === 'string' && value.trim() ? value.trim() : undefined
);
const canonicalPhone = (value: unknown): string => {
  const digits = String(value || '').replace(/\D/g, '');
  return digits.length === 12 && digits.startsWith('91') ? digits.slice(2) : digits;
};

/** Keep the browser write boundary aligned with the reviewed canonical schema. */
export const toCanonicalCustomerCreate = (input: Record<string, any>): CanonicalCustomerCreateInput => {
  if (input.customer_code !== undefined) {
    throw new Error('Customer code is generated by the canonical service.');
  }
  if (input.state !== undefined || input.address?.state !== undefined) {
    throw new Error('State names are not accepted; enter the 2-digit GST state code.');
  }
  if (input.customer_type !== 'individual' && input.customer_type !== 'organization') {
    throw new Error('Customer type must be selected explicitly.');
  }
  if (input.credit_limit === undefined || input.credit_limit === null || input.credit_limit === '') {
    throw new Error('Customer credit limit must be entered explicitly.');
  }
  if (input.credit_days === undefined || input.credit_days === null || input.credit_days === '') {
    throw new Error('Customer credit days must be entered explicitly.');
  }
  const stateCode = canonicalStateCode(input.state_code);
  const gstNumber = optionalText(input.gst_number)?.toUpperCase();
  const mismatch = gstinStateCodeError(stateCode, gstNumber);
  if (mismatch) throw new Error(mismatch);
  const payload = {
    customer_name: input.customer_name,
    customer_type: input.customer_type,
    primary_phone: canonicalPhone(input.primary_phone),
    primary_email: input.primary_email,
    contact_person_name: input.contact_person_name,
    address_line1: input.address_line1,
    address_line2: input.address_line2,
    city: input.city,
    state_code: stateCode,
    pincode: input.pincode,
    gst_number: gstNumber,
    pan_number: optionalText(input.pan_number)?.toUpperCase(),
    credit_limit: normalizeExactDecimal(
      input.credit_limit,
      'Customer credit limit',
      { scale: 2, maximumWholeDigits: 18 },
    ),
    credit_days: input.credit_days,
  };
  return Object.fromEntries(
    Object.entries(payload).filter(([, value]) => value !== undefined && value !== null),
  ) as unknown as CanonicalCustomerCreateInput;
};

// ============================================================================
// API
// ============================================================================

export const customersApi = {
  getAll: (params: CustomerParams = {}, config: MasterReadConfig = {}) => apiHelpers.get('/customers', {
    params,
    signal: config.signal,
    preserveExactDecimals: true,
  })
    .then(response => ({ ...response, data: decodeCanonicalCustomerList(response.data) })),

  create: (data: Record<string, any>, idempotencyKey: string) => {
    return apiHelpers.post<CanonicalCustomerCreateResponse>(
      '/customers/',
      toCanonicalCustomerCreate(data),
      masterCreateRequestConfig(idempotencyKey),
    ).then(response => ({
      ...response,
      data: decodeCanonicalCustomerCreateResponse(response.data),
    }));
  },

  update: (id: string, data: CanonicalCustomerUpdateInput, idempotencyKey: string) =>
    apiHelpers.patch(`/customers/${id}`, toCanonicalCustomerUpdate(data),
      masterCreateRequestConfig(idempotencyKey)),
  delete: (_id: number | string) => rejectCanonicalWrite('Deleting a customer'),

  // Create a customer address through the live API
  createAddress: (customerId: string, addressData: any) => {
    const stateCode = canonicalStateCode(addressData?.state_code);
    if (!stateCode) throw new Error('GST state code is required.');
    const cleanedData = cleanData({
      ...addressData,
      state_code: stateCode,
      state: undefined,
    });
    return apiHelpers.post(`/customers/${customerId}/addresses/`, cleanedData);
  },

  updateAddress: (customerId: string, addressId: string, addressData: any) => {
    const stateCode = canonicalStateCode(addressData?.state_code);
    if (!stateCode) throw new Error('GST state code is required.');
    const cleanedData = cleanData({
      ...addressData,
      state_code: stateCode,
      state: undefined,
    });
    return apiHelpers.put(`/customers/${customerId}/addresses/${addressId}`, cleanedData);
  },

  // Search customers
  search: (query: string, params: CustomerParams = {}, config: MasterReadConfig = {}) => {
    return apiHelpers.get('/customers', {
      params: { search: query, ...params },
      signal: config.signal,
      preserveExactDecimals: true,
    }).then(response => ({ ...response, data: decodeCanonicalCustomerList(response.data) }));
  },
};
