/**
 * Suppliers API Module
 * Handles supplier CRUD and related operations
 *
 * ENDPOINTS: /suppliers (backend: app/api/routes/master/suppliers.py)
 */

import { apiHelpers } from '../../apiClient';
import { cleanData } from '../../utils/dataUtils';
import {
  decodeCanonicalSupplierCreateResponse,
  masterCreateRequestConfig,
  type CanonicalSupplierCreateResponse,
} from './masterCreationContract';
import { rejectCanonicalWrite } from '../../canonicalWritePolicy';
import { decodeCanonicalSupplierList } from './canonicalMasterReads';
import { canonicalStateCode, gstinStateCodeError } from './partyStateCode';

// ============================================================================
// TYPES
// ============================================================================

export interface SupplierParams {
  limit?: number;
  offset?: number;
  search?: string;
  has_outstanding?: boolean;
}

interface MasterReadConfig {
  signal?: AbortSignal;
}

export interface CanonicalSupplierCreateInput {
  supplier_name: string;
  primary_phone?: string;
  primary_email?: string;
  contact_person?: string;
  address_line1?: string;
  address_line2?: string;
  city?: string;
  state_code?: string;
  pincode?: string;
  gst_number?: string;
  pan_number?: string;
  payment_days: number;
}

export interface CanonicalSupplierUpdateInput {
  account_row_version: number;
  party_row_version: number;
  supplier_name?: string;
  primary_phone?: string | null;
  primary_email?: string | null;
  contact_person?: string | null;
  pan_number?: string | null;
  payment_days?: number;
}

export const toCanonicalSupplierUpdate = (
  input: CanonicalSupplierUpdateInput,
): CanonicalSupplierUpdateInput => {
  const payload = { ...input };
  if (payload.primary_phone !== undefined && payload.primary_phone !== null) {
    payload.primary_phone = canonicalPhone(payload.primary_phone) || null;
  }
  if (payload.pan_number) payload.pan_number = payload.pan_number.trim().toUpperCase();
  if (payload.payment_days !== undefined
      && (!Number.isInteger(payload.payment_days)
        || payload.payment_days < 0 || payload.payment_days > 180)) {
    throw new Error('Supplier payment days must be an integer from 0 to 180.');
  }
  return payload;
};

const optionalText = (value: unknown): string | undefined => (
  typeof value === 'string' && value.trim() ? value.trim() : undefined
);
const canonicalPhone = (value: unknown): string | undefined => {
  const text = optionalText(value);
  if (!text) return undefined;
  const digits = text.replace(/\D/g, '');
  return digits.length === 12 && digits.startsWith('91') ? digits.slice(2) : digits;
};

/** Strip legacy UI aliases and fields owned by separate reviewed workflows. */
export const toCanonicalSupplierCreate = (input: Record<string, any>): CanonicalSupplierCreateInput => {
  if (input.supplier_code !== undefined) {
    throw new Error('Supplier code is generated by the canonical service.');
  }
  if (input.state !== undefined) {
    throw new Error('State names are not accepted; enter the 2-digit GST state code.');
  }
  const rawPaymentDays = input.payment_days;
  if (rawPaymentDays === undefined || rawPaymentDays === '') {
    throw new Error('Supplier payment days must be selected explicitly.');
  }
  const parsedPaymentDays = Number.parseInt(String(rawPaymentDays), 10);
  if (!Number.isInteger(parsedPaymentDays) || parsedPaymentDays < 0 || parsedPaymentDays > 180) {
    throw new Error('Supplier payment days must be an integer from 0 to 180.');
  }
  const stateCode = canonicalStateCode(input.state_code);
  const gstNumber = optionalText(input.gst_number)?.toUpperCase();
  const mismatch = gstinStateCodeError(stateCode, gstNumber);
  if (mismatch) throw new Error(mismatch);
  return cleanData({
    supplier_name: input.supplier_name,
    primary_phone: canonicalPhone(input.primary_phone),
    primary_email: input.primary_email,
    contact_person: input.contact_person,
    address_line1: input.address_line1,
    address_line2: input.address_line2,
    city: input.city,
    state_code: stateCode,
    pincode: input.pincode,
    gst_number: gstNumber,
    pan_number: optionalText(input.pan_number)?.toUpperCase(),
    payment_days: parsedPaymentDays,
  }) as CanonicalSupplierCreateInput;
};

// ============================================================================
// API
// ============================================================================

export const suppliersApi = {
  getAll: (params: SupplierParams = {}, config: MasterReadConfig = {}) => apiHelpers.get('/suppliers', {
    params,
    signal: config.signal,
    preserveExactDecimals: true,
  })
    .then(response => ({ ...response, data: decodeCanonicalSupplierList(response.data) })),

  create: (data: Record<string, any>, idempotencyKey: string) => {
    return apiHelpers.post<CanonicalSupplierCreateResponse>(
      '/suppliers/',
      toCanonicalSupplierCreate(data),
      masterCreateRequestConfig(idempotencyKey),
    ).then(response => ({
      ...response,
      data: decodeCanonicalSupplierCreateResponse(response.data),
    }));
  },

  update: (id: string, data: CanonicalSupplierUpdateInput, idempotencyKey: string) =>
    apiHelpers.patch(`/suppliers/${id}`, toCanonicalSupplierUpdate(data),
      masterCreateRequestConfig(idempotencyKey)),
  delete: (_id: number | string) => rejectCanonicalWrite('Deleting a supplier'),

  // Search suppliers
  search: (query: string, params: SupplierParams = {}, config: MasterReadConfig = {}) => {
    return apiHelpers.get('/suppliers', {
      params: { search: query, ...params },
      signal: config.signal,
      preserveExactDecimals: true,
    }).then(response => ({ ...response, data: decodeCanonicalSupplierList(response.data) }));
  },
};
