#!/bin/bash

# ERP Project API Client Consolidation Script
# Purpose: Migrate from dual JS/TS API clients to TypeScript only
# Created: August 2025

set -e

echo "🔧 Starting API Client Consolidation..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to check if file exists
check_file() {
    if [ -f "$1" ]; then
        echo -e "${GREEN}✓${NC} Found: $1"
        return 0
    else
        echo -e "${YELLOW}⚠${NC} Not found: $1"
        return 1
    fi
}

echo ""
echo "📋 Phase 1: Analyze current API client usage"
echo "============================================="

# Check current API clients
echo ""
echo "Current API client files:"
check_file "frontend/src/services/api/apiClient.ts"
check_file "frontend/src/services/api/apiClientExports.js" 
check_file "frontend/src/services/api/index.js"

echo ""
echo "🔍 Searching for imports of JavaScript API client..."

# Find files importing the JS client
js_imports=$(find frontend/src -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" | xargs grep -l "apiClientExports" 2>/dev/null || true)

if [ -n "$js_imports" ]; then
    echo -e "${YELLOW}Found files using JavaScript API client:${NC}"
    echo "$js_imports"
else
    echo -e "${GREEN}✓ No files found using JavaScript API client${NC}"
fi

echo ""
echo "🔍 Searching for imports of TypeScript API client..."

# Find files importing the TS client
ts_imports=$(find frontend/src -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" | xargs grep -l "apiClient" | grep -v "apiClientExports" 2>/dev/null || true)

if [ -n "$ts_imports" ]; then
    echo -e "${GREEN}Files using TypeScript API client:${NC}"
    echo "$ts_imports" | head -10
    echo "... (showing first 10, total: $(echo "$ts_imports" | wc -l))"
else
    echo -e "${YELLOW}⚠ No files found using TypeScript API client${NC}"
fi

echo ""
echo "📋 Phase 2: Create migration plan"
echo "=================================="

# Create backup directory
backup_dir="frontend/src/services/api/backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$backup_dir"

echo -e "${BLUE}ℹ${NC} Created backup directory: $backup_dir"

# Backup existing files
if [ -f "frontend/src/services/api/apiClientExports.js" ]; then
    cp "frontend/src/services/api/apiClientExports.js" "$backup_dir/"
    echo -e "${GREEN}✓${NC} Backed up apiClientExports.js"
fi

if [ -f "frontend/src/services/api/index.js" ]; then
    cp "frontend/src/services/api/index.js" "$backup_dir/"
    echo -e "${GREEN}✓${NC} Backed up index.js"
fi

echo ""
echo "📋 Phase 3: Analyze API module structure"
echo "========================================"

echo ""
echo "API modules found:"
find frontend/src/services/api/modules -name "*.api.js" 2>/dev/null | while read -r file; do
    echo -e "${GREEN}✓${NC} $(basename "$file")"
done

modules_count=$(find frontend/src/services/api/modules -name "*.api.js" 2>/dev/null | wc -l)
echo ""
echo "Total API modules: $modules_count"

echo ""
echo "📋 Phase 4: Create consolidated API client"
echo "=========================================="

# Create new consolidated index.ts file
cat > frontend/src/services/api/index.ts << 'EOF'
/**
 * Consolidated API Client - TypeScript Only
 * Replaces dual JS/TS client system
 * Generated by cleanup script
 */

// Import main TypeScript API client
import { apiHelpers } from './apiClient';

// Import all API modules
import { productsApi } from './modules/products.api.js';
import { customersApi } from './modules/customers.api.js';
import { suppliersApi } from './modules/suppliers.api.js';
import { salesApi } from './modules/sales.api.js';
import { purchasesApi } from './modules/purchases.api.js';
import { inventoryApi } from './modules/inventory.api.js';
import { paymentsApi } from './modules/payments.api.js';
import { ordersApi } from './modules/orders.api.js';
import { invoicesApi } from './modules/invoices.api.js';
import { returnsApi } from './modules/returns.api.js';
import { dashboardApi } from './modules/dashboard.api.js';
import { reportsApi } from './modules/reports.api.js';
import { settingsApi } from './modules/settings.api.js';
import { usersApi } from './modules/users.api.js';
import { batchesApi } from './modules/batches.api.js';
import { stockApi } from './modules/stock.api.js';
import { ledgerApi } from './modules/ledger.api.js';
import { notesApi } from './modules/notes.api.js';

// Export unified API object
export const api = {
  // Core business entities
  products: productsApi,
  customers: customersApi,
  suppliers: suppliersApi,
  
  // Transactions
  sales: salesApi,
  purchases: purchasesApi,
  orders: ordersApi,
  invoices: invoicesApi,
  payments: paymentsApi,
  returns: returnsApi,
  
  // Inventory
  inventory: inventoryApi,
  batches: batchesApi,
  stock: stockApi,
  
  // Financial
  ledger: ledgerApi,
  notes: notesApi,
  
  // Analytics & Management
  dashboard: dashboardApi,
  reports: reportsApi,
  settings: settingsApi,
  users: usersApi,
  
  // Low-level helpers
  helpers: apiHelpers
};

// Export individual modules for backward compatibility
export {
  productsApi,
  customersApi,
  suppliersApi,
  salesApi,
  purchasesApi,
  inventoryApi,
  paymentsApi,
  ordersApi,
  invoicesApi,
  returnsApi,
  dashboardApi,
  reportsApi,
  settingsApi,
  usersApi,
  batchesApi,
  stockApi,
  ledgerApi,
  notesApi,
  apiHelpers
};

// Default export for convenience
export default api;
EOF

echo -e "${GREEN}✓${NC} Created consolidated API client (frontend/src/services/api/index.ts)"

echo ""
echo "📋 Phase 5: Create migration guide"
echo "=================================="

cat > frontend/src/services/api/MIGRATION_GUIDE.md << 'EOF'
# API Client Migration Guide

## Overview

This project has been migrated from dual JavaScript/TypeScript API clients to a unified TypeScript-only system.

## Before (Dual System)
```javascript
// Old JavaScript approach
import { apiClientExports } from './apiClientExports.js';
import { productsApi } from './modules/products.api.js';

// Multiple ways to call APIs
apiClientExports.get('/products');
productsApi.getAll();
```

## After (Unified TypeScript)
```typescript
// New unified approach
import { api } from './services/api';
// or
import { productsApi } from './services/api';

// Consistent API calls
api.products.getAll();
productsApi.getAll();
```

## Migration Steps

1. **Replace imports:**
   ```typescript
   // Old
   import { apiClientExports } from './services/api/apiClientExports.js';
   
   // New
   import { api } from './services/api';
   ```

2. **Update API calls:**
   ```typescript
   // Old
   apiClientExports.get('/products')
   
   // New  
   api.products.getAll()
   ```

3. **Use domain-specific APIs:**
   ```typescript
   // Products
   api.products.getAll()
   api.products.create(data)
   
   // Customers
   api.customers.search(query)
   api.customers.create(data)
   ```

## Benefits

- **Type Safety**: Full TypeScript support
- **Consistency**: Single API pattern
- **Maintainability**: Easier to update and extend
- **Developer Experience**: Better autocomplete and error detection
- **Performance**: Tree-shaking and bundle optimization

## Backward Compatibility

Individual modules are still exported for gradual migration:

```typescript
import { productsApi, customersApi } from './services/api';
```

## Testing

All API calls should be tested after migration:
- Verify imports work correctly
- Test API calls return expected data
- Check error handling
- Validate TypeScript compilation
EOF

echo -e "${GREEN}✓${NC} Created migration guide (frontend/src/services/api/MIGRATION_GUIDE.md)"

echo ""
echo "📋 Phase 6: Create validation script"
echo "==================================="

cat > scripts/cleanup/validate_api_migration.sh << 'EOF'
#!/bin/bash

# API Migration Validation Script
echo "🔍 Validating API Migration..."

# Check TypeScript compilation
echo "Checking TypeScript compilation..."
cd frontend && npx tsc --noEmit
if [ $? -eq 0 ]; then
    echo "✅ TypeScript compilation successful"
else
    echo "❌ TypeScript compilation failed"
    exit 1
fi

# Check for remaining JS imports
echo "Checking for remaining JavaScript API imports..."
remaining_js=$(find src -name "*.ts" -o -name "*.tsx" | xargs grep -l "apiClientExports" 2>/dev/null || true)

if [ -n "$remaining_js" ]; then
    echo "⚠️  Found files still using JavaScript API client:"
    echo "$remaining_js"
else
    echo "✅ No JavaScript API client imports found"
fi

# Test build
echo "Testing build process..."
npm run build
if [ $? -eq 0 ]; then
    echo "✅ Build successful"
else
    echo "❌ Build failed"
    exit 1
fi

echo "🎉 API migration validation completed!"
EOF

chmod +x scripts/cleanup/validate_api_migration.sh
echo -e "${GREEN}✓${NC} Created validation script (scripts/cleanup/validate_api_migration.sh)"

echo ""
echo "📊 Summary"
echo "=========="

echo ""
echo -e "${GREEN}✅ API Client Consolidation Plan Created${NC}"
echo ""
echo "Files created:"
echo "  - frontend/src/services/api/index.ts (Unified API client)"
echo "  - frontend/src/services/api/MIGRATION_GUIDE.md"
echo "  - scripts/cleanup/validate_api_migration.sh"
echo ""
echo "Files backed up to: $backup_dir"
echo ""
echo "🚀 Next Steps:"
echo "1. Review the unified API client structure"
echo "2. Update imports in components to use new API"
echo "3. Run validation script to test migration"
echo "4. Remove old JavaScript API client files after validation"
echo ""
echo "💡 Migration Benefits:"
echo "  - Full TypeScript support"
echo "  - Consistent API patterns"
echo "  - Better maintainability"
echo "  - Improved developer experience"

echo ""
echo -e "${BLUE}ℹ${NC} To complete migration:"
echo "  1. Run: bash scripts/cleanup/validate_api_migration.sh" 
echo "  2. Update component imports gradually"
echo "  3. Test functionality thoroughly"
echo "  4. Remove JavaScript files when migration is complete"