-- Generated by backend/scripts/generate_sales_invoice_product_identity_migration.py.
-- Alembic owns the transaction; this file must not be applied directly.
SET LOCAL ROLE erp_migration_owner;

CREATE OR REPLACE FUNCTION erp_automation_commands.resolve_sales_invoice_product_identities(
    organization_id uuid,
    resolution jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
    requested_count integer;
    matched_count integer;
    product_references jsonb;
BEGIN
    IF organization_id IS NULL
       OR organization_id IS DISTINCT FROM erp_security.current_org_id()
       OR pg_catalog.jsonb_typeof(resolution) <> 'object'
       OR pg_catalog.jsonb_typeof(resolution->'lines') <> 'array' THEN
      RAISE EXCEPTION USING ERRCODE='42501',
        MESSAGE='sales-invoice product identity context is unavailable';
    END IF;

    WITH requested AS (
      SELECT DISTINCT
        (line.value->>'product_id')::uuid AS product_id,
        (line.value->>'product_row_version')::bigint AS product_row_version
      FROM pg_catalog.jsonb_array_elements(resolution->'lines') line(value)
      WHERE line.value->>'line_kind'='product'
    ), matched AS (
      SELECT requested.product_id, requested.product_row_version,
             product.sku AS product_code, product.name AS product_name
      FROM requested
      JOIN catalog.products product
        ON product.org_id=organization_id
       AND product.id=requested.product_id
       AND product.row_version=requested.product_row_version
       AND product.status='active'
    )
    SELECT
      (SELECT pg_catalog.count(*) FROM requested),
      pg_catalog.count(*),
      pg_catalog.jsonb_agg(
        pg_catalog.jsonb_build_object(
          'resource_type','product',
          'id',matched.product_id,
          'row_version',matched.product_row_version,
          'product_code',matched.product_code,
          'product_name',matched.product_name
        ) ORDER BY matched.product_id
      )
    INTO requested_count, matched_count, product_references
    FROM matched;

    IF requested_count<1 OR matched_count IS DISTINCT FROM requested_count
       OR product_references IS NULL THEN
      RAISE EXCEPTION USING ERRCODE='55000',
        MESSAGE='sales-invoice product identity differs from resolved product versions';
    END IF;
    RETURN product_references;
END
$function$;

ALTER FUNCTION erp_automation_commands.resolve_sales_invoice_product_identities(uuid,jsonb) OWNER TO erp_migration_owner;
REVOKE ALL ON FUNCTION erp_automation_commands.resolve_sales_invoice_product_identities(uuid,jsonb) FROM PUBLIC, erp_app, erp_runtime, erp_calculator;
GRANT EXECUTE ON FUNCTION erp_automation_commands.resolve_sales_invoice_product_identities(uuid,jsonb) TO erp_calculator;

RESET ROLE;
