-- Generated by backend/scripts/generate_sales_order_delivery_date_migration.py.
-- Alembic owns the transaction; this file must not be applied directly.
SET LOCAL ROLE erp_migration_owner;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_sales_order_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE
    branch_id uuid := NULLIF(request_document->>'branch_id','')::uuid;
    customer_account_id uuid := NULLIF(request_document->>'customer_account_id','')::uuid;
    delivery_address_id uuid := NULLIF(request_document->>'delivery_address_id','')::uuid;
    delivery_address_row_version bigint := NULLIF(request_document->>'delivery_address_row_version','')::bigint;
    customer_party_id uuid;
    order_date date := NULLIF(request_document->>'order_date','')::date;
    requested_delivery_date date := NULLIF(request_document->>'requested_delivery_date','')::date;
    zero_rated_payment_mode text := request_document->>'zero_rated_payment_mode';
    supply_type text;
    customer_account parties.customer_accounts%ROWTYPE;
    customer_registration parties.tax_registrations%ROWTYPE;
    billing_address parties.addresses%ROWTYPE;
    shipping_address parties.addresses%ROWTYPE;
    branch core.branches%ROWTYPE;
    line_count integer;
    resolved_count integer;
    ruleset_count integer;
    address_count integer;
    registration_count integer;
    resolved_lines jsonb;
BEGIN
    IF SESSION_USER<>'erp_calculator' OR organization_id IS NULL OR membership_id IS NULL
       OR auth_user_id IS NULL OR application_user_id IS NULL OR grant_id IS NULL
       OR branch_id IS NULL OR customer_account_id IS NULL OR order_date IS NULL
       OR requested_delivery_date IS NULL
       OR delivery_address_id IS NULL OR delivery_address_row_version IS NULL
       OR delivery_address_row_version<1 OR request_document?'place_of_supply_state_code'
       OR request_document?'shipping_address_id'
       OR zero_rated_payment_mode NOT IN ('not_applicable','without_payment','with_igst')
       OR pg_catalog.jsonb_typeof(request_document)<>'object'
       OR pg_catalog.jsonb_typeof(request_document->'lines')<>'array'
       OR pg_catalog.jsonb_array_length(request_document->'lines') NOT BETWEEN 1 AND 500 THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='sales-order resolve input is incomplete';
    END IF;
    IF requested_delivery_date<order_date THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='sales-order requested delivery date precedes order date';
    END IF;
    PERFORM 1
      FROM core.memberships AS membership
      JOIN core.users AS user_row ON user_row.id=membership.user_id
      JOIN core.organizations AS organization ON organization.id=membership.org_id
      JOIN automation.agent_grants AS grant_row
        ON grant_row.org_id=membership.org_id
       AND grant_row.subject_membership_id=membership.id
      JOIN automation.agent_grant_capabilities AS capability
        ON capability.org_id=grant_row.org_id AND capability.agent_grant_id=grant_row.id
     WHERE membership.org_id=organization_id AND membership.id=membership_id
       AND membership.user_id=application_user_id AND membership.status='active'
       AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
       AND organization.status='active' AND grant_row.id=grant_id
       AND grant_row.client_id=caller_client_id AND grant_row.status='active'
       AND grant_row.expires_at>pg_catalog.transaction_timestamp()
       AND (grant_row.branch_id IS NULL OR grant_row.branch_id=branch_id)
       AND capability.capability_code='sales.order.prepare'
       AND capability.operation_mode='write' AND capability.status='active';
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-order delegated authority is inactive';
    END IF;
    PERFORM erp_security.activate_context(auth_user_id,organization_id);
    IF erp_security.current_membership_id() IS DISTINCT FROM membership_id THEN
        RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-order verified auth context resolved a different membership';
    END IF;
    IF erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('sales.order.create',branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('automation.command.execute',branch_id) IS DISTINCT FROM true THEN
        RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-order branch permission is inactive';
    END IF;
    SELECT * INTO STRICT branch FROM core.branches
     WHERE org_id=organization_id AND id=branch_id AND status='active' FOR SHARE;
    SELECT * INTO STRICT customer_account FROM parties.customer_accounts
     WHERE org_id=organization_id AND id=customer_account_id AND status='active' FOR SHARE;
    customer_party_id:=customer_account.party_id;
    SELECT count(*) INTO address_count FROM parties.addresses
     WHERE org_id=organization_id AND party_id=customer_party_id
       AND address_kind='billing' AND is_primary AND status='active'
       AND valid_from<=order_date AND (valid_until IS NULL OR valid_until>=order_date);
    IF address_count>1 THEN
        RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='customer has ambiguous effective primary billing addresses';
    ELSIF address_count=1 THEN
        SELECT * INTO STRICT billing_address FROM parties.addresses
         WHERE org_id=organization_id AND party_id=customer_party_id
           AND address_kind='billing' AND is_primary AND status='active'
           AND valid_from<=order_date AND (valid_until IS NULL OR valid_until>=order_date) FOR SHARE;
    ELSE
        SELECT * INTO STRICT billing_address FROM parties.addresses
         WHERE org_id=organization_id AND party_id=customer_party_id
           AND address_kind='registered' AND is_primary AND status='active'
           AND valid_from<=order_date AND (valid_until IS NULL OR valid_until>=order_date) FOR SHARE;
    END IF;
    SELECT * INTO STRICT shipping_address FROM parties.addresses
     WHERE org_id=organization_id AND id=delivery_address_id
       AND party_id=customer_party_id
       AND address_kind IN ('registered','billing','shipping') AND status='active'
       AND row_version=delivery_address_row_version
       AND valid_from<=order_date AND (valid_until IS NULL OR valid_until>=order_date)
     FOR SHARE;
    IF shipping_address.country_code<>'IN' OR shipping_address.state_code!~'^[0-9]{2}$'
       OR shipping_address.postal_code!~'^[0-9]{6}$' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='selected delivery address lacks exact supported India address facts';
    END IF;

    SELECT count(*) INTO registration_count FROM parties.tax_registrations
     WHERE org_id=organization_id AND party_id=customer_party_id
       AND registration_type='GSTIN' AND status='active'
       AND (valid_from IS NULL OR valid_from<=order_date)
       AND (valid_until IS NULL OR valid_until>=order_date);
    IF registration_count>1 THEN
        RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='customer has ambiguous effective active GST registrations';
    ELSIF registration_count=1 THEN
        SELECT * INTO STRICT customer_registration FROM parties.tax_registrations
         WHERE org_id=organization_id AND party_id=customer_party_id
           AND registration_type='GSTIN' AND status='active'
           AND (valid_from IS NULL OR valid_from<=order_date)
           AND (valid_until IS NULL OR valid_until>=order_date) FOR SHARE;
    END IF;
    supply_type:=CASE
      WHEN registration_count=1 AND customer_registration.taxpayer_type IN ('sez_unit','sez_developer') THEN 'sez'
      WHEN branch.state_code=shipping_address.state_code THEN 'intra_state'
      ELSE 'inter_state'
    END;
    IF (supply_type='sez' AND zero_rated_payment_mode NOT IN ('without_payment','with_igst'))
       OR (supply_type<>'sez' AND zero_rated_payment_mode<>'not_applicable') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='zero-rated payment mode does not match exact customer GST status';
    END IF;

    line_count:=pg_catalog.jsonb_array_length(request_document->'lines')
      +pg_catalog.jsonb_array_length(COALESCE(request_document->'charge_lines','[]'::jsonb));
    WITH requested_products AS (
        SELECT item.value AS line, item.ordinality::integer AS line_number
          FROM pg_catalog.jsonb_array_elements(request_document->'lines') WITH ORDINALITY AS item(value,ordinality)
    ), resolved_products AS (
        SELECT requested.line_number,tax_version.ruleset_version,
               pg_catalog.jsonb_build_object(
                 'line_number',requested.line_number,'line_kind','product',
                 'line_id',NULLIF(requested.line->>'line_id','')::uuid,
                 'product_id',product.id,'product_row_version',product.row_version,
                 'hsn_code',product.hsn_code,'uom_conversion_id',conversion.id,
                 'uom_code',conversion.from_uom_code,'to_uom_code',conversion.to_uom_code,
                 'multiplier',conversion.multiplier::text,
                 'uom_valid_from',conversion.valid_from,'uom_valid_until',conversion.valid_until,
                 'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
                 'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
                 'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version,
                 'taxability',CASE WHEN supply_type='sez' THEN 'zero_rated' ELSE tax_version.taxability END,
                 'gst_rate',CASE
                   WHEN supply_type='sez' AND zero_rated_payment_mode='without_payment' THEN '0'
                   WHEN supply_type='sez' THEN tax_version.igst_rate::text
                   WHEN tax_version.taxability='taxable' THEN tax_version.igst_rate::text ELSE '0' END,
                 'cess_rate',CASE WHEN supply_type<>'sez' AND tax_version.taxability='taxable'
                                  THEN tax_version.cess_rate::text ELSE '0' END,
                 'ruleset_version',tax_version.ruleset_version,'input',requested.line
               ) AS resolved_line
          FROM requested_products AS requested
          JOIN catalog.products AS product
            ON product.org_id=organization_id
           AND product.id=NULLIF(requested.line->>'product_id','')::uuid
           AND product.status='active'
          JOIN catalog.uom_conversions AS conversion
            ON conversion.org_id=product.org_id
           AND conversion.id=NULLIF(requested.line->>'uom_conversion_id','')::uuid
           AND conversion.product_id=product.id AND conversion.status='active'
           AND conversion.to_uom_code=product.base_uom_code
           AND conversion.valid_from<=order_date
           AND (conversion.valid_until IS NULL OR conversion.valid_until>=order_date)
          JOIN tax.tax_code_versions AS tax_version
            ON tax_version.code=product.hsn_code AND tax_version.code_kind='hsn'
           AND tax_version.status='active' AND tax_version.effective_from<=order_date
           AND (tax_version.effective_to IS NULL OR tax_version.effective_to>=order_date)
          JOIN core.reference_data_releases AS tax_release
            ON tax_release.id=tax_version.release_id AND tax_release.dataset_kind='hsn_sac_tax'
           AND tax_release.status='active' AND tax_release.effective_from<=order_date
           AND (tax_release.effective_to IS NULL OR tax_release.effective_to>=order_date)
         FOR SHARE OF product,conversion,tax_version,tax_release
    ), requested_charges AS (
        SELECT item.value AS line,
               pg_catalog.jsonb_array_length(request_document->'lines')+item.ordinality::integer AS line_number
          FROM pg_catalog.jsonb_array_elements(
                 COALESCE(request_document->'charge_lines','[]'::jsonb)
               ) WITH ORDINALITY AS item(value,ordinality)
    ), resolved_charges AS (
        SELECT requested.line_number,tax_version.ruleset_version,
               pg_catalog.jsonb_build_object(
                 'line_number',requested.line_number,'line_kind','charge',
                 'line_id',NULLIF(requested.line->>'line_id','')::uuid,
                 'charge_code',profile.charge_code,
                 'charge_tax_profile_id',profile.id,'charge_tax_profile_row_version',profile.row_version,
                 'charge_tax_profile_effective_from',profile.effective_from,
                 'charge_tax_profile_effective_to',profile.effective_to,
                 'sac_code',tax_version.code,'tax_code_version_id',tax_version.id,
                 'tax_version_number',tax_version.version_number,
                 'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
                 'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version,
                 'taxability',CASE WHEN supply_type='sez' THEN 'zero_rated' ELSE tax_version.taxability END,
                 'gst_rate',CASE
                   WHEN supply_type='sez' AND zero_rated_payment_mode='without_payment' THEN '0'
                   WHEN supply_type='sez' THEN tax_version.igst_rate::text
                   WHEN tax_version.taxability='taxable' THEN tax_version.igst_rate::text ELSE '0' END,
                 'cess_rate',CASE WHEN supply_type<>'sez' AND tax_version.taxability='taxable'
                                  THEN tax_version.cess_rate::text ELSE '0' END,
                 'ruleset_version',tax_version.ruleset_version,'input',requested.line
               ) AS resolved_line
          FROM requested_charges AS requested
          JOIN catalog.commercial_charge_tax_profiles AS profile
            ON profile.org_id=organization_id AND profile.direction='sales'
           AND profile.charge_code=requested.line->>'charge_code' AND profile.status='active'
           AND profile.effective_from<=order_date
           AND (profile.effective_to IS NULL OR profile.effective_to>=order_date)
          JOIN tax.tax_code_versions AS tax_version
            ON tax_version.id=profile.tax_code_version_id AND tax_version.code_kind='sac'
           AND tax_version.status='active' AND tax_version.effective_from<=order_date
           AND (tax_version.effective_to IS NULL OR tax_version.effective_to>=order_date)
          JOIN core.reference_data_releases AS tax_release
            ON tax_release.id=tax_version.release_id AND tax_release.dataset_kind='hsn_sac_tax'
           AND tax_release.status='active' AND tax_release.effective_from<=order_date
           AND (tax_release.effective_to IS NULL OR tax_release.effective_to>=order_date)
         FOR SHARE OF profile,tax_version,tax_release
    ), resolved AS (
        SELECT * FROM resolved_products UNION ALL SELECT * FROM resolved_charges
    )
    SELECT count(*),count(DISTINCT ruleset_version),
           pg_catalog.jsonb_agg(resolved_line ORDER BY line_number)
      INTO resolved_count,ruleset_count,resolved_lines FROM resolved;
    IF resolved_count<>line_count OR ruleset_count<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='sales-order product, charge, UOM, or effective tax resolution is not exact';
    END IF;
    RETURN pg_catalog.jsonb_build_object(
        'branch_id',branch.id,'branch_row_version',branch.row_version,
        'branch_state_code',branch.state_code,
        'supply_type',supply_type,'zero_rated_payment_mode',zero_rated_payment_mode,
        'customer_party_id',customer_party_id,'customer_account_id',customer_account.id,
        'customer_account_row_version',customer_account.row_version,
        'customer_tax_registration_id',CASE WHEN registration_count=1 THEN customer_registration.id ELSE NULL END,
        'customer_tax_registration_row_version',CASE WHEN registration_count=1 THEN customer_registration.row_version ELSE NULL END,
        'customer_taxpayer_type',CASE WHEN registration_count=1 THEN customer_registration.taxpayer_type ELSE NULL END,
        'billing_address_id',billing_address.id,'billing_address_row_version',billing_address.row_version,
        'shipping_address_id',shipping_address.id,'shipping_address_row_version',shipping_address.row_version,
        'shipping_state_code',shipping_address.state_code,
        'order_date',order_date,'requested_delivery_date',requested_delivery_date,
        'lines',resolved_lines,
        'ruleset_version',resolved_lines->0->>'ruleset_version'
    );
END
$function$;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_sales_order_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, order_id uuid, command_id uuid, artifact_id uuid, request_id uuid, key_hash bytea, sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, calculation_input_bytes bytea, calculation_output_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE
    request_document jsonb;
    resolved_document jsonb;
    current_resolution jsonb;
    input_document jsonb;
    output_document jsonb;
    totals jsonb;
    line jsonb;
    resolved_line jsonb;
    sequence_id uuid;
    claim_id uuid;
    replay_id uuid;
    order_number text;
    branch_id uuid;
    order_date date;
    fiscal_year integer;
    aggregate_hash bytea;
    requested_total numeric(20,2);
    existing automation.command_requests%ROWTYPE;
BEGIN
    IF SESSION_USER<>'erp_calculator' OR order_id IS NULL OR command_id IS NULL
       OR artifact_id IS NULL OR request_id IS NULL
       OR pg_catalog.octet_length(key_hash)<>32
       OR pg_catalog.octet_length(sequence_key_hash)<>32
       OR pg_catalog.octet_length(request_bytes) NOT BETWEEN 2 AND 1048576
       OR pg_catalog.octet_length(resolved_bytes) NOT BETWEEN 2 AND 1048576
       OR pg_catalog.octet_length(preview_bytes) NOT BETWEEN 2 AND 1048576
       OR pg_catalog.octet_length(calculation_input_bytes) NOT BETWEEN 2 AND 1048576
       OR pg_catalog.octet_length(calculation_output_bytes) NOT BETWEEN 2 AND 1048576 THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='sales-order prepare persistence envelope is invalid';
    END IF;
    BEGIN
        request_document:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
        resolved_document:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
        input_document:=pg_catalog.convert_from(calculation_input_bytes,'UTF8')::jsonb;
        output_document:=pg_catalog.convert_from(calculation_output_bytes,'UTF8')::jsonb;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='sales-order prepare persistence requires UTF-8 JSON';
    END;
    current_resolution:="erp_automation_commands"."resolve_sales_order_prepare"(
        organization_id,membership_id,auth_user_id,application_user_id,grant_id,
        caller_client_id,request_document
    );
    PERFORM pg_catalog.set_config('app.request_id',request_id::text,true);
    IF current_resolution IS DISTINCT FROM resolved_document
       OR output_document->>'operation'<>'sales.order.approve'
       OR output_document->>'resource_type'<>'sales_order'
       OR output_document->>'resource_id'<>order_id::text
       OR (output_document->>'aggregate_version')::bigint<>1
       OR output_document->>'serializer_version'<>'aasopharma-jcs-decimal-v1'
       OR input_document->>'serializer_version'<>'aasopharma-jcs-decimal-v1'
       OR input_document#>>'{document,zero_rated_mode}' IS DISTINCT FROM resolved_document->>'zero_rated_payment_mode'
       OR input_document#>>'{document,gst_type}' IS DISTINCT FROM
          (CASE WHEN resolved_document->>'supply_type'='intra_state' THEN 'intra_state' ELSE 'inter_state' END)
       OR pg_catalog.jsonb_typeof(output_document->'lines')<>'array'
       OR pg_catalog.jsonb_array_length(output_document->'lines')<>
          pg_catalog.jsonb_array_length(resolved_document->'lines')
       OR pg_catalog.jsonb_array_length(input_document#>'{document,products}')
          +pg_catalog.jsonb_array_length(input_document#>'{document,charges}')<>
          pg_catalog.jsonb_array_length(resolved_document->'lines') THEN
        RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='sales-order resolution or calculation output changed';
    END IF;
    SELECT * INTO existing FROM automation.command_requests
     WHERE org_id=organization_id AND agent_grant_id=grant_id
       AND capability_code='sales.order.prepare' AND idempotency_key_hash=key_hash
     FOR SHARE;
    IF FOUND THEN
        IF existing.target_resource_id IS DISTINCT FROM order_id
           OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
           OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256') THEN
            RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='sales-order idempotency key has different exact input';
        END IF;
        RETURN pg_catalog.jsonb_build_object(
            'command_request_id',existing.id,'expires_at',existing.expires_at,
            'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true
        );
    END IF;
    branch_id:=NULLIF(resolved_document->>'branch_id','')::uuid;
    order_date:=(resolved_document->>'order_date')::date;
    fiscal_year:=CASE WHEN pg_catalog.date_part('month',order_date)>=4
                      THEN pg_catalog.date_part('year',order_date)::integer
                      ELSE pg_catalog.date_part('year',order_date)::integer-1 END;
    SELECT sequence.id INTO STRICT sequence_id FROM core.document_sequences AS sequence
     WHERE sequence.org_id=organization_id AND sequence.branch_id=branch_id
       AND sequence.document_type='sales_order'
       AND sequence.fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1)
       AND sequence.status='active' FOR SHARE;
    order_number:=erp_core_commands.allocate_document_number(
        organization_id,sequence_id,sequence_key_hash,expires_at
    );
    totals:=output_document->'totals';
    requested_total:=(totals->>'grand_total')::numeric;
    INSERT INTO sales.orders(
        org_id,id,branch_id,customer_account_id,order_number,fiscal_year,order_date,
        requested_delivery_date,status,
        supply_type,zero_rated_payment_mode,tax_charge_mechanism,billing_address_id,
        shipping_address_id,currency_code,calculation_ruleset_version,
        document_discount_kind,document_discount_basis,document_discount_value,
        subtotal,discount_total,charges_total,net_value_total,gst_taxable_total,
        cgst_total,sgst_total,igst_total,cess_total,recipient_assessed_tax_total,
        rounding_policy,rounding_adjustment,grand_total)
    VALUES(
        organization_id,order_id,branch_id,
        (resolved_document->>'customer_account_id')::uuid,order_number,fiscal_year,order_date,
        (resolved_document->>'requested_delivery_date')::date,'submitted',
        resolved_document->>'supply_type',resolved_document->>'zero_rated_payment_mode',
        'normal',(resolved_document->>'billing_address_id')::uuid,
        (resolved_document->>'shipping_address_id')::uuid,'INR',output_document->>'ruleset_version',
        request_document->'document_discount'->>'document_discount_kind',
        request_document->'document_discount'->>'document_discount_basis',
        (request_document->'document_discount'->>'document_discount_value')::numeric,
        (totals->>'subtotal')::numeric,(totals->>'discount_total')::numeric,
        (totals->>'charges_total')::numeric,(totals->>'net_value_total')::numeric,
        (totals->>'gst_taxable_total')::numeric,(totals->>'cgst_total')::numeric,
        (totals->>'sgst_total')::numeric,(totals->>'igst_total')::numeric,
        (totals->>'cess_total')::numeric,(totals->>'recipient_assessed_tax_total')::numeric,
        request_document->>'rounding_policy',(totals->>'rounding_adjustment')::numeric,
        requested_total);

    FOR resolved_line IN SELECT value FROM pg_catalog.jsonb_array_elements(resolved_document->'lines') LOOP
        SELECT value INTO STRICT line FROM pg_catalog.jsonb_array_elements(output_document->'lines')
         WHERE value->>'line_id'=resolved_line->>'line_id';
        INSERT INTO sales.order_lines(
            org_id,id,order_id,line_number,line_kind,product_id,charge_code,uom_code,uom_conversion_factor,
            billed_quantity,free_quantity,base_billed_quantity,base_free_quantity,
            free_supply_tax_treatment,quoted_unit_rate,price_basis,tax_charge_mechanism,
            gross_amount,line_discount_kind,line_discount_basis,line_discount_value,
            document_discount_eligible,line_discount_amount,line_taxable_discount_amount,
            document_discount_amount,document_taxable_discount_amount,net_value_amount,
            gst_taxable_value,tax_classification_code_snapshot,tax_code_version_id,
            taxability_snapshot,cgst_rate,sgst_rate,igst_rate,cess_rate,cgst_amount,
            sgst_amount,igst_amount,cess_amount,line_total)
        VALUES(
            organization_id,(resolved_line->>'line_id')::uuid,order_id,
            (resolved_line->>'line_number')::integer,resolved_line->>'line_kind',
            NULLIF(resolved_line->>'product_id','')::uuid,resolved_line->>'charge_code',
            resolved_line->>'uom_code',NULLIF(resolved_line->>'multiplier','')::numeric,
            NULLIF(resolved_line->'input'->>'billed_quantity','')::numeric,
            NULLIF(resolved_line->'input'->>'free_quantity','')::numeric,
            CASE WHEN resolved_line->>'line_kind'='product' THEN
              (resolved_line->'input'->>'billed_quantity')::numeric*(resolved_line->>'multiplier')::numeric ELSE NULL END,
            CASE WHEN resolved_line->>'line_kind'='product' THEN
              (resolved_line->'input'->>'free_quantity')::numeric*(resolved_line->>'multiplier')::numeric ELSE NULL END,
            CASE WHEN resolved_line->>'line_kind'='product'
                 THEN resolved_line->'input'->>'free_supply_tax_treatment' ELSE NULL END,
            NULLIF(resolved_line->'input'->>'quoted_unit_rate','')::numeric,
            resolved_line->'input'->>'price_basis','normal',(line->>'gross_amount')::numeric,
            CASE WHEN resolved_line->>'line_kind'='product'
                 THEN resolved_line->'input'->'line_discount'->>'line_discount_kind' ELSE 'none' END,
            CASE WHEN resolved_line->>'line_kind'='product'
                 THEN resolved_line->'input'->'line_discount'->>'line_discount_basis' ELSE 'price_value' END,
            CASE WHEN resolved_line->>'line_kind'='product'
                 THEN (resolved_line->'input'->'line_discount'->>'line_discount_value')::numeric ELSE 0 END,
            (resolved_line->'input'->>'document_discount_eligible')::boolean,
            (line->>'line_discount_amount')::numeric,
            (line->>'line_taxable_discount_amount')::numeric,
            (line->>'document_discount_amount')::numeric,
            (line->>'document_taxable_discount_amount')::numeric,
            (line->>'net_value_amount')::numeric,(line->>'gst_taxable_value')::numeric,
            CASE WHEN resolved_line->>'line_kind'='product' THEN resolved_line->>'hsn_code'
                 ELSE resolved_line->>'sac_code' END,(resolved_line->>'tax_code_version_id')::uuid,
            resolved_line->>'taxability',(line->>'cgst_rate')::numeric,
            (line->>'sgst_rate')::numeric,(line->>'igst_rate')::numeric,
            (line->>'cess_rate')::numeric,(line->>'cgst_amount')::numeric,
            (line->>'sgst_amount')::numeric,(line->>'igst_amount')::numeric,
            (line->>'cess_amount')::numeric,(line->>'line_total')::numeric);
    END LOOP;
    PERFORM erp_trade_commands_v2.assert_sales_order_artifact(
        organization_id,order_id,input_document,output_document
    );
    aggregate_hash:="erp_automation_commands"."aggregate_version_hash"('sales_order',order_id,1);
    PERFORM "erp_automation_commands"."prepare_operator_command"(
        organization_id,command_id,grant_id,'sales.order.prepare',branch_id,NULL::uuid,
        order_id,requested_total,'INR',key_hash,request_bytes,preview_bytes,NULL::bytea,
        aggregate_hash,expires_at
    );
    SELECT p_claim_id,p_replay_resource_id INTO claim_id,replay_id
      FROM erp_trade_commands.claim(
        organization_id,membership_id,'sales.order.approve',key_hash,
        extensions.digest(request_bytes,'sha256'),expires_at
      );
    IF replay_id IS NOT NULL THEN
        RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='sales-order prepare replay reached a completed execution claim';
    END IF;
    PERFORM erp_calculation_authority.issue_artifact(
        artifact_id,branch_id,'sales.order.approve','sales_order',order_id,1,
        request_id,command_id,claim_id,extensions.digest(request_bytes,'sha256'),
        calculation_input_bytes,calculation_output_bytes,output_document->>'engine_version',
        output_document->>'ruleset_version','aasopharma-jcs-decimal-v1',expires_at
    );
    RETURN pg_catalog.jsonb_build_object(
        'command_request_id',command_id,'expires_at',expires_at,
        'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),
        'replayed',false
    );
END
$function$;
RESET ROLE;
