-- Generated by backend/scripts/generate_finance_business_date_context_migration.py.
-- Alembic owns the transaction; this file must not be applied directly.
SET LOCAL ROLE erp_migration_owner;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_customer_receipt_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE branch_id uuid:=NULLIF(request_document->>'branch_id','')::uuid;
        payment_date date:=NULLIF(request_document->>'payment_date','')::date;
        customer_id uuid:=NULLIF(request_document->>'customer_account_id','')::uuid;
        bank_id uuid:=NULLIF(request_document->>'bank_account_id','')::uuid;
        settlement_id uuid:=NULLIF(request_document->>'settlement_account_id','')::uuid;
        payment_amount numeric(20,2):=NULLIF(request_document->>'amount','')::numeric;
        method text:=request_document->>'payment_method'; reference text:=upper(NULLIF(pg_catalog.btrim(request_document->>'external_reference'),''));
        branch core.branches%ROWTYPE; customer parties.customer_accounts%ROWTYPE; party parties.parties%ROWTYPE;
        bank finance.bank_accounts%ROWTYPE; settlement finance.accounts%ROWTYPE; receivable finance.accounts%ROWTYPE;
        requested jsonb; item finance.open_items%ROWTYPE; event finance.accounting_events%ROWTYPE; invoice sales.invoices%ROWTYPE;
        resolved_allocations jsonb:='[]'::jsonb; source_versions jsonb:='[]'::jsonb;
        prior_allocated numeric(20,2); requested_total numeric(20,2):=0; allocation_count integer; duplicate_count integer;
        allocation_state_hash text;
BEGIN
  IF organization_id IS NULL OR membership_id IS NULL OR auth_user_id IS NULL OR application_user_id IS NULL
     OR grant_id IS NULL OR payment_id IS NULL OR branch_id IS NULL OR payment_date IS NULL OR customer_id IS NULL
     OR bank_id IS NULL OR settlement_id IS NULL OR payment_amount<=0 OR method NOT IN ('bank_transfer','card','upi')
     OR reference IS NULL OR pg_catalog.length(reference)>256
     OR pg_catalog.jsonb_typeof(request_document->'allocations')<>'array'
     OR pg_catalog.jsonb_array_length(request_document->'allocations') NOT BETWEEN 1 AND 500 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='customer-receipt noncash INR pilot input is incomplete'; END IF;
  PERFORM 1 FROM core.memberships membership JOIN core.users user_row ON user_row.id=membership.user_id
    JOIN core.organizations organization_row ON organization_row.id=membership.org_id
    JOIN automation.agent_grants grant_row ON grant_row.org_id=membership.org_id AND grant_row.subject_membership_id=membership.id
    JOIN automation.agent_grant_capabilities capability ON capability.org_id=grant_row.org_id AND capability.agent_grant_id=grant_row.id
   WHERE membership.org_id=organization_id AND membership.id=membership_id AND membership.user_id=application_user_id
     AND membership.status='active' AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
     AND organization_row.status='active' AND organization_row.country_code='IN' AND organization_row.base_currency='INR'
     AND grant_row.id=grant_id AND grant_row.client_id=caller_client_id AND grant_row.status='active'
     AND grant_row.expires_at>pg_catalog.transaction_timestamp() AND (grant_row.branch_id IS NULL OR grant_row.branch_id=branch_id)
     AND capability.capability_code='finance.customer_receipt.prepare' AND capability.operation_mode='write' AND capability.status='active';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='customer-receipt delegated authority is inactive'; END IF;
  PERFORM erp_security.activate_context(auth_user_id,organization_id);
  IF erp_security.current_membership_id() IS DISTINCT FROM membership_id OR erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.payment.manage',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.payment.allocate',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.journal.post',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('automation.command.execute',branch_id) IS DISTINCT FROM true THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='customer-receipt verified context or cross-domain permission is inactive'; END IF;
  IF payment_date>"erp_core_commands"."current_organization_business_date"() THEN
    RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='customer receipt date cannot be in the future'; END IF;
  IF (SELECT count(DISTINCT value->>'open_item_id') FROM pg_catalog.jsonb_array_elements(request_document->'allocations'))
       <>pg_catalog.jsonb_array_length(request_document->'allocations') THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='customer receipt requires unique receivable allocations'; END IF;
  SELECT * INTO STRICT branch FROM core.branches WHERE org_id=organization_id AND id=branch_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT customer FROM parties.customer_accounts WHERE org_id=organization_id AND id=customer_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT party FROM parties.parties WHERE org_id=organization_id AND id=customer.party_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT receivable FROM finance.accounts WHERE org_id=organization_id
    AND id=erp_commercial_commands.resolve_role_account(organization_id,branch_id,'accounts_receivable','asset','INR',true)
    AND status='active' AND account_type='asset' AND currency_code='INR' AND allows_party_posting FOR SHARE;
  IF customer.default_receivable_account_id IS DISTINCT FROM receivable.id THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='customer default receivable does not match canonical branch account role'; END IF;
  SELECT * INTO STRICT bank FROM finance.bank_accounts WHERE org_id=organization_id AND id=bank_id
    AND status='active' AND currency_code='INR' FOR SHARE;
  SELECT * INTO STRICT settlement FROM finance.accounts WHERE org_id=organization_id AND id=settlement_id
    AND id=bank.account_id AND status='active' AND account_type='asset' AND currency_code='INR'
    AND allows_bank_reconciliation FOR SHARE;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    organization_id::text||':customer-receipt:'||bank.id::text||':'||reference||':'||payment_date::text||':'||payment_amount::text,672009));
  SELECT count(*) INTO duplicate_count FROM finance.payments existing
   WHERE existing.org_id=organization_id AND existing.bank_account_id=bank.id
     AND upper(pg_catalog.btrim(existing.external_reference))=reference AND existing.payment_date=payment_date
     AND existing.amount=payment_amount AND existing.status<>'reversed' AND existing.id<>payment_id;
  IF duplicate_count<>0 THEN
    RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='customer receipt bank reference, date, and amount already exist'; END IF;
  PERFORM 1 FROM finance.open_items candidate
   JOIN pg_catalog.jsonb_array_elements(request_document->'allocations') payload(value)
     ON candidate.id=(payload.value->>'open_item_id')::uuid
   WHERE candidate.org_id=organization_id ORDER BY candidate.id FOR UPDATE OF candidate;
  FOR requested IN SELECT value FROM pg_catalog.jsonb_array_elements(request_document->'allocations') LOOP
    IF NULLIF(requested->>'allocation_id','')::uuid IS NULL OR NULLIF(requested->>'open_item_id','')::uuid IS NULL
       OR NULLIF(requested->>'amount','')::numeric<=0 THEN
      RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='customer receipt allocation identity and positive amount are required'; END IF;
    SELECT * INTO STRICT item FROM finance.open_items WHERE org_id=organization_id
      AND id=(requested->>'open_item_id')::uuid AND item_side='receivable' AND party_id=party.id
      AND currency_code='INR' AND status='open' AND document_date<=payment_date FOR UPDATE;
    SELECT * INTO STRICT event FROM finance.accounting_events WHERE org_id=organization_id
      AND id=item.accounting_event_id AND event_type='sales_invoice' AND sales_invoice_id IS NOT NULL FOR SHARE;
    SELECT * INTO STRICT invoice FROM sales.invoices WHERE org_id=organization_id AND id=event.sales_invoice_id
      AND branch_id=branch.id AND customer_account_id=customer.id AND currency_code='INR' AND status='posted' FOR SHARE;
    PERFORM 1 FROM finance.allocations prior WHERE prior.org_id=organization_id AND prior.open_item_id=item.id ORDER BY prior.id FOR SHARE;
    SELECT coalesce(sum(prior.amount),0),count(*) INTO prior_allocated,allocation_count FROM finance.allocations prior
     WHERE prior.org_id=organization_id AND prior.open_item_id=item.id AND prior.status='posted'
       AND prior.reversal_of_allocation_id IS NULL AND NOT EXISTS (
         SELECT 1 FROM finance.allocations reversal WHERE reversal.org_id=prior.org_id
           AND reversal.reversal_of_allocation_id=prior.id AND reversal.status='reversed');
    SELECT pg_catalog.encode(extensions.digest(pg_catalog.convert_to(coalesce(pg_catalog.jsonb_agg(
        pg_catalog.jsonb_build_object('id',prior.id,'payment_id',prior.payment_id,'withholding_id',prior.withholding_id,
          'adjustment_note_id',prior.adjustment_note_id,'purchase_order_advance_allocation_id',prior.purchase_order_advance_allocation_id,
          'amount',prior.amount::text,'status',prior.status,'reversal_of_allocation_id',prior.reversal_of_allocation_id)
        ORDER BY prior.id),'[]'::jsonb)::text,'UTF8'),'sha256'),'hex') INTO allocation_state_hash
      FROM finance.allocations prior WHERE prior.org_id=organization_id AND prior.open_item_id=item.id;
    IF prior_allocated+(requested->>'amount')::numeric>item.principal_amount THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='customer receipt allocation exceeds live receivable balance'; END IF;
    requested_total:=requested_total+(requested->>'amount')::numeric;
    resolved_allocations:=resolved_allocations||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'allocation_id',requested->>'allocation_id','open_item_id',item.id,'invoice_id',invoice.id,
      'document_number',item.document_number,'principal_amount',item.principal_amount::text,
      'prior_allocated_amount',prior_allocated::text,'amount',(requested->>'amount')::numeric::text,
      'residual_after',(item.principal_amount-prior_allocated-(requested->>'amount')::numeric)::text));
    source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'resource_type','receivable_allocation_state','id',item.id,'invoice_id',invoice.id,'invoice_row_version',invoice.row_version,
      'principal_amount',item.principal_amount::text,'status',item.status,'allocation_count',allocation_count,
      'active_allocated_amount',prior_allocated::text,'allocation_state_hash',allocation_state_hash));
  END LOOP;
  IF requested_total<>payment_amount THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='customer receipt allocations must exactly equal payment amount'; END IF;
  source_versions:=pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_object('resource_type','branch','id',branch.id,'row_version',branch.row_version),
    pg_catalog.jsonb_build_object('resource_type','customer_account','id',customer.id,'row_version',customer.row_version),
    pg_catalog.jsonb_build_object('resource_type','customer_party','id',party.id,'row_version',party.row_version),
    pg_catalog.jsonb_build_object('resource_type','accounts_receivable_role','id',receivable.id,'row_version',receivable.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_account','id',bank.id,'row_version',bank.row_version),
    pg_catalog.jsonb_build_object('resource_type','settlement_account','id',settlement.id,'row_version',settlement.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_receipt_collision','bank_account_id',bank.id,'external_reference',reference,
      'payment_date',payment_date,'amount',payment_amount::text,'candidate_count',duplicate_count))||source_versions;
  RETURN pg_catalog.jsonb_build_object('branch_id',branch.id,'payment_id',payment_id,'payment_date',payment_date,
    'customer_account_id',customer.id,'customer_party_id',party.id,'bank_account_id',bank.id,
    'settlement_account_id',settlement.id,'accounts_receivable_account_id',receivable.id,'payment_method',method,
    'external_reference',reference,'amount',payment_amount::text,'currency_code','INR','allocations',resolved_allocations,
    'legal_scope',pg_catalog.jsonb_build_object('country_code','IN','currency_code','INR','settlement','fully_allocated_non_cash',
      'supported_payment_methods',pg_catalog.jsonb_build_array('bank_transfer','card','upi'),
      'cash','unavailable_section_269st_and_cash_account_authority','cheque','unavailable_account_payee_evidence',
      'customer_deducted_tds','unavailable_seller_tds_receivable_form16a_26as_authority',
      'fx','unavailable','advance_or_unapplied_receipt','unavailable'),
    'source_versions',source_versions);
END
$function$;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_supplier_advance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE branch_id uuid:=NULLIF(request_document->>'branch_id','')::uuid;
        payment_date date:=NULLIF(request_document->>'payment_date','')::date;
        supplier_id uuid:=NULLIF(request_document->>'supplier_account_id','')::uuid;
        purchase_order_id uuid:=NULLIF(request_document->>'purchase_order_id','')::uuid;
        bank_id uuid:=NULLIF(request_document->>'bank_account_id','')::uuid;
        settlement_id uuid:=NULLIF(request_document->>'settlement_account_id','')::uuid;
        gross numeric(20,2):=NULLIF(request_document->>'gross_amount','')::numeric;
        method text:=request_document->>'payment_method';
        reference text:=upper(NULLIF(pg_catalog.btrim(request_document->>'external_reference'),''));
        requested jsonb; branch core.branches%ROWTYPE; supplier parties.supplier_accounts%ROWTYPE;
        party parties.parties%ROWTYPE; party_evidence core.attachments%ROWTYPE;
        purchase_order procurement.purchase_orders%ROWTYPE; line procurement.purchase_order_lines%ROWTYPE;
        bank finance.bank_accounts%ROWTYPE; settlement finance.accounts%ROWTYPE; prepayment finance.accounts%ROWTYPE;
        fiscal_fact tax.organization_fiscal_tax_facts%ROWTYPE; fiscal_evidence core.attachments%ROWTYPE;
        fiscal_year smallint; prior_gross numeric(20,2); prior_count integer; duplicate_count integer;
        prior_state_hash text; source_versions jsonb; resolved_allocations jsonb;
BEGIN
  IF organization_id IS NULL OR membership_id IS NULL OR auth_user_id IS NULL OR application_user_id IS NULL
     OR grant_id IS NULL OR payment_id IS NULL OR branch_id IS NULL OR payment_date IS NULL OR supplier_id IS NULL
     OR purchase_order_id IS NULL OR bank_id IS NULL OR settlement_id IS NULL OR gross<=0
     OR method NOT IN ('bank_transfer','upi') OR reference IS NULL OR pg_catalog.length(reference)>256
     OR pg_catalog.jsonb_typeof(request_document->'allocations')<>'array'
     OR pg_catalog.jsonb_array_length(request_document->'allocations')<>1 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier-advance INR bank pilot requires exactly one complete allocation'; END IF;
  PERFORM 1 FROM core.memberships membership JOIN core.users user_row ON user_row.id=membership.user_id
    JOIN core.organizations organization_row ON organization_row.id=membership.org_id
    JOIN automation.agent_grants grant_row ON grant_row.org_id=membership.org_id AND grant_row.subject_membership_id=membership.id
    JOIN automation.agent_grant_capabilities capability ON capability.org_id=grant_row.org_id AND capability.agent_grant_id=grant_row.id
   WHERE membership.org_id=organization_id AND membership.id=membership_id AND membership.user_id=application_user_id
     AND membership.status='active' AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
     AND organization_row.status='active' AND organization_row.country_code='IN' AND organization_row.base_currency='INR'
     AND grant_row.id=grant_id AND grant_row.client_id=caller_client_id AND grant_row.status='active'
     AND grant_row.expires_at>pg_catalog.transaction_timestamp() AND (grant_row.branch_id IS NULL OR grant_row.branch_id=branch_id)
     AND capability.capability_code='finance.supplier_advance.prepare' AND capability.operation_mode='write' AND capability.status='active';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-advance delegated authority is inactive'; END IF;
  PERFORM erp_security.activate_context(auth_user_id,organization_id);
  IF erp_security.current_membership_id() IS DISTINCT FROM membership_id OR erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.payment.manage',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.journal.post',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('procurement.order.manage',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('automation.command.execute',branch_id) IS DISTINCT FROM true THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-advance verified context or cross-domain permission is inactive'; END IF;
  IF payment_date>"erp_core_commands"."current_organization_business_date"() THEN
    RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='supplier advance date cannot be in the future'; END IF;
  requested:=request_document->'allocations'->0;
  IF NULLIF(requested->>'purchase_order_line_id','')::uuid IS NULL
     OR NULLIF(requested->>'advance_allocation_id','')::uuid IS NULL
     OR NULLIF(requested->>'prepayment_open_item_id','')::uuid IS NULL
     OR NULLIF(requested->>'gross_amount','')::numeric<=0
     OR (requested->>'gross_amount')::numeric IS DISTINCT FROM gross THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier advance allocation must be positive and exactly equal gross amount'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    organization_id::text||':supplier-advance-line:'||(requested->>'purchase_order_line_id'),672004));
  SELECT * INTO STRICT branch FROM core.branches WHERE org_id=organization_id AND id=branch_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT supplier FROM parties.supplier_accounts WHERE org_id=organization_id AND id=supplier_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT party FROM parties.parties WHERE org_id=organization_id AND id=supplier.party_id AND status='active'
    AND tax_residency_status='resident' AND pan IS NOT NULL AND pan_verification_status='verified'
    AND tax_profile_verified_at IS NOT NULL AND tax_profile_verified_at<=pg_catalog.transaction_timestamp()
    AND tax_profile_evidence_attachment_id IS NOT NULL FOR SHARE;
  SELECT * INTO STRICT party_evidence FROM core.attachments WHERE org_id=organization_id
    AND id=party.tax_profile_evidence_attachment_id AND status IN ('verified','retained')
    AND verified_at IS NOT NULL AND verified_at<=pg_catalog.transaction_timestamp() FOR SHARE;
  SELECT * INTO STRICT purchase_order FROM procurement.purchase_orders WHERE org_id=organization_id AND id=purchase_order_id
    AND branch_id=branch.id AND supplier_account_id=supplier.id AND status='approved' AND currency_code='INR'
    AND supply_type IN ('intra_state','inter_state') AND zero_rated_payment_mode='not_applicable'
    AND tax_charge_mechanism='normal' AND order_date<=payment_date FOR UPDATE;
  SELECT * INTO STRICT line FROM procurement.purchase_order_lines WHERE org_id=organization_id
    AND id=(requested->>'purchase_order_line_id')::uuid AND purchase_order_id=purchase_order.id
    AND line_kind='product' AND withholding_nature_code='purchase_of_goods' AND net_value_amount>0 FOR UPDATE;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',payment_date)>=4 THEN pg_catalog.date_part('year',payment_date)::smallint
                    ELSE (pg_catalog.date_part('year',payment_date)-1)::smallint END;
  SELECT * INTO STRICT fiscal_fact FROM tax.organization_fiscal_tax_facts WHERE org_id=organization_id
    AND fiscal_year_start_year=fiscal_year AND status='active' AND payment_date BETWEEN effective_from AND effective_to
    AND prior_fiscal_year_turnover<=100000000 AND gst_tds_notified_deductor=false FOR SHARE;
  SELECT * INTO STRICT fiscal_evidence FROM core.attachments WHERE org_id=organization_id
    AND id=fiscal_fact.evidence_attachment_id AND status IN ('verified','retained') AND verified_at IS NOT NULL
    AND verified_at<=pg_catalog.transaction_timestamp() FOR SHARE;
  SELECT * INTO STRICT prepayment FROM finance.accounts WHERE org_id=organization_id
    AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'supplier_prepayment','asset','INR',true)
    AND status='active' AND account_type='asset' AND currency_code='INR' AND allows_party_posting FOR SHARE;
  SELECT * INTO STRICT bank FROM finance.bank_accounts WHERE org_id=organization_id AND id=bank_id
    AND status='active' AND currency_code='INR' FOR SHARE;
  SELECT * INTO STRICT settlement FROM finance.accounts WHERE org_id=organization_id AND id=settlement_id
    AND id=bank.account_id AND status='active' AND account_type='asset' AND currency_code='INR'
    AND allows_bank_reconciliation FOR SHARE;
  PERFORM 1 FROM procurement.purchase_order_advance_allocations prior WHERE prior.org_id=organization_id
    AND prior.purchase_order_line_id=line.id AND prior.payment_id<>payment_id ORDER BY prior.id FOR UPDATE OF prior;
  SELECT coalesce(sum(prior.gross_advance_amount),0),count(*) INTO prior_gross,prior_count
    FROM procurement.purchase_order_advance_allocations prior
   WHERE prior.org_id=organization_id AND prior.purchase_order_line_id=line.id AND prior.status='posted'
     AND prior.payment_id<>payment_id AND prior.reversal_of_allocation_id IS NULL AND NOT EXISTS (
       SELECT 1 FROM procurement.purchase_order_advance_allocations reversal
        WHERE reversal.org_id=prior.org_id AND reversal.reversal_of_allocation_id=prior.id);
  SELECT pg_catalog.encode(extensions.digest(pg_catalog.convert_to(coalesce(pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object('id',prior.id,'payment_id',prior.payment_id,'gross_advance_amount',prior.gross_advance_amount::text,
        'status',prior.status,'reversal_of_allocation_id',prior.reversal_of_allocation_id) ORDER BY prior.id),'[]'::jsonb)::text,'UTF8'),'sha256'),'hex')
    INTO prior_state_hash FROM procurement.purchase_order_advance_allocations prior
   WHERE prior.org_id=organization_id AND prior.purchase_order_line_id=line.id AND prior.payment_id<>payment_id;
  IF prior_gross+gross>line.net_value_amount THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier advance exceeds remaining purchase-order line net value'; END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    organization_id::text||':supplier-advance:'||bank.id::text||':'||reference||':'||payment_date::text||':'||gross::text,672010));
  SELECT count(*) INTO duplicate_count FROM finance.payments existing WHERE existing.org_id=organization_id
    AND existing.bank_account_id=bank.id AND upper(pg_catalog.btrim(existing.external_reference))=reference
    AND existing.payment_date=payment_date AND existing.amount=gross AND existing.status<>'reversed' AND existing.id<>payment_id;
  IF duplicate_count<>0 THEN
    RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier advance bank reference, date, and amount already exist'; END IF;
  resolved_allocations:=pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
    'id',requested->>'advance_allocation_id','purchase_order_line_id',line.id,
    'prepayment_open_item_id',requested->>'prepayment_open_item_id','cash_disbursed_amount',gross::text,
    'withheld_amount','0.00','gross_advance_amount',gross::text,'withholding_id',NULL));
  source_versions:=pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_object('resource_type','branch','id',branch.id,'row_version',branch.row_version),
    pg_catalog.jsonb_build_object('resource_type','supplier_account','id',supplier.id,'row_version',supplier.row_version),
    pg_catalog.jsonb_build_object('resource_type','supplier_party_tax_profile','id',party.id,'row_version',party.row_version,
      'pan_verification_status',party.pan_verification_status,'tax_residency_status',party.tax_residency_status,
      'evidence_attachment_id',party_evidence.id,'evidence_sha256',pg_catalog.encode(party_evidence.sha256,'hex')),
    pg_catalog.jsonb_build_object('resource_type','purchase_order','id',purchase_order.id,'row_version',purchase_order.row_version,'status',purchase_order.status),
    pg_catalog.jsonb_build_object('resource_type','purchase_order_line_advance_state','id',line.id,
      'net_value_amount',line.net_value_amount::text,'withholding_nature_code',line.withholding_nature_code,
      'prior_active_gross',prior_gross::text,'prior_count',prior_count,'prior_state_hash',prior_state_hash),
    pg_catalog.jsonb_build_object('resource_type','organization_fiscal_tax_fact','id',fiscal_fact.id,
      'fiscal_year_start_year',fiscal_fact.fiscal_year_start_year,'prior_fiscal_year_turnover',fiscal_fact.prior_fiscal_year_turnover::text,
      'gst_tds_notified_deductor',fiscal_fact.gst_tds_notified_deductor,'evidence_attachment_id',fiscal_evidence.id,
      'evidence_sha256',pg_catalog.encode(fiscal_evidence.sha256,'hex')),
    pg_catalog.jsonb_build_object('resource_type','supplier_prepayment_role','id',prepayment.id,'row_version',prepayment.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_account','id',bank.id,'row_version',bank.row_version),
    pg_catalog.jsonb_build_object('resource_type','settlement_account','id',settlement.id,'row_version',settlement.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_disbursement_collision','bank_account_id',bank.id,
      'external_reference',reference,'payment_date',payment_date,'amount',gross::text,'candidate_count',duplicate_count));
  RETURN pg_catalog.jsonb_build_object('branch_id',branch.id,'payment_id',payment_id,'payment_date',payment_date,
    'supplier_account_id',supplier.id,'supplier_party_id',party.id,'purchase_order_id',purchase_order.id,
    'bank_account_id',bank.id,'settlement_account_id',settlement.id,'supplier_prepayment_account_id',prepayment.id,
    'payment_method',method,'external_reference',reference,'gross_amount',gross::text,'cash_amount',gross::text,
    'withheld_amount','0.00','currency_code','INR','allocations',resolved_allocations,
    'legal_scope',pg_catalog.jsonb_build_object('country_code','IN','currency_code','INR','advance_subject','goods_net_value',
      'gst_on_goods_advance','not_payable_notification_66_2017','income_tax_withholding','not_applicable_verified_prior_fy_turnover_at_or_below_inr_10_crore',
      'gst_tds','not_applicable_verified_notified_deductor_false','supported_payment_methods',pg_catalog.jsonb_build_array('bank_transfer','upi'),
      'allocation_cardinality','exactly_one_purchase_order_product_line','withholding_application_and_reversal','unavailable'),
    'source_versions',source_versions);
END
$function$;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_supplier_payment_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE branch_id uuid:=NULLIF(request_document->>'branch_id','')::uuid;
        payment_date date:=NULLIF(request_document->>'payment_date','')::date;
        supplier_id uuid:=NULLIF(request_document->>'supplier_account_id','')::uuid;
        bank_id uuid:=NULLIF(request_document->>'bank_account_id','')::uuid;
        settlement_id uuid:=NULLIF(request_document->>'settlement_account_id','')::uuid;
        gross numeric(20,2):=NULLIF(request_document->>'gross_amount','')::numeric;
        method text:=request_document->>'payment_method';
        reference text:=upper(NULLIF(pg_catalog.btrim(request_document->>'external_reference'),''));
        branch core.branches%ROWTYPE; supplier parties.supplier_accounts%ROWTYPE; party parties.parties%ROWTYPE;
        party_evidence core.attachments%ROWTYPE; bank finance.bank_accounts%ROWTYPE; settlement finance.accounts%ROWTYPE;
        payable finance.accounts%ROWTYPE; payment_fiscal_fact tax.organization_fiscal_tax_facts%ROWTYPE;
        payment_fiscal_evidence core.attachments%ROWTYPE; credit_fiscal_fact tax.organization_fiscal_tax_facts%ROWTYPE;
        credit_fiscal_evidence core.attachments%ROWTYPE; requested jsonb; item finance.open_items%ROWTYPE;
        event finance.accounting_events%ROWTYPE; invoice procurement.supplier_invoices%ROWTYPE;
        resolved_allocations jsonb:='[]'::jsonb; source_versions jsonb:='[]'::jsonb;
        prior_allocated numeric(20,2); requested_total numeric(20,2):=0; allocation_count integer;
        duplicate_count integer; allocation_state_hash text; applicable_advance_state_hash text; fiscal_year smallint;
BEGIN
  IF organization_id IS NULL OR membership_id IS NULL OR auth_user_id IS NULL OR application_user_id IS NULL
     OR grant_id IS NULL OR payment_id IS NULL OR branch_id IS NULL OR payment_date IS NULL OR supplier_id IS NULL
     OR bank_id IS NULL OR settlement_id IS NULL OR gross<=0 OR method NOT IN ('bank_transfer','upi')
     OR reference IS NULL OR pg_catalog.length(reference)>256
     OR pg_catalog.jsonb_typeof(request_document->'allocations')<>'array'
     OR pg_catalog.jsonb_array_length(request_document->'allocations') NOT BETWEEN 1 AND 500 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier-payment INR bank pilot input is incomplete'; END IF;
  PERFORM 1 FROM core.memberships membership JOIN core.users user_row ON user_row.id=membership.user_id
    JOIN core.organizations organization_row ON organization_row.id=membership.org_id
    JOIN automation.agent_grants grant_row ON grant_row.org_id=membership.org_id AND grant_row.subject_membership_id=membership.id
    JOIN automation.agent_grant_capabilities capability ON capability.org_id=grant_row.org_id AND capability.agent_grant_id=grant_row.id
   WHERE membership.org_id=organization_id AND membership.id=membership_id AND membership.user_id=application_user_id
     AND membership.status='active' AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
     AND organization_row.status='active' AND organization_row.country_code='IN' AND organization_row.base_currency='INR'
     AND grant_row.id=grant_id AND grant_row.client_id=caller_client_id AND grant_row.status='active'
     AND grant_row.expires_at>pg_catalog.transaction_timestamp() AND (grant_row.branch_id IS NULL OR grant_row.branch_id=branch_id)
     AND capability.capability_code='finance.supplier_payment.prepare' AND capability.operation_mode='write' AND capability.status='active';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-payment delegated authority is inactive'; END IF;
  PERFORM erp_security.activate_context(auth_user_id,organization_id);
  IF erp_security.current_membership_id() IS DISTINCT FROM membership_id OR erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.payment.manage',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.payment.allocate',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.journal.post',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('automation.command.execute',branch_id) IS DISTINCT FROM true THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-payment verified context or cross-domain permission is inactive'; END IF;
  IF payment_date>"erp_core_commands"."current_organization_business_date"() THEN
    RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='supplier payment date cannot be in the future'; END IF;
  IF (SELECT count(DISTINCT value->>'open_item_id') FROM pg_catalog.jsonb_array_elements(request_document->'allocations'))
       <>pg_catalog.jsonb_array_length(request_document->'allocations') THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier payment requires unique payable allocations'; END IF;
  SELECT * INTO STRICT branch FROM core.branches WHERE org_id=organization_id AND id=branch_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT supplier FROM parties.supplier_accounts WHERE org_id=organization_id AND id=supplier_id AND status='active' FOR SHARE;
  SELECT * INTO STRICT party FROM parties.parties WHERE org_id=organization_id AND id=supplier.party_id AND status='active'
    AND tax_residency_status='resident' AND pan IS NOT NULL AND pan_verification_status='verified'
    AND tax_profile_verified_at IS NOT NULL AND tax_profile_verified_at<=pg_catalog.transaction_timestamp()
    AND tax_profile_evidence_attachment_id IS NOT NULL FOR SHARE;
  SELECT * INTO STRICT party_evidence FROM core.attachments WHERE org_id=organization_id
    AND id=party.tax_profile_evidence_attachment_id AND status IN ('verified','retained')
    AND verified_at IS NOT NULL AND verified_at<=pg_catalog.transaction_timestamp() FOR SHARE;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',payment_date)>=4 THEN pg_catalog.date_part('year',payment_date)::smallint
                    ELSE (pg_catalog.date_part('year',payment_date)-1)::smallint END;
  SELECT * INTO STRICT payment_fiscal_fact FROM tax.organization_fiscal_tax_facts WHERE org_id=organization_id
    AND fiscal_year_start_year=fiscal_year AND status='active' AND payment_date BETWEEN effective_from AND effective_to
    AND prior_fiscal_year_turnover<=100000000 AND gst_tds_notified_deductor=false FOR SHARE;
  SELECT * INTO STRICT payment_fiscal_evidence FROM core.attachments WHERE org_id=organization_id
    AND id=payment_fiscal_fact.evidence_attachment_id AND status IN ('verified','retained') AND verified_at IS NOT NULL
    AND verified_at<=pg_catalog.transaction_timestamp() FOR SHARE;
  SELECT * INTO STRICT payable FROM finance.accounts WHERE org_id=organization_id
    AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'accounts_payable','liability','INR',true)
    AND status='active' AND account_type='liability' AND currency_code='INR' AND allows_party_posting FOR SHARE;
  IF supplier.default_payable_account_id IS DISTINCT FROM payable.id THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier default payable does not match canonical branch account role'; END IF;
  SELECT * INTO STRICT bank FROM finance.bank_accounts WHERE org_id=organization_id AND id=bank_id
    AND status='active' AND currency_code='INR' FOR SHARE;
  SELECT * INTO STRICT settlement FROM finance.accounts WHERE org_id=organization_id AND id=settlement_id
    AND id=bank.account_id AND status='active' AND account_type='asset' AND currency_code='INR'
    AND allows_bank_reconciliation FOR SHARE;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    organization_id::text||':supplier-payment-reference:'||bank.id::text||':'||reference,672011));
  SELECT count(*) INTO duplicate_count FROM finance.payments existing WHERE existing.org_id=organization_id
    AND existing.bank_account_id=bank.id AND upper(pg_catalog.btrim(existing.external_reference))=reference
    AND existing.reversal_of_payment_id IS NULL AND existing.id<>payment_id;
  IF duplicate_count<>0 THEN
    RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier payment bank reference was already consumed'; END IF;
  PERFORM 1 FROM finance.open_items candidate
   JOIN pg_catalog.jsonb_array_elements(request_document->'allocations') payload(value)
     ON candidate.id=(payload.value->>'open_item_id')::uuid
   WHERE candidate.org_id=organization_id ORDER BY candidate.id FOR UPDATE OF candidate;
  FOR requested IN SELECT value FROM pg_catalog.jsonb_array_elements(request_document->'allocations') LOOP
    IF NULLIF(requested->>'allocation_id','')::uuid IS NULL OR NULLIF(requested->>'open_item_id','')::uuid IS NULL
       OR NULLIF(requested->>'amount','')::numeric<=0 THEN
      RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier payment allocation identity and positive amount are required'; END IF;
    SELECT * INTO STRICT item FROM finance.open_items WHERE org_id=organization_id
      AND id=(requested->>'open_item_id')::uuid AND item_side='payable' AND party_id=party.id
      AND currency_code='INR' AND status='open' AND document_date<=payment_date FOR UPDATE;
    SELECT * INTO STRICT event FROM finance.accounting_events WHERE org_id=organization_id
      AND id=item.accounting_event_id AND event_type='supplier_invoice' AND supplier_invoice_id IS NOT NULL FOR SHARE;
    SELECT * INTO STRICT invoice FROM procurement.supplier_invoices WHERE org_id=organization_id AND id=event.supplier_invoice_id
      AND branch_id=branch.id AND supplier_account_id=supplier.id AND currency_code='INR' AND status='posted'
      AND supply_type IN ('intra_state','inter_state') AND zero_rated_payment_mode='not_applicable'
      AND tax_charge_mechanism='normal' FOR SHARE;
    fiscal_year:=CASE WHEN pg_catalog.date_part('month',item.document_date)>=4
                      THEN pg_catalog.date_part('year',item.document_date)::smallint
                      ELSE (pg_catalog.date_part('year',item.document_date)-1)::smallint END;
    SELECT * INTO STRICT credit_fiscal_fact FROM tax.organization_fiscal_tax_facts WHERE org_id=organization_id
      AND fiscal_year_start_year=fiscal_year AND status='active' AND item.document_date BETWEEN effective_from AND effective_to
      AND prior_fiscal_year_turnover<=100000000 AND gst_tds_notified_deductor=false FOR SHARE;
    SELECT * INTO STRICT credit_fiscal_evidence FROM core.attachments WHERE org_id=organization_id
      AND id=credit_fiscal_fact.evidence_attachment_id AND status IN ('verified','retained') AND verified_at IS NOT NULL
      AND verified_at<=pg_catalog.transaction_timestamp() FOR SHARE;
    IF (SELECT count(*) FROM procurement.supplier_invoice_lines invoice_line WHERE invoice_line.org_id=organization_id
         AND invoice_line.supplier_invoice_id=invoice.id AND invoice_line.line_kind='product'
         AND invoice_line.withholding_nature_code='purchase_of_goods')=0
       OR EXISTS (SELECT 1 FROM procurement.supplier_invoice_lines invoice_line WHERE invoice_line.org_id=organization_id
         AND invoice_line.supplier_invoice_id=invoice.id
         AND (invoice_line.line_kind<>'product' OR invoice_line.withholding_nature_code IS DISTINCT FROM 'purchase_of_goods')) THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='supplier payment pilot supports only purchase-of-goods product invoices without charge withholding ambiguity'; END IF;
    PERFORM 1 FROM procurement.purchase_order_advance_allocations advance
     WHERE advance.org_id=organization_id AND EXISTS (
       SELECT 1 FROM procurement.supplier_invoice_lines invoice_line
       JOIN procurement.supplier_invoice_receipt_allocations receipt_allocation
         ON receipt_allocation.org_id=invoice_line.org_id AND receipt_allocation.supplier_invoice_line_id=invoice_line.id
       JOIN procurement.goods_receipt_lines receipt_line
         ON receipt_line.org_id=receipt_allocation.org_id AND receipt_line.id=receipt_allocation.goods_receipt_line_id
        AND receipt_line.purchase_order_line_id=advance.purchase_order_line_id
       WHERE invoice_line.org_id=organization_id AND invoice_line.supplier_invoice_id=invoice.id)
     ORDER BY advance.id FOR UPDATE OF advance;
    SELECT pg_catalog.encode(extensions.digest(pg_catalog.convert_to(coalesce(pg_catalog.jsonb_agg(
        pg_catalog.jsonb_build_object('id',advance.id,'purchase_order_line_id',advance.purchase_order_line_id,
          'gross_advance_amount',advance.gross_advance_amount::text,'status',advance.status,
          'reversal_of_allocation_id',advance.reversal_of_allocation_id,
          'applied',EXISTS (SELECT 1 FROM finance.accounting_events application
            WHERE application.org_id=advance.org_id AND application.purchase_order_advance_allocation_id=advance.id))
        ORDER BY advance.id),'[]'::jsonb)::text,'UTF8'),'sha256'),'hex') INTO applicable_advance_state_hash
      FROM procurement.purchase_order_advance_allocations advance
     WHERE advance.org_id=organization_id AND EXISTS (
       SELECT 1 FROM procurement.supplier_invoice_lines invoice_line
       JOIN procurement.supplier_invoice_receipt_allocations receipt_allocation
         ON receipt_allocation.org_id=invoice_line.org_id AND receipt_allocation.supplier_invoice_line_id=invoice_line.id
       JOIN procurement.goods_receipt_lines receipt_line
         ON receipt_line.org_id=receipt_allocation.org_id AND receipt_line.id=receipt_allocation.goods_receipt_line_id
        AND receipt_line.purchase_order_line_id=advance.purchase_order_line_id
       WHERE invoice_line.org_id=organization_id AND invoice_line.supplier_invoice_id=invoice.id);
    IF EXISTS (SELECT 1 FROM procurement.purchase_order_advance_allocations advance
       WHERE advance.org_id=organization_id AND advance.status='posted' AND advance.reversal_of_allocation_id IS NULL
         AND NOT EXISTS (SELECT 1 FROM procurement.purchase_order_advance_allocations reversal
           WHERE reversal.org_id=advance.org_id AND reversal.reversal_of_allocation_id=advance.id AND reversal.status='reversed')
         AND NOT EXISTS (SELECT 1 FROM finance.accounting_events application
           WHERE application.org_id=advance.org_id AND application.purchase_order_advance_allocation_id=advance.id)
         AND EXISTS (SELECT 1 FROM procurement.supplier_invoice_lines invoice_line
           JOIN procurement.supplier_invoice_receipt_allocations receipt_allocation
             ON receipt_allocation.org_id=invoice_line.org_id AND receipt_allocation.supplier_invoice_line_id=invoice_line.id
           JOIN procurement.goods_receipt_lines receipt_line
             ON receipt_line.org_id=receipt_allocation.org_id AND receipt_line.id=receipt_allocation.goods_receipt_line_id
            AND receipt_line.purchase_order_line_id=advance.purchase_order_line_id
          WHERE invoice_line.org_id=organization_id AND invoice_line.supplier_invoice_id=invoice.id)) THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='supplier payment pilot cannot leave an applicable supplier advance unapplied'; END IF;
    PERFORM 1 FROM finance.allocations prior WHERE prior.org_id=organization_id AND prior.open_item_id=item.id
      AND prior.payment_id IS DISTINCT FROM payment_id ORDER BY prior.id FOR UPDATE OF prior;
    IF EXISTS (SELECT 1 FROM finance.allocations prior WHERE prior.org_id=organization_id AND prior.open_item_id=item.id
         AND prior.payment_id IS DISTINCT FROM payment_id AND prior.status='posted' AND prior.reversal_of_allocation_id IS NULL
         AND NOT EXISTS (SELECT 1 FROM finance.allocations reversal WHERE reversal.org_id=prior.org_id
           AND reversal.reversal_of_allocation_id=prior.id AND reversal.status='reversed')
         AND prior.payment_id IS NULL) THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='supplier payment pilot cannot mix advance, withholding, or adjustment allocations'; END IF;
    SELECT coalesce(sum(prior.amount),0),count(*) INTO prior_allocated,allocation_count FROM finance.allocations prior
     WHERE prior.org_id=organization_id AND prior.open_item_id=item.id AND prior.payment_id IS NOT NULL
       AND prior.payment_id<>payment_id AND prior.status='posted' AND prior.reversal_of_allocation_id IS NULL
       AND NOT EXISTS (SELECT 1 FROM finance.allocations reversal WHERE reversal.org_id=prior.org_id
         AND reversal.reversal_of_allocation_id=prior.id AND reversal.status='reversed');
    SELECT pg_catalog.encode(extensions.digest(pg_catalog.convert_to(coalesce(pg_catalog.jsonb_agg(
        pg_catalog.jsonb_build_object('id',prior.id,'payment_id',prior.payment_id,'withholding_id',prior.withholding_id,
          'adjustment_note_id',prior.adjustment_note_id,'purchase_order_advance_allocation_id',prior.purchase_order_advance_allocation_id,
          'amount',prior.amount::text,'status',prior.status,'reversal_of_allocation_id',prior.reversal_of_allocation_id)
        ORDER BY prior.id),'[]'::jsonb)::text,'UTF8'),'sha256'),'hex') INTO allocation_state_hash
      FROM finance.allocations prior WHERE prior.org_id=organization_id AND prior.open_item_id=item.id
        AND prior.payment_id IS DISTINCT FROM payment_id;
    IF prior_allocated+(requested->>'amount')::numeric>item.principal_amount THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier payment allocation exceeds live payable balance'; END IF;
    requested_total:=requested_total+(requested->>'amount')::numeric;
    resolved_allocations:=resolved_allocations||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'allocation_id',requested->>'allocation_id','open_item_id',item.id,'supplier_invoice_id',invoice.id,
      'document_number',item.document_number,'principal_amount',item.principal_amount::text,
      'prior_cash_allocated_amount',prior_allocated::text,'amount',(requested->>'amount')::numeric::text,
      'residual_after',(item.principal_amount-prior_allocated-(requested->>'amount')::numeric)::text));
    source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'resource_type','payable_allocation_state','id',item.id,'supplier_invoice_id',invoice.id,'invoice_row_version',invoice.row_version,
      'principal_amount',item.principal_amount::text,'status',item.status,'allocation_count',allocation_count,
      'active_cash_allocated_amount',prior_allocated::text,'allocation_state_hash',allocation_state_hash,
      'applicable_advance_state_hash',applicable_advance_state_hash),
      pg_catalog.jsonb_build_object('resource_type','invoice_credit_fiscal_tax_fact','id',credit_fiscal_fact.id,
        'supplier_invoice_id',invoice.id,'credit_date',item.document_date,
        'fiscal_year_start_year',credit_fiscal_fact.fiscal_year_start_year,
        'prior_fiscal_year_turnover',credit_fiscal_fact.prior_fiscal_year_turnover::text,
        'gst_tds_notified_deductor',credit_fiscal_fact.gst_tds_notified_deductor,
        'evidence_attachment_id',credit_fiscal_evidence.id,
        'evidence_sha256',pg_catalog.encode(credit_fiscal_evidence.sha256,'hex')));
  END LOOP;
  IF requested_total<>gross THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier payment allocations must exactly equal gross liability and bank cash'; END IF;
  source_versions:=pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_object('resource_type','branch','id',branch.id,'row_version',branch.row_version),
    pg_catalog.jsonb_build_object('resource_type','supplier_account','id',supplier.id,'row_version',supplier.row_version),
    pg_catalog.jsonb_build_object('resource_type','supplier_party_tax_profile','id',party.id,'row_version',party.row_version,
      'pan_verification_status',party.pan_verification_status,'tax_residency_status',party.tax_residency_status,
      'evidence_attachment_id',party_evidence.id,'evidence_sha256',pg_catalog.encode(party_evidence.sha256,'hex')),
    pg_catalog.jsonb_build_object('resource_type','payment_date_fiscal_tax_fact','id',payment_fiscal_fact.id,
      'payment_date',payment_date,'fiscal_year_start_year',payment_fiscal_fact.fiscal_year_start_year,
      'prior_fiscal_year_turnover',payment_fiscal_fact.prior_fiscal_year_turnover::text,
      'gst_tds_notified_deductor',payment_fiscal_fact.gst_tds_notified_deductor,
      'evidence_attachment_id',payment_fiscal_evidence.id,
      'evidence_sha256',pg_catalog.encode(payment_fiscal_evidence.sha256,'hex')),
    pg_catalog.jsonb_build_object('resource_type','accounts_payable_role','id',payable.id,'row_version',payable.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_account','id',bank.id,'row_version',bank.row_version),
    pg_catalog.jsonb_build_object('resource_type','settlement_account','id',settlement.id,'row_version',settlement.row_version),
    pg_catalog.jsonb_build_object('resource_type','bank_disbursement_collision','bank_account_id',bank.id,
      'external_reference',reference,'original_payment_candidate_count',duplicate_count))||source_versions;
  RETURN pg_catalog.jsonb_build_object('branch_id',branch.id,'payment_id',payment_id,'payment_date',payment_date,
    'supplier_account_id',supplier.id,'supplier_party_id',party.id,'bank_account_id',bank.id,
    'settlement_account_id',settlement.id,'accounts_payable_account_id',payable.id,'payment_method',method,
    'external_reference',reference,'gross_amount',gross::text,'cash_amount',gross::text,'withheld_amount','0.00',
    'currency_code','INR','allocations',resolved_allocations,
    'legal_scope',pg_catalog.jsonb_build_object('country_code','IN','currency_code','INR','settlement','posted_supplier_invoice_payables_only',
      'supported_payment_methods',pg_catalog.jsonb_build_array('bank_transfer','upi'),
      'income_tax_withholding','not_applicable_verified_prior_fy_turnover_at_or_below_inr_10_crore',
      'gst_tds','not_applicable_verified_notified_deductor_false',
      'gross_liability_equals_bank_cash',true,'advance_withholding_adjustment_or_supplier_credit_netting','unavailable',
      'payment_reversal','unavailable_operator_action'),
    'source_versions',source_versions);
END
$function$;
RESET ROLE;
