-- Generated by backend/scripts/generate_business_gap_security_closure_migration.py.
-- Alembic owns the transaction; this file must not be applied directly.
SET LOCAL ROLE erp_migration_owner;
CREATE OR REPLACE FUNCTION "erp_commercial_commands"."resolve_commercial_reversal_prepare"(organization_id uuid, reversal_kind text, original_resource_id uuid, expected_row_version bigint, reversal_date date, reason text, amendment_evidence_attachment_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE note finance.adjustment_notes%ROWTYPE; source_version bigint; branch_id uuid;
        tax_document tax.documents%ROWTYPE; reported_count bigint; inventory_document_id uuid;
BEGIN
  IF organization_id IS DISTINCT FROM erp_security.current_org_id()
     OR reversal_kind NOT IN ('sales_return','purchase_return','adjustment_note')
     OR reason IS NULL OR pg_catalog.btrim(reason)='' OR reversal_date IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='commercial reversal prepare context is invalid'; END IF;
  IF reversal_date>"erp_core_commands"."current_organization_business_date"() THEN
    RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='commercial reversal date cannot be in the future'; END IF;
  IF reversal_kind='sales_return' THEN
    SELECT row_version,branch_id INTO STRICT source_version,branch_id FROM sales.returns
     WHERE org_id=organization_id AND id=original_resource_id AND status='posted' FOR UPDATE;
    SELECT * INTO STRICT note FROM finance.adjustment_notes
     WHERE org_id=organization_id AND sales_return_id=original_resource_id AND status='posted' FOR SHARE;
    SELECT id INTO STRICT inventory_document_id FROM inventory.inventory_documents
     WHERE org_id=organization_id AND sales_return_id=original_resource_id
       AND document_type='sales_return_receipt' AND status='posted' FOR SHARE;
  ELSIF reversal_kind='purchase_return' THEN
    SELECT row_version,branch_id INTO STRICT source_version,branch_id FROM procurement.purchase_returns
     WHERE org_id=organization_id AND id=original_resource_id AND status='posted' FOR UPDATE;
    SELECT * INTO STRICT note FROM finance.adjustment_notes
     WHERE org_id=organization_id AND purchase_return_id=original_resource_id AND status='posted' FOR SHARE;
    SELECT id INTO STRICT inventory_document_id FROM inventory.inventory_documents
     WHERE org_id=organization_id AND purchase_return_id=original_resource_id
       AND document_type='purchase_return_issue' AND status='posted' FOR SHARE;
  ELSE
    SELECT * INTO STRICT note FROM finance.adjustment_notes
     WHERE org_id=organization_id AND id=original_resource_id AND status='posted'
       AND sales_return_id IS NULL AND purchase_return_id IS NULL FOR UPDATE;
    source_version:=note.row_version;
    SELECT coalesce(invoice.branch_id,supplier.branch_id) INTO STRICT branch_id
      FROM finance.adjustment_notes source
      LEFT JOIN sales.invoices invoice ON invoice.org_id=source.org_id AND invoice.id=source.sales_invoice_id
      LEFT JOIN procurement.supplier_invoices supplier ON supplier.org_id=source.org_id AND supplier.id=source.supplier_invoice_id
     WHERE source.org_id=organization_id AND source.id=note.id;
  END IF;
  IF source_version IS DISTINCT FROM expected_row_version OR reversal_date<note.note_date
     OR note.reversal_of_adjustment_note_id IS NOT NULL
     OR EXISTS(SELECT 1 FROM finance.adjustment_notes reversal
       WHERE reversal.org_id=organization_id AND reversal.reversal_of_adjustment_note_id=note.id) THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='posted commercial source changed or was already reversed'; END IF;
  IF erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.adjustment_note.manage',branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('finance.journal.post',branch_id) IS DISTINCT FROM true THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='commercial reversal branch permission denied'; END IF;
  SELECT * INTO tax_document FROM tax.documents
   WHERE org_id=organization_id AND adjustment_note_id=note.id FOR SHARE;
  SELECT count(*) INTO reported_count FROM tax.return_documents membership
   WHERE membership.org_id=organization_id AND membership.tax_document_id=tax_document.id;
  IF reported_count>0 THEN
    PERFORM 1 FROM core.attachments evidence WHERE evidence.org_id=organization_id
      AND evidence.id=amendment_evidence_attachment_id
      AND evidence.evidence_kind='statutory_amendment_or_counter_note'
      AND evidence.status IN ('verified','retained') AND evidence.verified_at IS NOT NULL FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='reported return or note requires explicit verified amendment or counter-note evidence'; END IF;
  ELSIF amendment_evidence_attachment_id IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unreported return or note must use direct counter-document reversal without amendment evidence';
  END IF;
  IF EXISTS(SELECT 1 FROM finance.open_items residual
      WHERE residual.org_id=organization_id
        AND residual.accounting_event_id=(SELECT event.id FROM finance.accounting_events event
          WHERE event.org_id=organization_id AND event.adjustment_note_id=note.id)
        AND EXISTS(SELECT 1 FROM finance.allocations allocation WHERE allocation.org_id=organization_id
          AND (allocation.source_open_item_id=residual.id OR allocation.open_item_id=residual.id)
          AND allocation.status='posted' AND NOT EXISTS(SELECT 1 FROM finance.allocations reversal
            WHERE reversal.org_id=allocation.org_id AND reversal.reversal_of_allocation_id=allocation.id))) THEN
    RAISE EXCEPTION USING ERRCODE='55000', MESSAGE='commercial reversal is blocked because residual credit or debit was consumed'; END IF;
  RETURN pg_catalog.jsonb_build_object('reversal_kind',reversal_kind,'original_resource_id',original_resource_id,
    'original_adjustment_note_id',note.id,'expected_row_version',source_version,'branch_id',branch_id,
    'inventory_document_id',inventory_document_id,'original_tax_document_id',tax_document.id,
    'counterparty_payable_amount',note.counterparty_payable_amount,
    'reported_return_membership_count',reported_count,'reversal_date',reversal_date,'reason',reason,
    'amendment_evidence_attachment_id',amendment_evidence_attachment_id,
    'source_versions',pg_catalog.jsonb_build_array(
      pg_catalog.jsonb_build_object('resource_type',reversal_kind,'id',original_resource_id,'row_version',source_version),
      pg_catalog.jsonb_build_object('resource_type','adjustment_note','id',note.id,'row_version',note.row_version)),
    'legal_scope',pg_catalog.jsonb_build_object('correction_kind','compensating_counter_document',
      'reported',reported_count>0,'deletion',false,'requires_exact_stock_lineage',reversal_kind<>'adjustment_note'));
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_commercial_commands"."execute_approved_commercial_reversal"(organization_id uuid, command_request_id uuid)
RETURNS bytea
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE command automation.command_requests%ROWTYPE; grant_row automation.agent_grants%ROWTYPE;
        capability automation.agent_grant_capabilities%ROWTYPE;
        request_document jsonb; actor uuid:=erp_security.current_membership_id();
        approval_count bigint; reversal_kind text; fiscal_year integer; note_sequence uuid; journal_sequence uuid;
        inventory_sequence uuid; note_number text; journal_number text; inventory_number text; result_id uuid;
        response_document jsonb; response_body bytea;
BEGIN
  IF organization_id IS DISTINCT FROM erp_security.current_org_id()
     OR NULLIF(pg_catalog.current_setting('app.command_request_id',true),'')::uuid IS DISTINCT FROM command_request_id
     OR actor IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='commercial reversal execute context is invalid'; END IF;
  SELECT * INTO STRICT command FROM automation.command_requests
   WHERE org_id=organization_id AND id=command_request_id FOR UPDATE;
  IF command.status='succeeded' THEN RETURN command.response_bytes; END IF;
  SELECT * INTO grant_row FROM automation.agent_grants
   WHERE org_id=organization_id AND id=command.agent_grant_id FOR UPDATE;
  SELECT * INTO capability FROM automation.agent_grant_capabilities
   WHERE org_id=organization_id AND agent_grant_id=command.agent_grant_id
     AND capability_code=command.capability_code FOR SHARE;
  IF grant_row.id IS NULL OR capability.agent_grant_id IS NULL
     OR grant_row.status<>'active' OR grant_row.expires_at<=pg_catalog.transaction_timestamp()
     OR grant_row.subject_membership_id IS DISTINCT FROM actor
     OR capability.status<>'active'
     OR capability.operation_mode IS DISTINCT FROM command.operation_mode
     OR capability.risk_class IS DISTINCT FROM command.risk_class
     OR capability.approval_policy IS DISTINCT FROM command.approval_policy
     OR command.branch_id IS NULL
     OR erp_security.can_access_branch(command.branch_id) IS DISTINCT FROM true
     OR erp_security.has_permission('automation.command.execute',command.branch_id) IS DISTINCT FROM true
     OR (grant_row.branch_id IS NOT NULL AND command.branch_id IS DISTINCT FROM grant_row.branch_id) THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='commercial reversal grant or exact capability consent changed before execution'; END IF;
  IF command.status NOT IN ('prepared','pending_approval','approved')
     OR command.requested_by_membership_id IS DISTINCT FROM actor
     OR command.expires_at<=pg_catalog.transaction_timestamp()
     OR command.request_hash IS DISTINCT FROM extensions.digest(command.request_bytes,'sha256')
     OR command.preview_hash IS DISTINCT FROM extensions.digest(command.preview_bytes,'sha256') THEN
    RAISE EXCEPTION USING ERRCODE='55000', MESSAGE='commercial reversal command is not exactly executable'; END IF;
  SELECT count(*) INTO approval_count FROM automation.command_approvals approval
   WHERE approval.org_id=organization_id AND approval.command_request_id=command.id
     AND approval.decision='approved' AND approval.preview_hash=command.preview_hash
     AND approval.aggregate_version_hash=command.aggregate_version_hash
     AND approval.valid_until_at>pg_catalog.transaction_timestamp()
     AND approval.approver_membership_id<>command.requested_by_membership_id;
  IF approval_count<1 THEN RAISE EXCEPTION USING ERRCODE='55000', MESSAGE='commercial reversal lacks independent immutable approval'; END IF;
  INSERT INTO erp_automation_commands.execution_scopes
    VALUES(pg_catalog.pg_backend_pid(),pg_catalog.txid_current(),organization_id,command_request_id);
  IF command.status<>'approved' THEN
    UPDATE automation.command_requests SET status='approved',row_version=row_version+1
     WHERE org_id=organization_id AND id=command.id AND status IN ('prepared','pending_approval');
  END IF;
  UPDATE automation.command_requests SET status='executing',execution_started_at=pg_catalog.transaction_timestamp(),
    row_version=row_version+1 WHERE org_id=organization_id AND id=command.id AND status='approved';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='commercial reversal begin boundary lost ownership'; END IF;
  request_document:=pg_catalog.convert_from(command.request_bytes,'UTF8')::jsonb;
  reversal_kind:=CASE command.capability_code WHEN 'sales.return.reversal.prepare' THEN 'sales_return'
    WHEN 'procurement.purchase_return.reversal.prepare' THEN 'purchase_return'
    WHEN 'finance.adjustment_note.reversal.prepare' THEN 'adjustment_note' ELSE NULL END;
  IF reversal_kind IS NULL THEN RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='command is not a typed commercial reversal'; END IF;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',(request_document->>'reversal_date')::date)>=4
    THEN pg_catalog.date_part('year',(request_document->>'reversal_date')::date)::integer
    ELSE pg_catalog.date_part('year',(request_document->>'reversal_date')::date)::integer-1 END;
  SELECT id INTO STRICT note_sequence FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=command.branch_id AND document_type='adjustment_note'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=command.branch_id AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  note_number:=erp_core_commands.allocate_document_number(organization_id,note_sequence,
    extensions.digest(command.idempotency_key_hash||pg_catalog.convert_to(':reversal-note','UTF8'),'sha256'),command.expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence,
    extensions.digest(command.idempotency_key_hash||pg_catalog.convert_to(':reversal-journal','UTF8'),'sha256'),command.expires_at);
  IF reversal_kind<>'adjustment_note' THEN
    SELECT id INTO STRICT inventory_sequence FROM core.document_sequences WHERE org_id=organization_id
      AND branch_id=command.branch_id AND document_type='inventory_reversal'
      AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
    inventory_number:=erp_core_commands.allocate_document_number(organization_id,inventory_sequence,
      extensions.digest(command.idempotency_key_hash||pg_catalog.convert_to(':inventory-reversal','UTF8'),'sha256'),command.expires_at);
  END IF;
  IF reversal_kind='sales_return' THEN
    result_id:=erp_commercial_commands.post_sales_return_reversal(organization_id,
      (request_document->>'original_resource_id')::uuid,(request_document->>'expected_row_version')::bigint,
      command.target_resource_id,note_number,(request_document->>'reversal_inventory_document_id')::uuid,inventory_number,
      (request_document->>'reversal_journal_id')::uuid,journal_number,(request_document->>'reversal_event_id')::uuid,
      NULLIF(request_document->>'reversal_tax_document_id','')::uuid,(request_document->>'reversal_date')::date,
      request_document->>'reason',NULLIF(request_document->>'amendment_evidence_attachment_id','')::uuid,
      command.idempotency_key_hash,command.request_hash,command.expires_at);
  ELSIF reversal_kind='purchase_return' THEN
    result_id:=erp_commercial_commands.post_purchase_return_reversal(organization_id,
      (request_document->>'original_resource_id')::uuid,(request_document->>'expected_row_version')::bigint,
      command.target_resource_id,note_number,(request_document->>'reversal_inventory_document_id')::uuid,inventory_number,
      (request_document->>'reversal_journal_id')::uuid,journal_number,(request_document->>'reversal_event_id')::uuid,
      NULLIF(request_document->>'reversal_tax_document_id','')::uuid,(request_document->>'reversal_date')::date,
      request_document->>'reason',NULLIF(request_document->>'amendment_evidence_attachment_id','')::uuid,
      command.idempotency_key_hash,command.request_hash,command.expires_at);
  ELSE
    result_id:=erp_commercial_commands.post_adjustment_note_reversal(organization_id,
      (request_document->>'original_resource_id')::uuid,(request_document->>'expected_row_version')::bigint,
      command.target_resource_id,note_number,NULL,NULL,(request_document->>'reversal_journal_id')::uuid,journal_number,
      (request_document->>'reversal_event_id')::uuid,NULLIF(request_document->>'reversal_tax_document_id','')::uuid,
      (request_document->>'reversal_date')::date,request_document->>'reason',
      NULLIF(request_document->>'amendment_evidence_attachment_id','')::uuid,
      command.idempotency_key_hash,command.request_hash,command.expires_at);
  END IF;
  response_document:=pg_catalog.jsonb_build_object('command_request_id',command.id,'operation',command.operation,
    'resource_id',result_id,'resource_type','adjustment_note_reversal','status','succeeded');
  response_body:=pg_catalog.convert_to(response_document::text,'UTF8');
  UPDATE automation.command_requests SET status='succeeded',completed_at=pg_catalog.transaction_timestamp(),
    result_resource_type='adjustment_note_reversal',result_resource_id=result_id,response_status=200,
    response_media_type='application/vnd.aasopharma.command-result+json',response_bytes=response_body,
    response_hash=extensions.digest(response_body,'sha256'),row_version=row_version+1
   WHERE org_id=organization_id AND id=command.id AND status='executing';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='commercial reversal finish boundary lost ownership'; END IF;
  DELETE FROM erp_automation_commands.execution_scopes scope
   WHERE scope.backend_pid=pg_catalog.pg_backend_pid() AND scope.transaction_id=pg_catalog.txid_current()
     AND scope.org_id=organization_id AND scope.command_request_id=command.id;
  RETURN response_body;
END
$function$;
ALTER FUNCTION "erp_commercial_commands"."execute_approved_commercial_reversal"(uuid,uuid) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."execute_approved_commercial_reversal"(uuid,uuid) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_commercial_commands"."execute_approved_commercial_reversal"(uuid,uuid) TO "erp_app", "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_finance_commands"."apply_supplier_adjustment_credit"(organization_id uuid, adjustment_note_id uuid, source_open_item_id uuid, target_open_item_id uuid, allocation_id uuid, application_date date)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE note finance.adjustment_notes%ROWTYPE; source_item finance.open_items%ROWTYPE;
        target_item finance.open_items%ROWTYPE; actor uuid:=erp_security.current_membership_id();
        source_used numeric(20,2); target_used numeric(20,2); residual numeric(20,2);
BEGIN
    SELECT * INTO STRICT note FROM finance.adjustment_notes WHERE org_id=organization_id
      AND id=adjustment_note_id AND side='purchase' AND direction='debit' AND status='posted' FOR SHARE;
    SELECT * INTO STRICT source_item FROM finance.open_items WHERE org_id=organization_id
      AND id=source_open_item_id AND accounting_event_id IN (
        SELECT id FROM finance.accounting_events WHERE org_id=organization_id AND adjustment_note_id=note.id)
      AND item_side='receivable' AND status IN ('open','settled') FOR UPDATE;
    SELECT * INTO STRICT target_item FROM finance.open_items WHERE org_id=organization_id
      AND id=target_open_item_id AND item_side='payable' AND party_id=source_item.party_id
      AND currency_code=source_item.currency_code AND status IN ('open','settled') FOR UPDATE;
    IF note.branch_id IS DISTINCT FROM (
         SELECT invoice.branch_id FROM finance.accounting_events event
         JOIN procurement.supplier_invoices invoice ON invoice.org_id=event.org_id AND invoice.id=event.supplier_invoice_id
         WHERE event.org_id=organization_id AND event.id=target_item.accounting_event_id)
       OR source_item.currency_code<>'INR' THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier adjustment source and payable must share supplier, branch, and INR currency';
    END IF;
    IF application_date IS NULL OR application_date<note.note_date
       OR application_date>"erp_core_commands"."current_organization_business_date"() THEN
      RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='supplier adjustment application date is invalid'; END IF;
    SELECT coalesce(sum(a.amount),0) INTO source_used FROM finance.allocations a WHERE a.org_id=organization_id
      AND a.source_open_item_id=source_item.id AND a.status='posted' AND a.reversal_of_allocation_id IS NULL
      AND NOT EXISTS(SELECT 1 FROM finance.allocations r WHERE r.org_id=a.org_id AND r.reversal_of_allocation_id=a.id);
    SELECT coalesce(sum(a.amount),0) INTO target_used FROM finance.allocations a WHERE a.org_id=organization_id
      AND a.open_item_id=target_item.id AND a.status='posted' AND a.reversal_of_allocation_id IS NULL
      AND NOT EXISTS(SELECT 1 FROM finance.allocations r WHERE r.org_id=a.org_id AND r.reversal_of_allocation_id=a.id);
    residual:=source_item.principal_amount-source_used;
    IF residual<=0 OR residual>target_item.principal_amount-target_used THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier adjustment residual must be positive and fit the locked payable residual exactly';
    END IF;
    INSERT INTO finance.allocations(org_id,id,source_open_item_id,open_item_id,allocation_date,currency_code,
      amount,functional_amount,fx_rate,status,created_by_membership_id)
    VALUES(organization_id,allocation_id,source_item.id,target_item.id,application_date,'INR',residual,residual,1,'posted',actor);
    PERFORM "erp_finance_commands"."synchronize_open_item_status"(organization_id,source_item.id);
    PERFORM "erp_finance_commands"."synchronize_open_item_status"(organization_id,target_item.id);
    RETURN residual;
END
$function$;
CREATE OR REPLACE FUNCTION "erp_automation_commands"."find_exact_prepare_replay"(organization_id uuid, grant_id uuid, capability_name varchar, target_id uuid, key_hash bytea, request_bytes bytea, preview_bytes bytea)
RETURNS automation.command_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE existing automation.command_requests%ROWTYPE;
BEGIN
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
      organization_id::text||grant_id::text||capability_name||pg_catalog.encode(key_hash,'hex'),672044));
    SELECT * INTO existing FROM automation.command_requests
     WHERE org_id=organization_id AND agent_grant_id=grant_id
       AND capability_code=capability_name AND idempotency_key_hash=key_hash FOR SHARE;
    IF existing.id IS NOT NULL AND (
       existing.target_resource_id IS DISTINCT FROM target_id
       OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
       OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256')) THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='prepare idempotency key has different exact input';
    END IF;
    RETURN existing;
END
$function$;
ALTER FUNCTION "erp_automation_commands"."find_exact_prepare_replay"(organization_id uuid, grant_id uuid, capability_name varchar, target_id uuid, key_hash bytea, request_bytes bytea, preview_bytes bytea) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."find_exact_prepare_replay"(organization_id uuid, grant_id uuid, capability_name varchar, target_id uuid, key_hash bytea, request_bytes bytea, preview_bytes bytea) FROM PUBLIC, "erp_app", "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, command_id uuid, artifact_id uuid, request_id uuid, tax_document_id uuid, journal_id uuid, event_id uuid, open_item_id uuid, key_hash bytea, sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, calculation_input_bytes bytea, calculation_output_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb; resolved_document jsonb; current_resolution jsonb; preview_document jsonb;
        input_document jsonb; output_document jsonb; totals jsonb; resolved_line jsonb; calculated_line jsonb; allocation jsonb;
        existing automation.command_requests%ROWTYPE; aggregate_hash bytea; claim_id uuid; replay_id uuid;
        requested_total numeric(20,2);
BEGIN
    IF SESSION_USER<>'erp_calculator' OR supplier_invoice_id IS NULL OR command_id IS NULL OR artifact_id IS NULL
       OR request_id IS NULL OR tax_document_id IS NULL OR journal_id IS NULL OR event_id IS NULL OR open_item_id IS NULL
       OR pg_catalog.octet_length(key_hash)<>32 OR pg_catalog.octet_length(sequence_key_hash)<>32 THEN
      RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier-invoice persistence envelope is invalid'; END IF;
    request_document:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
    resolved_document:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
    preview_document:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
    input_document:=pg_catalog.convert_from(calculation_input_bytes,'UTF8')::jsonb;
    output_document:=pg_catalog.convert_from(calculation_output_bytes,'UTF8')::jsonb;
    existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
      'procurement.supplier_invoice.prepare',supplier_invoice_id,key_hash,request_bytes,preview_bytes);
    IF existing.id IS NOT NULL THEN
      RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
        'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
    END IF;
    current_resolution:="erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id,membership_id,auth_user_id,application_user_id,
      grant_id,caller_client_id,supplier_invoice_id,request_document);
    PERFORM pg_catalog.set_config('app.request_id',request_id::text,true);
    IF current_resolution IS DISTINCT FROM resolved_document OR output_document->>'operation'<>'procurement.supplier_invoice.post'
       OR output_document->>'resource_type'<>'supplier_invoice' OR output_document->>'resource_id'<>supplier_invoice_id::text
       OR preview_document->>'itc_eligibility_basis'<>'taxable_resale_not_blocked_under_section_17'
       OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
       OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope' THEN
      RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='supplier-invoice resolution, calculation, or ITC attestation changed'; END IF;
    totals:=output_document->'totals';
    IF (totals->>'gst_taxable_total')::numeric IS DISTINCT FROM (resolved_document->>'portal_taxable_amount')::numeric
       OR (totals->>'cgst_total')::numeric IS DISTINCT FROM (resolved_document->>'portal_cgst_amount')::numeric
       OR (totals->>'sgst_total')::numeric IS DISTINCT FROM (resolved_document->>'portal_sgst_amount')::numeric
       OR (totals->>'igst_total')::numeric IS DISTINCT FROM (resolved_document->>'portal_igst_amount')::numeric
       OR (totals->>'cess_total')::numeric IS DISTINCT FROM (resolved_document->>'portal_cess_amount')::numeric THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='calculated supplier invoice GST components differ from the unique GSTR-2B evidence'; END IF;
    SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
      AND capability_code='procurement.supplier_invoice.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
    IF FOUND THEN
      IF existing.target_resource_id IS DISTINCT FROM supplier_invoice_id
         OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
         OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256') THEN
        RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier-invoice idempotency key has different exact input'; END IF;
      RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
        'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
    END IF;
    requested_total:=(totals->>'grand_total')::numeric;
    INSERT INTO procurement.supplier_invoices(org_id,id,branch_id,supplier_account_id,buyer_tax_registration_id,
      supplier_tax_registration_id,supplier_invoice_number,supplier_invoice_date,received_date,due_date,fiscal_year,status,
      supply_type,zero_rated_payment_mode,tax_charge_mechanism,place_of_supply_state_code,calculation_ruleset_version,
      document_discount_kind,document_discount_basis,document_discount_value,supplier_legal_name_snapshot,supplier_gstin_snapshot,
      supplier_address_snapshot,buyer_legal_name_snapshot,buyer_gstin_snapshot,buyer_address_snapshot,currency_code,
      subtotal,discount_total,charges_total,net_value_total,gst_taxable_total,cgst_total,sgst_total,igst_total,cess_total,
      recipient_assessed_tax_total,rounding_policy,rounding_adjustment,grand_total)
    VALUES(organization_id,supplier_invoice_id,(resolved_document->>'branch_id')::uuid,(resolved_document->>'supplier_account_id')::uuid,
      (resolved_document->>'buyer_tax_registration_id')::uuid,(resolved_document->>'supplier_tax_registration_id')::uuid,
      request_document->>'supplier_invoice_number',(resolved_document->>'invoice_date')::date,(resolved_document->>'received_date')::date,
      (resolved_document->>'due_date')::date,CASE WHEN pg_catalog.date_part('month',(resolved_document->>'invoice_date')::date)>=4
        THEN pg_catalog.date_part('year',(resolved_document->>'invoice_date')::date)::integer
        ELSE pg_catalog.date_part('year',(resolved_document->>'invoice_date')::date)::integer-1 END,'approved',
      resolved_document->>'supply_type','not_applicable','normal',resolved_document->>'place_of_supply_state_code',output_document->>'ruleset_version',
      request_document->'document_discount'->>'document_discount_kind',request_document->'document_discount'->>'document_discount_basis',
      (request_document->'document_discount'->>'document_discount_value')::numeric,resolved_document->>'supplier_legal_name',
      resolved_document->>'supplier_gstin',resolved_document->>'supplier_address',resolved_document->>'buyer_legal_name',
      resolved_document->>'buyer_gstin',resolved_document->>'buyer_address','INR',(totals->>'subtotal')::numeric,
      (totals->>'discount_total')::numeric,(totals->>'charges_total')::numeric,(totals->>'net_value_total')::numeric,
      (totals->>'gst_taxable_total')::numeric,(totals->>'cgst_total')::numeric,(totals->>'sgst_total')::numeric,
      (totals->>'igst_total')::numeric,(totals->>'cess_total')::numeric,(totals->>'recipient_assessed_tax_total')::numeric,
      request_document->>'rounding_policy',(totals->>'rounding_adjustment')::numeric,requested_total);
    FOR resolved_line IN SELECT value FROM pg_catalog.jsonb_array_elements(resolved_document->'lines') LOOP
      SELECT value INTO STRICT calculated_line FROM pg_catalog.jsonb_array_elements(output_document->'lines') WHERE value->>'line_id'=resolved_line->>'line_id';
      INSERT INTO procurement.supplier_invoice_lines(org_id,id,supplier_invoice_id,line_number,line_kind,purchase_order_line_id,
        product_id,charge_code,uom_code,uom_conversion_factor,billed_quantity,free_quantity,base_billed_quantity,base_free_quantity,
        free_supply_tax_treatment,quoted_unit_rate,price_basis,tax_charge_mechanism,gross_amount,line_discount_kind,line_discount_basis,
        line_discount_value,document_discount_eligible,line_discount_amount,line_taxable_discount_amount,document_discount_amount,
        document_taxable_discount_amount,net_value_amount,gst_taxable_value,tax_classification_code_snapshot,tax_code_version_id,
        taxability_snapshot,inventory_cost_treatment,landed_cost_allocation_method,net_value_account_id,withholding_nature_code,itc_eligibility,cgst_rate,sgst_rate,igst_rate,cess_rate,
        cgst_amount,sgst_amount,igst_amount,cess_amount,line_total)
      VALUES(organization_id,(resolved_line->>'line_id')::uuid,supplier_invoice_id,(resolved_line->>'line_number')::integer,
        resolved_line->>'line_kind',NULLIF(resolved_line->>'purchase_order_line_id','')::uuid,
        NULLIF(resolved_line->>'product_id','')::uuid,resolved_line->>'charge_code',resolved_line->>'uom_code',
        NULLIF(resolved_line->>'multiplier','')::numeric,NULLIF(resolved_line->'input'->>'billed_quantity','')::numeric,
        NULLIF(resolved_line->'input'->>'free_quantity','')::numeric,
        CASE WHEN resolved_line->>'line_kind'='product' THEN (resolved_line->'input'->>'billed_quantity')::numeric*(resolved_line->>'multiplier')::numeric END,
        CASE WHEN resolved_line->>'line_kind'='product' THEN (resolved_line->'input'->>'free_quantity')::numeric*(resolved_line->>'multiplier')::numeric END,
        CASE WHEN resolved_line->>'line_kind'='product' THEN resolved_line->'input'->>'free_supply_tax_treatment' END,
        NULLIF(resolved_line->'input'->>'quoted_unit_rate','')::numeric,resolved_line->'input'->>'price_basis','normal',
        (calculated_line->>'gross_amount')::numeric,CASE WHEN resolved_line->>'line_kind'='product' THEN resolved_line->'input'->'line_discount'->>'line_discount_kind' ELSE 'none' END,
        CASE WHEN resolved_line->>'line_kind'='product' THEN resolved_line->'input'->'line_discount'->>'line_discount_basis' ELSE 'price_value' END,
        CASE WHEN resolved_line->>'line_kind'='product' THEN (resolved_line->'input'->'line_discount'->>'line_discount_value')::numeric ELSE 0 END,
        (resolved_line->'input'->>'document_discount_eligible')::boolean,(calculated_line->>'line_discount_amount')::numeric,
        (calculated_line->>'line_taxable_discount_amount')::numeric,(calculated_line->>'document_discount_amount')::numeric,
        (calculated_line->>'document_taxable_discount_amount')::numeric,(calculated_line->>'net_value_amount')::numeric,
        (calculated_line->>'gst_taxable_value')::numeric,CASE WHEN resolved_line->>'line_kind'='product' THEN resolved_line->>'hsn_code' ELSE resolved_line->>'sac_code' END,
        (resolved_line->>'tax_code_version_id')::uuid,'taxable',resolved_line->>'inventory_cost_treatment',
        NULLIF(resolved_line->>'landed_cost_allocation_method',''),
        (resolved_line->>'net_value_account_id')::uuid,
        CASE WHEN resolved_line->>'line_kind'='product' THEN 'purchase_of_goods' END,
        'eligible',(calculated_line->>'cgst_rate')::numeric,
        (calculated_line->>'sgst_rate')::numeric,(calculated_line->>'igst_rate')::numeric,(calculated_line->>'cess_rate')::numeric,
        (calculated_line->>'cgst_amount')::numeric,(calculated_line->>'sgst_amount')::numeric,(calculated_line->>'igst_amount')::numeric,
        (calculated_line->>'cess_amount')::numeric,(calculated_line->>'line_total')::numeric);
      IF resolved_line->>'line_kind'='product' THEN
        FOR allocation IN SELECT value FROM pg_catalog.jsonb_array_elements(resolved_line->'receipt_allocations') LOOP
          INSERT INTO procurement.supplier_invoice_receipt_allocations(org_id,id,supplier_invoice_line_id,goods_receipt_line_id,
            allocated_base_billed_quantity,allocated_base_free_quantity)
          VALUES(organization_id,(allocation->>'allocation_id')::uuid,(resolved_line->>'line_id')::uuid,
            (allocation->>'goods_receipt_line_id')::uuid,(allocation->>'allocated_base_billed_quantity')::numeric,
            (allocation->>'allocated_base_free_quantity')::numeric);
        END LOOP;
      END IF;
    END LOOP;
    PERFORM erp_commercial_commands.assert_supplier_invoice_artifact(organization_id,supplier_invoice_id,input_document,output_document);
    aggregate_hash:="erp_automation_commands"."aggregate_version_hash"('supplier_invoice',supplier_invoice_id,1);
    PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'procurement.supplier_invoice.prepare',
      (resolved_document->>'branch_id')::uuid,NULL,supplier_invoice_id,requested_total,'INR',key_hash,request_bytes,preview_bytes,NULL,aggregate_hash,expires_at);
    SELECT p_claim_id,p_replay_resource_id INTO claim_id,replay_id FROM erp_trade_commands.claim(organization_id,membership_id,
      'procurement.supplier_invoice.post',key_hash,extensions.digest(request_bytes,'sha256'),expires_at);
    IF replay_id IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier-invoice prepare replay reached completed execution'; END IF;
    PERFORM erp_calculation_authority.issue_artifact(artifact_id,(resolved_document->>'branch_id')::uuid,
      'procurement.supplier_invoice.post','supplier_invoice',supplier_invoice_id,1,request_id,command_id,claim_id,
      extensions.digest(request_bytes,'sha256'),calculation_input_bytes,calculation_output_bytes,output_document->>'engine_version',
      output_document->>'ruleset_version','aasopharma-jcs-decimal-v1',expires_at);
    RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
      'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, command_id uuid, artifact_id uuid, request_id uuid, tax_document_id uuid, journal_id uuid, event_id uuid, open_item_id uuid, key_hash bytea, sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, calculation_input_bytes bytea, calculation_output_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, command_id uuid, artifact_id uuid, request_id uuid, tax_document_id uuid, journal_id uuid, event_id uuid, open_item_id uuid, key_hash bytea, sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, calculation_input_bytes bytea, calculation_output_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, command_id uuid, artifact_id uuid, request_id uuid, tax_document_id uuid, journal_id uuid, event_id uuid, open_item_id uuid, key_hash bytea, sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, calculation_input_bytes bytea, calculation_output_bytes bytea, expires_at timestamptz) TO "erp_calculator";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_supplier_payment_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb; resolved_document jsonb; current_resolution jsonb; preview_document jsonb;
        existing automation.command_requests%ROWTYPE; payment_sequence_id uuid; journal_sequence_id uuid;
        payment_number text; journal_number text; fiscal_year integer; aggregate_hash bytea;
BEGIN
  IF SESSION_USER<>'erp_runtime' OR payment_id IS NULL OR command_id IS NULL OR journal_id IS NULL OR event_id IS NULL
     OR pg_catalog.octet_length(key_hash)<>32 OR pg_catalog.octet_length(payment_sequence_key_hash)<>32
     OR pg_catalog.octet_length(journal_sequence_key_hash)<>32 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier payment persistence envelope is invalid'; END IF;
  request_document:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
  resolved_document:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
  preview_document:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
  existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
    'finance.supplier_payment.prepare',payment_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:="erp_automation_commands"."resolve_supplier_payment_prepare"(organization_id,membership_id,auth_user_id,
    application_user_id,grant_id,caller_client_id,payment_id,request_document);
  PERFORM pg_catalog.set_config('app.request_id',command_id::text,true);
  IF current_resolution IS DISTINCT FROM resolved_document OR request_document->>'payment_id' IS DISTINCT FROM payment_id::text
     OR request_document->>'journal_id' IS DISTINCT FROM journal_id::text OR request_document->>'event_id' IS DISTINCT FROM event_id::text
     OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope'
     OR preview_document->'inventory_impact'<>'[]'::jsonb OR preview_document->'tax_impact'<>'[]'::jsonb
     OR preview_document->'calculation_ruleset'<>'[]'::jsonb THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='supplier payment resolution or immutable preview changed'; END IF;
  SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
    AND capability_code='finance.supplier_payment.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
  IF FOUND THEN
    IF existing.target_resource_id IS DISTINCT FROM payment_id OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
       OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256') THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier payment idempotency key has different exact input'; END IF;
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',(resolved_document->>'payment_date')::date)>=4
    THEN pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer
    ELSE pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer-1 END;
  aggregate_hash:=extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256');
  PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'finance.supplier_payment.prepare',
    (resolved_document->>'branch_id')::uuid,NULL,payment_id,(resolved_document->>'gross_amount')::numeric,'INR',key_hash,
    request_bytes,preview_bytes,NULL,aggregate_hash,expires_at);
  SELECT id INTO STRICT payment_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='supplier_payment'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  payment_number:=erp_core_commands.allocate_document_number(organization_id,payment_sequence_id,payment_sequence_key_hash,expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence_id,journal_sequence_key_hash,expires_at);
  INSERT INTO finance.payments(org_id,id,payment_number,payment_date,direction,party_id,branch_id,bank_account_id,
    settlement_account_id,payment_method,payment_purpose,currency_code,amount,functional_amount,fx_rate,external_reference,
    status,approved_at,approved_by_membership_id)
  VALUES(organization_id,payment_id,payment_number,(resolved_document->>'payment_date')::date,'disbursement',
    (resolved_document->>'supplier_party_id')::uuid,(resolved_document->>'branch_id')::uuid,
    (resolved_document->>'bank_account_id')::uuid,(resolved_document->>'settlement_account_id')::uuid,
    resolved_document->>'payment_method','commercial_settlement','INR',(resolved_document->>'cash_amount')::numeric,
    (resolved_document->>'cash_amount')::numeric,1,resolved_document->>'external_reference','approved',
    pg_catalog.transaction_timestamp(),membership_id);
  INSERT INTO finance.journal_entries(org_id,id,journal_number,posting_date,description,transaction_currency,functional_currency,
    fx_rate,transaction_debit_total,transaction_credit_total,functional_debit_total,functional_credit_total,status)
  VALUES(organization_id,journal_id,journal_number,(resolved_document->>'payment_date')::date,
    'Supplier payment '||payment_number,'INR','INR',1,(resolved_document->>'cash_amount')::numeric,
    (resolved_document->>'cash_amount')::numeric,(resolved_document->>'cash_amount')::numeric,(resolved_document->>'cash_amount')::numeric,'draft');
  INSERT INTO finance.journal_lines(org_id,id,journal_entry_id,line_number,account_id,branch_id,party_id,description,
    transaction_debit,transaction_credit,functional_debit,functional_credit)
  VALUES
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,1,(resolved_document->>'accounts_payable_account_id')::uuid,
    (resolved_document->>'branch_id')::uuid,(resolved_document->>'supplier_party_id')::uuid,'Supplier payable settlement',
    (resolved_document->>'cash_amount')::numeric,0,(resolved_document->>'cash_amount')::numeric,0),
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,2,(resolved_document->>'settlement_account_id')::uuid,
    (resolved_document->>'branch_id')::uuid,NULL,'Supplier payment bank settlement',0,
    (resolved_document->>'cash_amount')::numeric,0,(resolved_document->>'cash_amount')::numeric);
  PERFORM "erp_automation_commands"."assert_supplier_payment_draft"(organization_id,payment_id,journal_id,resolved_document);
  RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_supplier_payment_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_supplier_payment_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_supplier_payment_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_supplier_advance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb; resolved_document jsonb; current_resolution jsonb; preview_document jsonb;
        existing automation.command_requests%ROWTYPE; payment_sequence_id uuid; journal_sequence_id uuid;
        payment_number text; journal_number text; fiscal_year integer; aggregate_hash bytea;
BEGIN
  IF SESSION_USER<>'erp_runtime' OR payment_id IS NULL OR command_id IS NULL OR journal_id IS NULL OR event_id IS NULL
     OR pg_catalog.octet_length(key_hash)<>32 OR pg_catalog.octet_length(payment_sequence_key_hash)<>32
     OR pg_catalog.octet_length(journal_sequence_key_hash)<>32 OR pg_catalog.octet_length(request_bytes) NOT BETWEEN 2 AND 1048576
     OR pg_catalog.octet_length(resolved_bytes) NOT BETWEEN 2 AND 1048576 OR pg_catalog.octet_length(preview_bytes) NOT BETWEEN 2 AND 1048576 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier advance persistence envelope is invalid'; END IF;
  request_document:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
  resolved_document:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
  preview_document:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
  existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
    'finance.supplier_advance.prepare',payment_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:="erp_automation_commands"."resolve_supplier_advance_prepare"(organization_id,membership_id,auth_user_id,
    application_user_id,grant_id,caller_client_id,payment_id,request_document);
  PERFORM pg_catalog.set_config('app.request_id',command_id::text,true);
  IF current_resolution IS DISTINCT FROM resolved_document OR request_document->>'payment_id' IS DISTINCT FROM payment_id::text
     OR request_document->>'journal_id' IS DISTINCT FROM journal_id::text OR request_document->>'event_id' IS DISTINCT FROM event_id::text
     OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope'
     OR preview_document->'inventory_impact'<>'[]'::jsonb OR preview_document->'tax_impact'<>'[]'::jsonb
     OR preview_document->'calculation_ruleset'<>'[]'::jsonb THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='supplier advance resolution or immutable preview changed'; END IF;
  SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
    AND capability_code='finance.supplier_advance.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
  IF FOUND THEN
    IF existing.target_resource_id IS DISTINCT FROM payment_id OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
       OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256') THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier advance idempotency key has different exact input'; END IF;
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',(resolved_document->>'payment_date')::date)>=4
    THEN pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer
    ELSE pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer-1 END;
  aggregate_hash:=extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256');
  PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'finance.supplier_advance.prepare',
    (resolved_document->>'branch_id')::uuid,NULL,payment_id,(resolved_document->>'gross_amount')::numeric,'INR',key_hash,
    request_bytes,preview_bytes,NULL,aggregate_hash,expires_at);
  SELECT id INTO STRICT payment_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='supplier_advance'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  payment_number:=erp_core_commands.allocate_document_number(organization_id,payment_sequence_id,payment_sequence_key_hash,expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence_id,journal_sequence_key_hash,expires_at);
  INSERT INTO finance.payments(org_id,id,payment_number,payment_date,direction,party_id,branch_id,bank_account_id,
    settlement_account_id,payment_method,payment_purpose,currency_code,amount,functional_amount,fx_rate,external_reference,
    status,approved_at,approved_by_membership_id)
  VALUES(organization_id,payment_id,payment_number,(resolved_document->>'payment_date')::date,'disbursement',
    (resolved_document->>'supplier_party_id')::uuid,(resolved_document->>'branch_id')::uuid,
    (resolved_document->>'bank_account_id')::uuid,(resolved_document->>'settlement_account_id')::uuid,
    resolved_document->>'payment_method','supplier_advance','INR',(resolved_document->>'cash_amount')::numeric,
    (resolved_document->>'cash_amount')::numeric,1,resolved_document->>'external_reference','approved',
    pg_catalog.transaction_timestamp(),membership_id);
  INSERT INTO finance.journal_entries(org_id,id,journal_number,posting_date,description,transaction_currency,functional_currency,
    fx_rate,transaction_debit_total,transaction_credit_total,functional_debit_total,functional_credit_total,status)
  VALUES(organization_id,journal_id,journal_number,(resolved_document->>'payment_date')::date,
    'Supplier advance '||payment_number,'INR','INR',1,(resolved_document->>'cash_amount')::numeric,
    (resolved_document->>'cash_amount')::numeric,(resolved_document->>'cash_amount')::numeric,(resolved_document->>'cash_amount')::numeric,'draft');
  INSERT INTO finance.journal_lines(org_id,id,journal_entry_id,line_number,account_id,branch_id,party_id,description,
    transaction_debit,transaction_credit,functional_debit,functional_credit)
  VALUES
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,1,(resolved_document->>'supplier_prepayment_account_id')::uuid,
    (resolved_document->>'branch_id')::uuid,(resolved_document->>'supplier_party_id')::uuid,'Supplier goods prepayment',
    (resolved_document->>'gross_amount')::numeric,0,(resolved_document->>'gross_amount')::numeric,0),
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,2,(resolved_document->>'settlement_account_id')::uuid,
    (resolved_document->>'branch_id')::uuid,NULL,'Supplier advance bank settlement',0,
    (resolved_document->>'cash_amount')::numeric,0,(resolved_document->>'cash_amount')::numeric);
  PERFORM "erp_automation_commands"."assert_supplier_advance_draft"(organization_id,payment_id,journal_id,resolved_document);
  RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_supplier_advance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_supplier_advance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_supplier_advance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_customer_receipt_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb; resolved_document jsonb; current_resolution jsonb; preview_document jsonb;
        existing automation.command_requests%ROWTYPE; payment_sequence_id uuid; journal_sequence_id uuid;
        payment_number text; journal_number text; fiscal_year integer; aggregate_hash bytea;
BEGIN
  IF SESSION_USER<>'erp_runtime' OR payment_id IS NULL OR command_id IS NULL OR journal_id IS NULL OR event_id IS NULL
     OR pg_catalog.octet_length(key_hash)<>32 OR pg_catalog.octet_length(payment_sequence_key_hash)<>32
     OR pg_catalog.octet_length(journal_sequence_key_hash)<>32 OR pg_catalog.octet_length(request_bytes) NOT BETWEEN 2 AND 1048576
     OR pg_catalog.octet_length(resolved_bytes) NOT BETWEEN 2 AND 1048576 OR pg_catalog.octet_length(preview_bytes) NOT BETWEEN 2 AND 1048576 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='customer receipt persistence envelope is invalid'; END IF;
  BEGIN request_document:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
    resolved_document:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
    preview_document:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
  EXCEPTION WHEN OTHERS THEN RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='customer receipt persistence requires UTF-8 JSON'; END;
  existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
    'finance.customer_receipt.prepare',payment_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:="erp_automation_commands"."resolve_customer_receipt_prepare"(organization_id,membership_id,auth_user_id,
    application_user_id,grant_id,caller_client_id,payment_id,request_document);
  PERFORM pg_catalog.set_config('app.request_id',command_id::text,true);
  IF current_resolution IS DISTINCT FROM resolved_document OR request_document->>'payment_id' IS DISTINCT FROM payment_id::text
     OR request_document->>'journal_id' IS DISTINCT FROM journal_id::text OR request_document->>'event_id' IS DISTINCT FROM event_id::text
     OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope'
     OR preview_document->'inventory_impact'<>'[]'::jsonb OR preview_document->'tax_impact'<>'[]'::jsonb
     OR preview_document->'calculation_ruleset'<>'[]'::jsonb THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='customer receipt resolution or immutable preview changed'; END IF;
  SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
    AND capability_code='finance.customer_receipt.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
  IF FOUND THEN
    IF existing.target_resource_id IS DISTINCT FROM payment_id OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256')
       OR existing.preview_hash IS DISTINCT FROM extensions.digest(preview_bytes,'sha256') THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='customer receipt idempotency key has different exact input'; END IF;
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  fiscal_year:=CASE WHEN pg_catalog.date_part('month',(resolved_document->>'payment_date')::date)>=4
    THEN pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer
    ELSE pg_catalog.date_part('year',(resolved_document->>'payment_date')::date)::integer-1 END;
  aggregate_hash:=extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256');
  PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'finance.customer_receipt.prepare',
    (resolved_document->>'branch_id')::uuid,NULL,payment_id,(resolved_document->>'amount')::numeric,'INR',key_hash,
    request_bytes,preview_bytes,NULL,aggregate_hash,expires_at);
  SELECT id INTO STRICT payment_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='customer_receipt'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  payment_number:=erp_core_commands.allocate_document_number(organization_id,payment_sequence_id,payment_sequence_key_hash,expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence_id,journal_sequence_key_hash,expires_at);
  INSERT INTO finance.payments(org_id,id,payment_number,payment_date,direction,party_id,branch_id,bank_account_id,
    settlement_account_id,payment_method,payment_purpose,currency_code,amount,functional_amount,fx_rate,external_reference,
    sales_order_id,evidence_attachment_id,instrument_number,instrument_date,drawee_bank_name,account_payee_confirmed,
    status,approved_at,approved_by_membership_id)
  VALUES(organization_id,payment_id,payment_number,(resolved_document->>'payment_date')::date,'receipt',
    (resolved_document->>'customer_party_id')::uuid,(resolved_document->>'branch_id')::uuid,
    (resolved_document->>'bank_account_id')::uuid,(resolved_document->>'settlement_account_id')::uuid,
    resolved_document->>'payment_method',CASE resolved_document->>'receipt_purpose' WHEN 'customer_advance' THEN 'customer_advance' ELSE 'commercial_settlement' END,
    'INR',(resolved_document->>'amount')::numeric,
    (resolved_document->>'amount')::numeric,1,resolved_document->>'external_reference',
    (resolved_document->>'sales_order_id')::uuid,(resolved_document->>'evidence_attachment_id')::uuid,
    resolved_document->>'instrument_number',(resolved_document->>'instrument_date')::date,
    resolved_document->>'drawee_bank_name',(resolved_document->>'account_payee_confirmed')::boolean,
    'approved',pg_catalog.transaction_timestamp(),membership_id);
  INSERT INTO finance.journal_entries(org_id,id,journal_number,posting_date,description,transaction_currency,functional_currency,
    fx_rate,transaction_debit_total,transaction_credit_total,functional_debit_total,functional_credit_total,status)
  VALUES(organization_id,journal_id,journal_number,(resolved_document->>'payment_date')::date,
    'Customer receipt '||payment_number,'INR','INR',1,(resolved_document->>'amount')::numeric,
    (resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,'draft');
  INSERT INTO finance.journal_lines(org_id,id,journal_entry_id,line_number,account_id,branch_id,party_id,description,
    transaction_debit,transaction_credit,functional_debit,functional_credit)
  VALUES
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,1,(resolved_document->>'settlement_account_id')::uuid,
    (resolved_document->>'branch_id')::uuid,NULL,'Customer receipt bank settlement',(resolved_document->>'amount')::numeric,0,
    (resolved_document->>'amount')::numeric,0),
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,2,(CASE WHEN resolved_document->>'receipt_purpose'='customer_advance'
      THEN resolved_document->>'customer_advance_account_id' ELSE resolved_document->>'accounts_receivable_account_id' END)::uuid,
    (resolved_document->>'branch_id')::uuid,(resolved_document->>'customer_party_id')::uuid,
    CASE WHEN resolved_document->>'receipt_purpose'='customer_advance' THEN 'Customer goods advance liability' ELSE 'Customer receivable allocation' END,0,
    (resolved_document->>'amount')::numeric,0,(resolved_document->>'amount')::numeric);
  PERFORM "erp_automation_commands"."assert_customer_receipt_draft"(organization_id,payment_id,journal_id,resolved_document);
  RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_customer_receipt_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_customer_receipt_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_customer_receipt_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_customer_cheque_clearance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
        resolved_document jsonb:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
        preview_document jsonb:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
        current_resolution jsonb; existing automation.command_requests%ROWTYPE;
        payment_sequence_id uuid; journal_sequence_id uuid; original_journal_id uuid;
        payment_number text; journal_number text; fiscal_year integer;
BEGIN
  existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
    'finance.customer_cheque_clearance.prepare',payment_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:="erp_automation_commands"."resolve_customer_cheque_clearance_prepare"(organization_id,membership_id,
    auth_user_id,application_user_id,grant_id,caller_client_id,payment_id,request_document);
  IF current_resolution IS DISTINCT FROM resolved_document OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope' THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='cheque clearance resolution changed'; END IF;
  SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
    AND capability_code='finance.customer_cheque_clearance.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
  IF FOUND THEN
    IF existing.target_resource_id IS DISTINCT FROM payment_id OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256') THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='cheque clearance idempotency input changed'; END IF;
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  PERFORM pg_catalog.set_config('app.request_id',command_id::text,true);
  PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'finance.customer_cheque_clearance.prepare',
    (resolved_document->>'branch_id')::uuid,NULL,payment_id,(resolved_document->>'amount')::numeric,'INR',key_hash,
    request_bytes,preview_bytes,NULL,extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256'),expires_at);
  fiscal_year:=CASE WHEN extract(month FROM (resolved_document->>'action_date')::date)>=4
    THEN extract(year FROM (resolved_document->>'action_date')::date)::integer
    ELSE extract(year FROM (resolved_document->>'action_date')::date)::integer-1 END;
  SELECT id INTO STRICT payment_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='customer_receipt'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  payment_number:=erp_core_commands.allocate_document_number(organization_id,payment_sequence_id,payment_sequence_key_hash,expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence_id,journal_sequence_key_hash,expires_at);
  IF 'clearance'='bounce' THEN SELECT journal_entry_id INTO STRICT original_journal_id FROM finance.accounting_events
    WHERE org_id=organization_id AND payment_id=(resolved_document->>'original_payment_id')::uuid FOR SHARE; END IF;
  INSERT INTO finance.payments(org_id,id,payment_number,payment_date,direction,party_id,branch_id,bank_account_id,
    settlement_account_id,payment_method,payment_purpose,currency_code,amount,functional_amount,fx_rate,external_reference,
    related_payment_id,evidence_attachment_id,memo,status,approved_at,approved_by_membership_id)
  VALUES(organization_id,payment_id,payment_number,(resolved_document->>'action_date')::date,
    CASE 'clearance' WHEN 'bounce' THEN 'disbursement' ELSE 'receipt' END,(resolved_document->>'customer_party_id')::uuid,
    (resolved_document->>'branch_id')::uuid,(resolved_document->>'bank_account_id')::uuid,
    (resolved_document->>'settlement_account_id')::uuid,CASE 'clearance' WHEN 'bounce' THEN 'cheque' ELSE 'bank_transfer' END,
    'cheque_clearance','INR',(resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,1,
    resolved_document->>'external_reference',(resolved_document->>'original_payment_id')::uuid,
    (resolved_document->>'evidence_attachment_id')::uuid,resolved_document->>'reason_code','approved',
    pg_catalog.transaction_timestamp(),membership_id);
  INSERT INTO finance.journal_entries(org_id,id,journal_number,posting_date,description,transaction_currency,functional_currency,
    fx_rate,transaction_debit_total,transaction_credit_total,functional_debit_total,functional_credit_total,
    reversal_of_journal_entry_id,reversal_reason,status)
  VALUES(organization_id,journal_id,journal_number,(resolved_document->>'action_date')::date,'Customer cheque clearance',
    'INR','INR',1,(resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,
    (resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,original_journal_id,
    CASE 'clearance' WHEN 'bounce' THEN resolved_document->>'reason_code' ELSE NULL END,'draft');
  INSERT INTO finance.journal_lines(org_id,id,journal_entry_id,line_number,account_id,branch_id,party_id,description,
    transaction_debit,transaction_credit,functional_debit,functional_credit)
  VALUES
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,1,(CASE 'clearance' WHEN 'bounce' THEN resolved_document->>'offset_account_id'
      ELSE resolved_document->>'settlement_account_id' END)::uuid,(resolved_document->>'branch_id')::uuid,
      CASE 'clearance' WHEN 'bounce' THEN (resolved_document->>'customer_party_id')::uuid ELSE NULL END,'Cheque clearance debit',
      (resolved_document->>'amount')::numeric,0,(resolved_document->>'amount')::numeric,0),
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,2,(resolved_document->>'cheques_in_hand_account_id')::uuid,
      (resolved_document->>'branch_id')::uuid,NULL,'Cheque clearance credit',0,(resolved_document->>'amount')::numeric,
      0,(resolved_document->>'amount')::numeric);
  RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_customer_cheque_clearance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_customer_cheque_clearance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_customer_cheque_clearance_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
        resolved_document jsonb:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
        preview_document jsonb:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
        current_resolution jsonb; existing automation.command_requests%ROWTYPE;
        payment_sequence_id uuid; journal_sequence_id uuid; original_journal_id uuid;
        payment_number text; journal_number text; fiscal_year integer;
BEGIN
  existing:="erp_automation_commands"."find_exact_prepare_replay"(organization_id,grant_id,
    'finance.customer_cheque_bounce.prepare',payment_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:="erp_automation_commands"."resolve_customer_cheque_bounce_prepare"(organization_id,membership_id,
    auth_user_id,application_user_id,grant_id,caller_client_id,payment_id,request_document);
  IF current_resolution IS DISTINCT FROM resolved_document OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope' THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='cheque bounce resolution changed'; END IF;
  SELECT * INTO existing FROM automation.command_requests WHERE org_id=organization_id AND agent_grant_id=grant_id
    AND capability_code='finance.customer_cheque_bounce.prepare' AND idempotency_key_hash=key_hash FOR SHARE;
  IF FOUND THEN
    IF existing.target_resource_id IS DISTINCT FROM payment_id OR existing.request_hash IS DISTINCT FROM extensions.digest(request_bytes,'sha256') THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='cheque bounce idempotency input changed'; END IF;
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  PERFORM pg_catalog.set_config('app.request_id',command_id::text,true);
  PERFORM "erp_automation_commands"."prepare_operator_command"(organization_id,command_id,grant_id,'finance.customer_cheque_bounce.prepare',
    (resolved_document->>'branch_id')::uuid,NULL,payment_id,(resolved_document->>'amount')::numeric,'INR',key_hash,
    request_bytes,preview_bytes,NULL,extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256'),expires_at);
  fiscal_year:=CASE WHEN extract(month FROM (resolved_document->>'action_date')::date)>=4
    THEN extract(year FROM (resolved_document->>'action_date')::date)::integer
    ELSE extract(year FROM (resolved_document->>'action_date')::date)::integer-1 END;
  SELECT id INTO STRICT payment_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='customer_receipt'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  SELECT id INTO STRICT journal_sequence_id FROM core.document_sequences WHERE org_id=organization_id
    AND branch_id=(resolved_document->>'branch_id')::uuid AND document_type='journal_entry'
    AND fiscal_year_start=pg_catalog.make_date(fiscal_year,4,1) AND status='active' FOR SHARE;
  payment_number:=erp_core_commands.allocate_document_number(organization_id,payment_sequence_id,payment_sequence_key_hash,expires_at);
  journal_number:=erp_core_commands.allocate_document_number(organization_id,journal_sequence_id,journal_sequence_key_hash,expires_at);
  IF 'bounce'='bounce' THEN SELECT journal_entry_id INTO STRICT original_journal_id FROM finance.accounting_events
    WHERE org_id=organization_id AND payment_id=(resolved_document->>'original_payment_id')::uuid FOR SHARE; END IF;
  INSERT INTO finance.payments(org_id,id,payment_number,payment_date,direction,party_id,branch_id,bank_account_id,
    settlement_account_id,payment_method,payment_purpose,currency_code,amount,functional_amount,fx_rate,external_reference,
    related_payment_id,evidence_attachment_id,memo,status,approved_at,approved_by_membership_id)
  VALUES(organization_id,payment_id,payment_number,(resolved_document->>'action_date')::date,
    CASE 'bounce' WHEN 'bounce' THEN 'disbursement' ELSE 'receipt' END,(resolved_document->>'customer_party_id')::uuid,
    (resolved_document->>'branch_id')::uuid,(resolved_document->>'bank_account_id')::uuid,
    (resolved_document->>'settlement_account_id')::uuid,CASE 'bounce' WHEN 'bounce' THEN 'cheque' ELSE 'bank_transfer' END,
    'cheque_bounce','INR',(resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,1,
    resolved_document->>'external_reference',(resolved_document->>'original_payment_id')::uuid,
    (resolved_document->>'evidence_attachment_id')::uuid,resolved_document->>'reason_code','approved',
    pg_catalog.transaction_timestamp(),membership_id);
  INSERT INTO finance.journal_entries(org_id,id,journal_number,posting_date,description,transaction_currency,functional_currency,
    fx_rate,transaction_debit_total,transaction_credit_total,functional_debit_total,functional_credit_total,
    reversal_of_journal_entry_id,reversal_reason,status)
  VALUES(organization_id,journal_id,journal_number,(resolved_document->>'action_date')::date,'Customer cheque bounce',
    'INR','INR',1,(resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,
    (resolved_document->>'amount')::numeric,(resolved_document->>'amount')::numeric,original_journal_id,
    CASE 'bounce' WHEN 'bounce' THEN resolved_document->>'reason_code' ELSE NULL END,'draft');
  INSERT INTO finance.journal_lines(org_id,id,journal_entry_id,line_number,account_id,branch_id,party_id,description,
    transaction_debit,transaction_credit,functional_debit,functional_credit)
  VALUES
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,1,(CASE 'bounce' WHEN 'bounce' THEN resolved_document->>'offset_account_id'
      ELSE resolved_document->>'settlement_account_id' END)::uuid,(resolved_document->>'branch_id')::uuid,
      CASE 'bounce' WHEN 'bounce' THEN (resolved_document->>'customer_party_id')::uuid ELSE NULL END,'Cheque bounce debit',
      (resolved_document->>'amount')::numeric,0,(resolved_document->>'amount')::numeric,0),
   (organization_id,pg_catalog.gen_random_uuid(),journal_id,2,(resolved_document->>'cheques_in_hand_account_id')::uuid,
      (resolved_document->>'branch_id')::uuid,NULL,'Cheque bounce credit',0,(resolved_document->>'amount')::numeric,
      0,(resolved_document->>'amount')::numeric);
  RETURN pg_catalog.jsonb_build_object('command_request_id',command_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),'replayed',false);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."persist_customer_cheque_bounce_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, payment_id uuid, command_id uuid, journal_id uuid, event_id uuid, key_hash bytea, payment_sequence_key_hash bytea, journal_sequence_key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz) TO "erp_runtime";
CREATE OR REPLACE FUNCTION "erp_commercial_commands"."persist_commercial_reversal_prepare"(organization_id uuid, reversal_kind text, original_resource_id uuid, reversal_adjustment_note_id uuid, command_request_id uuid, grant_id uuid, key_hash bytea, request_bytes bytea, resolved_bytes bytea, preview_bytes bytea, expires_at timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE request_document jsonb:=pg_catalog.convert_from(request_bytes,'UTF8')::jsonb;
        resolved_document jsonb:=pg_catalog.convert_from(resolved_bytes,'UTF8')::jsonb;
        preview_document jsonb:=pg_catalog.convert_from(preview_bytes,'UTF8')::jsonb;
        current_resolution jsonb; capability_name text; persisted_id uuid;
        existing automation.command_requests%ROWTYPE;
BEGIN
  IF SESSION_USER<>'erp_runtime' OR reversal_kind NOT IN ('sales_return','purchase_return','adjustment_note')
     OR request_document->>'original_resource_id' IS DISTINCT FROM original_resource_id::text
     OR request_document->>'reversal_adjustment_note_id' IS DISTINCT FROM reversal_adjustment_note_id::text THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='commercial reversal persistence boundary is invalid'; END IF;
  capability_name:=CASE reversal_kind WHEN 'sales_return' THEN 'sales.return.reversal.prepare'
    WHEN 'purchase_return' THEN 'procurement.purchase_return.reversal.prepare'
    ELSE 'finance.adjustment_note.reversal.prepare' END;
  existing:=erp_automation_commands.find_exact_prepare_replay(organization_id,grant_id,
    capability_name,reversal_adjustment_note_id,key_hash,request_bytes,preview_bytes);
  IF existing.id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('command_request_id',existing.id,'expires_at',existing.expires_at,
      'preview_hash',pg_catalog.encode(existing.preview_hash,'hex'),'replayed',true);
  END IF;
  current_resolution:=erp_commercial_commands.resolve_commercial_reversal_prepare(organization_id,reversal_kind,
    original_resource_id,(request_document->>'expected_row_version')::bigint,
    (request_document->>'reversal_date')::date,request_document->>'reason',
    NULLIF(request_document->>'amendment_evidence_attachment_id','')::uuid);
  IF current_resolution IS DISTINCT FROM resolved_document
     OR preview_document->>'capability_code' IS DISTINCT FROM capability_name
     OR preview_document->>'target_resource_id' IS DISTINCT FROM reversal_adjustment_note_id::text
     OR preview_document->'source_versions' IS DISTINCT FROM resolved_document->'source_versions'
     OR preview_document->'legal_scope' IS DISTINCT FROM resolved_document->'legal_scope'
     OR preview_document->'calculation_ruleset'<>'[]'::jsonb THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='commercial reversal resolution or immutable preview changed'; END IF;
  PERFORM pg_catalog.set_config('app.request_id',command_request_id::text,true);
  persisted_id:=erp_automation_commands.prepare_operator_command(organization_id,command_request_id,grant_id,
    capability_name,(resolved_document->>'branch_id')::uuid,NULL,reversal_adjustment_note_id,
    (resolved_document->>'counterparty_payable_amount')::numeric,'INR',key_hash,request_bytes,preview_bytes,NULL,
    extensions.digest(pg_catalog.convert_to((resolved_document->'source_versions')::text,'UTF8'),'sha256'),expires_at);
  RETURN pg_catalog.jsonb_build_object('command_request_id',persisted_id,'expires_at',expires_at,
    'preview_hash',pg_catalog.encode(extensions.digest(preview_bytes,'sha256'),'hex'),
    'replayed',persisted_id IS DISTINCT FROM command_request_id);
END
$function$;
ALTER FUNCTION "erp_commercial_commands"."persist_commercial_reversal_prepare"(uuid,text,uuid,uuid,uuid,uuid,bytea,bytea,bytea,bytea,timestamptz) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."persist_commercial_reversal_prepare"(uuid,text,uuid,uuid,uuid,uuid,bytea,bytea,bytea,bytea,timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_commercial_commands"."persist_commercial_reversal_prepare"(uuid,text,uuid,uuid,uuid,uuid,bytea,bytea,bytea,bytea,timestamptz) TO "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."post_supplier_invoice"(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,varchar,uuid,uuid,uuid,bytea,bytea,bytea,bytea,timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."post_sales_return_reversal"(uuid,uuid,bigint,uuid,varchar,uuid,varchar,uuid,varchar,uuid,uuid,date,text,uuid,bytea,bytea,timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."post_purchase_return_reversal"(uuid,uuid,bigint,uuid,varchar,uuid,varchar,uuid,varchar,uuid,uuid,date,text,uuid,bytea,bytea,timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_commercial_commands"."post_adjustment_note_reversal"(uuid,uuid,bigint,uuid,varchar,uuid,varchar,uuid,varchar,uuid,uuid,date,text,uuid,bytea,bytea,timestamptz) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_payment"(organization_id uuid, payment_id uuid, journal_id uuid, event_id uuid) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_customer_receipt"(organization_id uuid, payment_id uuid, journal_id uuid, event_id uuid, receipt_allocations jsonb, customer_advance_open_item_id uuid) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_customer_cheque_clearance"(organization_id uuid, original_payment_id uuid, clearance_payment_id uuid, journal_id uuid, event_id uuid) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_customer_cheque_bounce"(organization_id uuid, original_payment_id uuid, bounce_payment_id uuid, journal_id uuid, event_id uuid, compensating_allocations jsonb) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_supplier_payment"(organization_id uuid, payment_id uuid, journal_id uuid, event_id uuid, settlement_components jsonb) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."post_supplier_advance_payment"(organization_id uuid, payment_id uuid, journal_id uuid, event_id uuid, advance_allocations jsonb) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."reverse_payment"(organization_id uuid, original_payment_id uuid, reversal_payment_id uuid, reversal_payment_number varchar, reversal_journal_id uuid, reversal_journal_number varchar, reversal_event_id uuid, reason text) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."apply_supplier_advance"(organization_id uuid, advance_allocation_id uuid, supplier_invoice_line_id uuid, invoice_open_item_id uuid, allocation_id uuid, journal_id uuid, journal_number varchar, event_id uuid) FROM PUBLIC, "erp_app", "erp_runtime";
REVOKE ALL ON FUNCTION "erp_finance_commands"."apply_supplier_adjustment_credit"(organization_id uuid, adjustment_note_id uuid, source_open_item_id uuid, target_open_item_id uuid, allocation_id uuid, application_date date) FROM PUBLIC, "erp_app", "erp_runtime";
RESET ROLE;
