-- Generated by backend/scripts/generate_sales_invoice_auto_fefo_migration.py.
-- Alembic owns the transaction; this file must not be applied directly.
SET LOCAL ROLE erp_migration_owner;

DO $migration$
DECLARE definition text;
BEGIN
  SELECT pg_catalog.pg_get_functiondef(
    'erp_automation_commands.resolve_sales_invoice_prepare(uuid,uuid,uuid,uuid,uuid,character varying,uuid,jsonb)'::pg_catalog.regprocedure
  ) INTO STRICT definition;
  IF pg_catalog.strpos(definition,'delivery_address_row_version bigint')=0
     OR pg_catalog.strpos(definition,'sales_invoice_fefo_expiry_date_equivalence_v1')=0
     OR pg_catalog.strpos(definition,'direct invoice batch allocations are invalid')=0
     OR pg_catalog.strpos(definition,'sales_invoice_auto_fefo_v1')<>0 THEN
    RAISE EXCEPTION USING ERRCODE='55000',
      MESSAGE='sales-invoice resolver differs from reviewed auto-FEFO migration precondition';
  END IF;
END
$migration$;

CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_sales_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, invoice_id uuid, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE
    branch_id uuid:=NULLIF(request_document->>'branch_id','')::uuid;
    customer_account_id uuid:=NULLIF(request_document->>'customer_account_id','')::uuid;
    delivery_address_id uuid:=NULLIF(request_document->>'delivery_address_id','')::uuid;
    delivery_address_row_version bigint:=NULLIF(request_document->>'delivery_address_row_version','')::bigint;
    from_location_id uuid:=NULLIF(request_document->>'from_location_id','')::uuid;
    invoice_date date:=NULLIF(request_document->>'invoice_date','')::date;
    place_of_supply text;
    zero_mode text:=request_document->>'zero_rated_payment_mode';
    logistics jsonb:=request_document->'logistics';
    transport_mode text:=logistics->>'transport_mode';
    transporter_party_id uuid:=NULLIF(logistics->>'transporter_party_id','')::uuid;
    has_direct boolean;
    has_allocated boolean;
    supply_type text;
    branch core.branches%ROWTYPE;
    organization core.organizations%ROWTYPE;
    customer parties.customer_accounts%ROWTYPE;
    customer_party parties.parties%ROWTYPE;
    customer_registration parties.tax_registrations%ROWTYPE;
    seller_registration tax.registrations%ROWTYPE;
    seller_registration_branch tax.registration_branches%ROWTYPE;
    billing parties.addresses%ROWTYPE;
    shipping parties.addresses%ROWTYPE;
    location inventory.locations%ROWTYPE;
    transporter parties.parties%ROWTYPE;
    transporter_registration parties.tax_registrations%ROWTYPE;
    revenue_account finance.accounts%ROWTYPE;
    product catalog.products%ROWTYPE;
    conversion catalog.uom_conversions%ROWTYPE;
    tax_version tax.tax_code_versions%ROWTYPE;
    tax_release core.reference_data_releases%ROWTYPE;
    profile catalog.commercial_charge_tax_profiles%ROWTYPE;
    batch inventory.batches%ROWTYPE;
    balance inventory.stock_balances%ROWTYPE;
    dispatch_line sales.dispatch_lines%ROWTYPE;
    dispatch_header sales.dispatches%ROWTYPE;
    order_line sales.order_lines%ROWTYPE;
    eligible record;
    requested_line jsonb;
    requested_allocation jsonb;
    resolved_line jsonb;
    resolved_lines jsonb:='[]'::jsonb;
    resolved_allocations jsonb;
    source_versions jsonb:='[]'::jsonb;
    allocation_tracker jsonb:='{}'::jsonb;
    dispatch_tracker jsonb:='{}'::jsonb;
    auto_allocations jsonb;
    allocation_mode text;
    billed numeric(20,6);
    free numeric(20,6);
    base_billed numeric(20,6);
    base_free numeric(20,6);
    allocated_billed numeric(20,6);
    allocated_free numeric(20,6);
    allocation_billed numeric(20,6);
    allocation_free numeric(20,6);
    prior_base numeric(20,6);
    prior_value numeric(20,2);
    current_quantity numeric(20,6);
    current_value numeric(20,2);
    current_unit_cost numeric(20,4);
    extended_cost numeric(20,2);
    existing_billed numeric(20,6);
    existing_free numeric(20,6);
    remaining_billed numeric(20,6);
    remaining_free numeric(20,6);
    candidate_billed numeric(20,6);
    candidate_free numeric(20,6);
    available_entered numeric(20,6);
    total_base numeric(20,6):=0;
    total_value numeric(20,2):=0;
    line_number integer:=0;
    registration_count integer;
    address_count integer;
    bad_count integer;
    ruleset_version text;
BEGIN
    IF organization_id IS NULL OR membership_id IS NULL OR auth_user_id IS NULL
       OR application_user_id IS NULL OR grant_id IS NULL OR invoice_id IS NULL
       OR branch_id IS NULL OR customer_account_id IS NULL OR invoice_date IS NULL
       OR delivery_address_id IS NULL OR delivery_address_row_version IS NULL
       OR delivery_address_row_version<1 OR request_document?'place_of_supply_state_code'
       OR request_document?'shipping_address_id'
       OR request_document->>'tax_charge_mechanism'<>'normal'
       OR zero_mode NOT IN ('not_applicable','with_igst')
       OR pg_catalog.jsonb_typeof(request_document)<>'object'
       OR pg_catalog.jsonb_typeof(request_document->'lines')<>'array'
       OR pg_catalog.jsonb_array_length(request_document->'lines') NOT BETWEEN 1 AND 500
       OR pg_catalog.jsonb_typeof(COALESCE(request_document->'charge_lines','[]'::jsonb))<>'array' THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='sales-invoice resolve input is incomplete or outside the pilot legal scope';
    END IF;
    has_direct:=EXISTS(
      SELECT 1 FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
       WHERE line.value->>'fulfillment_source'='direct_issue');
    has_allocated:=EXISTS(
      SELECT 1 FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
       WHERE line.value->>'fulfillment_source'='dispatch_allocated');
    IF EXISTS(
      SELECT 1 FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
       WHERE line.value->>'fulfillment_source' NOT IN ('direct_issue','dispatch_allocated'))
       OR (has_direct AND (from_location_id IS NULL OR pg_catalog.jsonb_typeof(logistics)<>'object'))
       OR (NOT has_direct AND (from_location_id IS NOT NULL OR logistics IS NOT NULL)) THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='invoice fulfillment source, location, and logistics shape differ';
    END IF;
    IF has_direct THEN
      IF transport_mode NOT IN ('road','rail','air','ship','multimodal','in_person')
         OR NULLIF(logistics->>'distance_km','')::numeric<0
         OR (transport_mode='road' AND (NULLIF(logistics->>'vehicle_number','') IS NULL
             OR logistics->>'vehicle_type' NOT IN ('regular','over_dimensional_cargo')))
         OR (transport_mode<>'road' AND (NULLIF(logistics->>'vehicle_number','') IS NOT NULL
             OR NULLIF(logistics->>'vehicle_type','') IS NOT NULL))
         OR (transport_mode IN ('rail','air','ship','multimodal') AND
             (NULLIF(logistics->>'transport_document_number','') IS NULL
              OR NULLIF(logistics->>'transport_document_date','')::date IS NULL))
         OR ((NULLIF(logistics->>'transport_document_number','') IS NULL) IS DISTINCT FROM
             (NULLIF(logistics->>'transport_document_date','') IS NULL))
         OR (transport_mode='in_person' AND
             (transporter_party_id IS NOT NULL OR NULLIF(logistics->>'transport_document_number','') IS NOT NULL))
         OR (transport_mode<>'in_person' AND transporter_party_id IS NULL) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice logistics fields do not match the selected transport mode';
      END IF;
    END IF;
    PERFORM 1
      FROM core.memberships membership
      JOIN core.users user_row ON user_row.id=membership.user_id
      JOIN core.organizations organization_row ON organization_row.id=membership.org_id
      JOIN automation.agent_grants grant_row ON grant_row.org_id=membership.org_id
       AND grant_row.subject_membership_id=membership.id
      JOIN automation.agent_grant_capabilities capability ON capability.org_id=grant_row.org_id
       AND capability.agent_grant_id=grant_row.id
     WHERE membership.org_id=organization_id AND membership.id=membership_id
       AND membership.user_id=application_user_id AND membership.status='active'
       AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
       AND organization_row.status='active' AND grant_row.id=grant_id
       AND grant_row.client_id=caller_client_id AND grant_row.status='active'
       AND grant_row.expires_at>pg_catalog.transaction_timestamp()
       AND (grant_row.branch_id IS NULL OR grant_row.branch_id=branch_id)
       AND capability.capability_code='sales.invoice.prepare'
       AND capability.operation_mode='write' AND capability.status='active';
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-invoice delegated authority is inactive'; END IF;
    PERFORM erp_security.activate_context(auth_user_id,organization_id);
    IF erp_security.current_membership_id() IS DISTINCT FROM membership_id THEN
      RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-invoice verified auth context resolved a different membership'; END IF;
    IF erp_security.can_access_branch(branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('sales.invoice.create',branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('sales.invoice.post',branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('automation.command.execute',branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('finance.journal.post',NULL::uuid) IS DISTINCT FROM true
       OR (has_direct AND erp_security.has_permission('inventory.document.post',branch_id) IS DISTINCT FROM true) THEN
      RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='sales-invoice cross-domain permission is inactive'; END IF;
    SELECT * INTO STRICT organization FROM core.organizations
     WHERE id=organization_id AND status='active' FOR SHARE;
    IF organization.country_code<>'IN' OR organization.base_currency<>'INR' THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='sales-invoice pilot supports only Indian INR organizations'; END IF;
    SELECT * INTO STRICT branch FROM core.branches
     WHERE org_id=organization_id AND id=branch_id AND status='active' FOR SHARE;
    SELECT count(*) INTO registration_count FROM tax.registration_branches association
      JOIN tax.registrations registration ON registration.org_id=association.org_id
       AND registration.id=association.registration_id
     WHERE association.org_id=organization_id AND association.branch_id=branch.id
       AND association.status='active' AND association.effective_from<=invoice_date
       AND (association.effective_to IS NULL OR association.effective_to>=invoice_date)
       AND registration.state_code=branch.state_code AND registration.status='active'
       AND registration.effective_from<=invoice_date
       AND (registration.effective_to IS NULL OR registration.effective_to>=invoice_date);
    IF registration_count<>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='seller has no exact effective branch-state GST registration'; END IF;
    SELECT registration.* INTO STRICT seller_registration FROM tax.registration_branches association
      JOIN tax.registrations registration ON registration.org_id=association.org_id
       AND registration.id=association.registration_id
     WHERE association.org_id=organization_id AND association.branch_id=branch.id
       AND association.status='active' AND association.effective_from<=invoice_date
       AND (association.effective_to IS NULL OR association.effective_to>=invoice_date)
       AND registration.state_code=branch.state_code AND registration.status='active'
       AND registration.effective_from<=invoice_date
       AND (registration.effective_to IS NULL OR registration.effective_to>=invoice_date)
     FOR SHARE OF association,registration;
    SELECT * INTO STRICT seller_registration_branch FROM tax.registration_branches association
     WHERE association.org_id=organization_id AND association.registration_id=seller_registration.id
       AND association.branch_id=branch.id AND association.status='active'
       AND association.effective_from<=invoice_date
       AND (association.effective_to IS NULL OR association.effective_to>=invoice_date) FOR SHARE;
    IF seller_registration.registration_type<>'regular' THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='pilot invoice posting requires a regular seller GST registration'; END IF;
    SELECT * INTO STRICT customer FROM parties.customer_accounts
     WHERE org_id=organization_id AND id=customer_account_id AND status='active' FOR SHARE;
    SELECT * INTO STRICT customer_party FROM parties.parties
     WHERE org_id=organization_id AND id=customer.party_id AND status='active' FOR SHARE;
    SELECT count(*) INTO address_count FROM parties.addresses
     WHERE org_id=organization_id AND party_id=customer.party_id AND address_kind='billing'
       AND is_primary AND status='active' AND valid_from<=invoice_date
       AND (valid_until IS NULL OR valid_until>=invoice_date);
    IF address_count>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='customer billing address is ambiguous';
    ELSIF address_count=1 THEN
      SELECT * INTO STRICT billing FROM parties.addresses WHERE org_id=organization_id AND party_id=customer.party_id
       AND address_kind='billing' AND is_primary AND status='active' AND valid_from<=invoice_date
       AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
    ELSE
      SELECT * INTO STRICT billing FROM parties.addresses WHERE org_id=organization_id AND party_id=customer.party_id
       AND address_kind='registered' AND is_primary AND status='active' AND valid_from<=invoice_date
       AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
    END IF;
    SELECT * INTO STRICT shipping FROM parties.addresses
     WHERE org_id=organization_id AND id=delivery_address_id
       AND party_id=customer.party_id
       AND address_kind IN ('registered','billing','shipping') AND status='active'
       AND row_version=delivery_address_row_version
       AND valid_from<=invoice_date AND (valid_until IS NULL OR valid_until>=invoice_date)
     FOR SHARE;
    place_of_supply:=shipping.state_code;
    IF billing.country_code<>'IN' OR shipping.country_code<>'IN' THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='export sales invoices remain fail-closed in the pilot'; END IF;
    SELECT count(*) INTO registration_count FROM parties.tax_registrations
     WHERE org_id=organization_id AND party_id=customer.party_id AND registration_type='GSTIN'
       AND state_code=place_of_supply
       AND status='active' AND (valid_from IS NULL OR valid_from<=invoice_date)
       AND (valid_until IS NULL OR valid_until>=invoice_date);
    IF registration_count>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='customer GST registration is ambiguous';
    ELSIF registration_count=1 THEN
      SELECT * INTO STRICT customer_registration FROM parties.tax_registrations
       WHERE org_id=organization_id AND party_id=customer.party_id AND registration_type='GSTIN'
         AND state_code=place_of_supply
         AND status='active' AND (valid_from IS NULL OR valid_from<=invoice_date)
         AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
    END IF;
    supply_type:=CASE WHEN registration_count=1 AND customer_registration.taxpayer_type IN ('sez_unit','sez_developer')
      THEN 'sez' WHEN seller_registration.state_code=place_of_supply THEN 'intra_state' ELSE 'inter_state' END;
    IF place_of_supply<>shipping.state_code
       OR (supply_type='sez' AND (zero_mode<>'with_igst' OR customer_registration.state_code<>place_of_supply))
       OR (supply_type<>'sez' AND zero_mode<>'not_applicable') THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='place of supply or zero-rated mode lacks exact supported legal evidence'; END IF;
     SELECT * INTO STRICT revenue_account FROM finance.accounts AS resolved_revenue_account
      WHERE resolved_revenue_account.org_id=organization_id
        AND resolved_revenue_account.id=erp_commercial_commands.resolve_role_account(
          organization_id,branch_id,'sales_revenue','income','INR',false) FOR SHARE;
    IF has_direct THEN
      SELECT * INTO STRICT location FROM inventory.locations
       WHERE org_id=organization_id AND id=from_location_id AND branch_id=branch_id
         AND status='active' AND allows_sale FOR SHARE;
      IF branch.postal_code!~'^[0-9]{6}$' OR shipping.postal_code!~'^[0-9]{6}$' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='direct invoice requires exact Indian origin and destination pincodes'; END IF;
      IF transporter_party_id IS NOT NULL THEN
        SELECT * INTO STRICT transporter FROM parties.parties
         WHERE org_id=organization_id AND id=transporter_party_id AND status='active' FOR SHARE;
        SELECT count(*) INTO registration_count FROM parties.tax_registrations
         WHERE org_id=organization_id AND party_id=transporter.id AND registration_type='GSTIN'
           AND status='active' AND (valid_from IS NULL OR valid_from<=invoice_date)
           AND (valid_until IS NULL OR valid_until>=invoice_date);
        IF registration_count>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='transporter GST registration is ambiguous';
        ELSIF registration_count=1 THEN
          SELECT * INTO STRICT transporter_registration FROM parties.tax_registrations
           WHERE org_id=organization_id AND party_id=transporter.id AND registration_type='GSTIN'
             AND status='active' AND (valid_from IS NULL OR valid_from<=invoice_date)
             AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
        END IF;
      END IF;
    END IF;
    source_versions:=source_versions||pg_catalog.jsonb_build_array(
      pg_catalog.jsonb_build_object('resource_type','organization','id',organization.id,'row_version',organization.row_version),
      pg_catalog.jsonb_build_object('resource_type','branch','id',branch.id,'row_version',branch.row_version),
      pg_catalog.jsonb_build_object('resource_type','seller_tax_registration','id',seller_registration.id,'row_version',seller_registration.row_version,'effective_from',seller_registration.effective_from,'effective_to',seller_registration.effective_to),
      pg_catalog.jsonb_build_object('resource_type','seller_registration_branch','registration_id',seller_registration_branch.registration_id,'branch_id',seller_registration_branch.branch_id,'status',seller_registration_branch.status,'effective_from',seller_registration_branch.effective_from,'effective_to',seller_registration_branch.effective_to),
      pg_catalog.jsonb_build_object('resource_type','customer_account','id',customer.id,'row_version',customer.row_version),
      pg_catalog.jsonb_build_object('resource_type','customer_party','id',customer_party.id,'row_version',customer_party.row_version),
      pg_catalog.jsonb_build_object('resource_type','billing_address','id',billing.id,'row_version',billing.row_version,'valid_from',billing.valid_from,'valid_until',billing.valid_until),
      pg_catalog.jsonb_build_object('resource_type','shipping_address','id',shipping.id,'row_version',shipping.row_version,'valid_from',shipping.valid_from,'valid_until',shipping.valid_until),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','sales_revenue','id',revenue_account.id,'row_version',revenue_account.row_version)
    );
    IF customer_registration.id IS NOT NULL THEN
      source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'resource_type','customer_tax_registration','id',customer_registration.id,'row_version',customer_registration.row_version,
        'taxpayer_type',customer_registration.taxpayer_type,'valid_from',customer_registration.valid_from,'valid_until',customer_registration.valid_until));
    END IF;
    IF has_direct THEN
      source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'resource_type','inventory_location','id',location.id,'row_version',location.row_version,'allows_sale',location.allows_sale));
      IF transporter.id IS NOT NULL THEN source_versions:=source_versions||pg_catalog.jsonb_build_array(
        pg_catalog.jsonb_build_object('resource_type','transporter_party','id',transporter.id,'row_version',transporter.row_version)); END IF;
      IF transporter_registration.id IS NOT NULL THEN source_versions:=source_versions||pg_catalog.jsonb_build_array(
        pg_catalog.jsonb_build_object('resource_type','transporter_gstin','id',transporter_registration.id,'row_version',transporter_registration.row_version,'registration_number',transporter_registration.registration_number)); END IF;
    END IF;

    FOR requested_line IN SELECT value FROM pg_catalog.jsonb_array_elements(request_document->'lines') LOOP
      billed:=NULLIF(requested_line->>'billed_quantity','')::numeric;
      free:=NULLIF(requested_line->>'free_quantity','')::numeric;
      IF billed<0 OR free<0 OR billed+free<=0 OR NULLIF(requested_line->>'line_id','')::uuid IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='invoice product line quantities are invalid'; END IF;
      SELECT * INTO STRICT product FROM catalog.products WHERE org_id=organization_id
       AND id=NULLIF(requested_line->>'product_id','')::uuid AND status='active' FOR SHARE;
      SELECT * INTO STRICT conversion FROM catalog.uom_conversions WHERE org_id=organization_id
       AND id=NULLIF(requested_line->>'uom_conversion_id','')::uuid AND product_id=product.id
       AND status='active' AND to_uom_code=product.base_uom_code AND valid_from<=invoice_date
       AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_version FROM tax.tax_code_versions WHERE code=product.hsn_code
       AND code_kind='hsn' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_release FROM core.reference_data_releases WHERE id=tax_version.release_id
       AND dataset_kind='hsn_sac_tax' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      IF ruleset_version IS NULL THEN ruleset_version:=tax_version.ruleset_version;
      ELSIF ruleset_version<>tax_version.ruleset_version THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice tax lines resolve to different ruleset versions'; END IF;
      base_billed:=pg_catalog.round(billed*conversion.multiplier,6);
      base_free:=pg_catalog.round(free*conversion.multiplier,6);
      resolved_allocations:='[]'::jsonb; allocated_billed:=0; allocated_free:=0;
      order_line.id:=NULL;
      IF requested_line->>'fulfillment_source'='direct_issue' THEN
        allocation_mode:=COALESCE(NULLIF(requested_line->>'batch_allocation_mode',''),
          CASE WHEN requested_line->'batch_allocations' IS NULL THEN 'auto_fefo' ELSE 'explicit_fefo' END);
        IF allocation_mode NOT IN ('auto_fefo','explicit_fefo') THEN
          RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='direct invoice batch allocation mode is invalid';
        END IF;
        source_versions:=source_versions||pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_object('resource_type','invoice_batch_allocation_policy',
            'invoice_line_id',requested_line->>'line_id','mode',allocation_mode,
            'algorithm_version','sales_invoice_auto_fefo_v1','later_expiry_override_supported',false));
        IF allocation_mode='auto_fefo' THEN
          IF requested_line->'dispatch_allocations' IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='automatic FEFO invoice line cannot carry dispatch allocations'; END IF;
          auto_allocations:='[]'::jsonb;
          remaining_billed:=billed;
          remaining_free:=free;
          FOR eligible IN
            SELECT batch_row.id AS batch_id,batch_row.batch_number,batch_row.expires_on,
                   stock.on_hand_quantity-
                     coalesce((allocation_tracker#>>ARRAY[batch_row.id::text,'base_quantity'])::numeric,0)
                     AS on_hand_quantity
              FROM inventory.stock_balances stock
              JOIN inventory.batches batch_row ON batch_row.org_id=stock.org_id
               AND batch_row.id=stock.batch_id
             WHERE stock.org_id=organization_id AND stock.location_id=location.id
               AND stock.product_id=product.id
               AND stock.on_hand_quantity-
                     coalesce((allocation_tracker#>>ARRAY[batch_row.id::text,'base_quantity'])::numeric,0)>0
               AND batch_row.lot_kind='manufacturer_batch' AND batch_row.status='released'
               AND batch_row.released_at IS NOT NULL AND batch_row.expires_on IS NOT NULL
               AND invoice_date<batch_row.expires_on
             ORDER BY batch_row.expires_on,batch_row.batch_number,batch_row.id
             FOR SHARE OF stock,batch_row
          LOOP
            available_entered:=pg_catalog.trunc(eligible.on_hand_quantity/conversion.multiplier,6);
            candidate_billed:=LEAST(remaining_billed,available_entered);
            available_entered:=available_entered-candidate_billed;
            candidate_free:=LEAST(remaining_free,available_entered);
            IF candidate_billed+candidate_free>0 THEN
              auto_allocations:=auto_allocations||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
                'batch_id',eligible.batch_id,'billed_quantity',candidate_billed::text,
                'free_quantity',candidate_free::text));
              remaining_billed:=remaining_billed-candidate_billed;
              remaining_free:=remaining_free-candidate_free;
            END IF;
            EXIT WHEN remaining_billed=0 AND remaining_free=0;
          END LOOP;
          IF remaining_billed<>0 OR remaining_free<>0 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='automatic FEFO allocation cannot satisfy locked stock'; END IF;
          IF requested_line->'batch_allocations' IS NULL THEN
            requested_line:=pg_catalog.jsonb_set(requested_line,'{batch_allocations}',auto_allocations,true);
          ELSIF pg_catalog.jsonb_typeof(requested_line->'batch_allocations')<>'array'
             OR pg_catalog.jsonb_array_length(requested_line->'batch_allocations')<>pg_catalog.jsonb_array_length(auto_allocations)
             OR EXISTS (
               WITH expected AS (
                 SELECT value,ordinality FROM pg_catalog.jsonb_array_elements(auto_allocations) WITH ORDINALITY item(value,ordinality)
               ), supplied AS (
                 SELECT value,ordinality FROM pg_catalog.jsonb_array_elements(requested_line->'batch_allocations') WITH ORDINALITY item(value,ordinality)
               )
               SELECT 1 FROM expected FULL JOIN supplied USING(ordinality)
                WHERE ROW(expected.value->>'batch_id',expected.value->>'billed_quantity',expected.value->>'free_quantity')
                  IS DISTINCT FROM ROW(supplied.value->>'batch_id',supplied.value->>'billed_quantity',supplied.value->>'free_quantity')
             ) THEN
            RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='automatic FEFO allocation changed before persistence';
          END IF;
        END IF;
        IF pg_catalog.jsonb_typeof(requested_line->'batch_allocations')<>'array'
           OR pg_catalog.jsonb_array_length(requested_line->'batch_allocations')<1
           OR requested_line->'dispatch_allocations' IS NOT NULL
           OR (SELECT count(DISTINCT value->>'batch_id') FROM pg_catalog.jsonb_array_elements(requested_line->'batch_allocations'))
              <>pg_catalog.jsonb_array_length(requested_line->'batch_allocations') THEN
          RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='direct invoice batch allocations are invalid'; END IF;
        FOR requested_allocation IN SELECT value FROM pg_catalog.jsonb_array_elements(requested_line->'batch_allocations') LOOP
          allocation_billed:=NULLIF(requested_allocation->>'billed_quantity','')::numeric;
          allocation_free:=NULLIF(requested_allocation->>'free_quantity','')::numeric;
          IF allocation_billed<0 OR allocation_free<0 OR allocation_billed+allocation_free<=0
             OR (allocation_mode='explicit_fefo'
                 AND NULLIF(requested_allocation->>'inventory_line_id','')::uuid IS NULL) THEN
            RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='direct invoice batch allocation is invalid'; END IF;
          SELECT * INTO STRICT batch FROM inventory.batches WHERE org_id=organization_id
           AND id=NULLIF(requested_allocation->>'batch_id','')::uuid AND product_id=product.id
           AND lot_kind='manufacturer_batch' AND status='released' AND released_at IS NOT NULL
           AND expires_on IS NOT NULL AND invoice_date<expires_on FOR SHARE;
          SELECT * INTO STRICT balance FROM inventory.stock_balances WHERE org_id=organization_id
           AND location_id=location.id AND product_id=product.id AND batch_id=batch.id FOR SHARE;
          prior_base:=coalesce((allocation_tracker#>>ARRAY[batch.id::text,'base_quantity'])::numeric,0);
          prior_value:=coalesce((allocation_tracker#>>ARRAY[batch.id::text,'issued_value'])::numeric,0);
          current_quantity:=balance.on_hand_quantity-prior_base;
          current_value:=balance.inventory_value-prior_value;
          current_unit_cost:=CASE WHEN current_quantity=0 THEN 0 ELSE pg_catalog.round(current_value/current_quantity,4) END;
          IF pg_catalog.round((allocation_billed+allocation_free)*conversion.multiplier,6)>current_quantity THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='direct invoice batch allocation exceeds locked stock'; END IF;
          extended_cost:=CASE WHEN pg_catalog.round((allocation_billed+allocation_free)*conversion.multiplier,6)=current_quantity
            THEN current_value ELSE pg_catalog.round(pg_catalog.round((allocation_billed+allocation_free)*conversion.multiplier,6)*current_unit_cost,2) END;
          allocation_tracker:=pg_catalog.jsonb_set(allocation_tracker,ARRAY[batch.id::text],pg_catalog.jsonb_build_object(
            'base_quantity',(prior_base+pg_catalog.round((allocation_billed+allocation_free)*conversion.multiplier,6))::text,
            'issued_value',(prior_value+extended_cost)::text),true);
          line_number:=line_number+1;
          resolved_allocations:=resolved_allocations||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
            'line_number',line_number,'inventory_line_id',requested_allocation->>'inventory_line_id','batch_id',batch.id,
            'batch_number',batch.batch_number,'batch_row_version',batch.row_version,'expires_on',batch.expires_on,
            'billed_quantity',allocation_billed::text,'free_quantity',allocation_free::text,
            'base_billed_quantity',pg_catalog.round(allocation_billed*conversion.multiplier,6)::text,
            'base_free_quantity',pg_catalog.round(allocation_free*conversion.multiplier,6)::text,
            'stock_balance_row_version',balance.row_version,'on_hand_quantity',balance.on_hand_quantity::text,
            'inventory_value',balance.inventory_value::text,'unit_cost',current_unit_cost::text,'extended_cost',extended_cost::text));
          source_versions:=source_versions||pg_catalog.jsonb_build_array(
            pg_catalog.jsonb_build_object('resource_type','manufacturer_batch','id',batch.id,'row_version',batch.row_version,'product_id',batch.product_id,'expires_on',batch.expires_on,'status',batch.status),
            pg_catalog.jsonb_build_object('resource_type','stock_balance','location_id',balance.location_id,'product_id',balance.product_id,'batch_id',balance.batch_id,'row_version',balance.row_version,'on_hand_quantity',balance.on_hand_quantity::text,'inventory_value',balance.inventory_value::text,'average_unit_cost',balance.average_unit_cost::text));
          allocated_billed:=allocated_billed+allocation_billed; allocated_free:=allocated_free+allocation_free;
          total_base:=total_base+pg_catalog.round((allocation_billed+allocation_free)*conversion.multiplier,6);
          total_value:=total_value+extended_cost;
        END LOOP;
        IF allocated_billed IS DISTINCT FROM billed OR allocated_free IS DISTINCT FROM free THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='direct invoice batches do not reconcile billed and free quantities separately'; END IF;
      ELSE
        IF pg_catalog.jsonb_typeof(requested_line->'dispatch_allocations')<>'array'
           OR pg_catalog.jsonb_array_length(requested_line->'dispatch_allocations')<1
           OR requested_line->'batch_allocations' IS NOT NULL
           OR (SELECT count(DISTINCT value->>'dispatch_line_id') FROM pg_catalog.jsonb_array_elements(requested_line->'dispatch_allocations'))
              <>pg_catalog.jsonb_array_length(requested_line->'dispatch_allocations') THEN
          RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='invoice dispatch allocations are invalid'; END IF;
        FOR requested_allocation IN SELECT value FROM pg_catalog.jsonb_array_elements(requested_line->'dispatch_allocations') LOOP
          allocation_billed:=NULLIF(requested_allocation->>'allocated_base_billed_quantity','')::numeric;
          allocation_free:=NULLIF(requested_allocation->>'allocated_base_free_quantity','')::numeric;
          IF allocation_billed<0 OR allocation_free<0 OR allocation_billed+allocation_free<=0
             OR NULLIF(requested_allocation->>'invoice_dispatch_allocation_id','')::uuid IS NULL THEN
            RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='invoice dispatch allocation quantity is invalid'; END IF;
          SELECT * INTO STRICT dispatch_line FROM sales.dispatch_lines WHERE org_id=organization_id
           AND id=NULLIF(requested_allocation->>'dispatch_line_id','')::uuid FOR SHARE;
          SELECT * INTO STRICT dispatch_header FROM sales.dispatches WHERE org_id=organization_id
           AND id=dispatch_line.dispatch_id AND status='posted' AND branch_id=branch_id
           AND customer_account_id=customer.id AND shipping_address_id=shipping.id FOR SHARE;
          IF order_line.id IS NULL THEN
            SELECT * INTO STRICT order_line FROM sales.order_lines WHERE org_id=organization_id
             AND id=dispatch_line.order_line_id AND line_kind='product' FOR SHARE;
          ELSIF order_line.id IS DISTINCT FROM dispatch_line.order_line_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='one invoice line cannot combine different approved order lines'; END IF;
          IF ROW(dispatch_line.product_id,order_line.product_id,order_line.uom_code,order_line.uom_conversion_factor,
                 order_line.quoted_unit_rate,order_line.price_basis,order_line.free_supply_tax_treatment,order_line.tax_code_version_id)
             IS DISTINCT FROM ROW(product.id,product.id,conversion.from_uom_code,conversion.multiplier,
                 (requested_line->>'quoted_unit_rate')::numeric,requested_line->>'price_basis',
                 requested_line->>'free_supply_tax_treatment',tax_version.id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='dispatch invoice terms differ from the approved source order line'; END IF;
          SELECT coalesce(sum(allocation.allocated_base_billed_quantity),0),coalesce(sum(allocation.allocated_base_free_quantity),0)
            INTO existing_billed,existing_free FROM sales.invoice_dispatch_allocations allocation
            JOIN sales.invoice_lines invoice_line ON invoice_line.org_id=allocation.org_id AND invoice_line.id=allocation.invoice_line_id
           WHERE allocation.org_id=organization_id AND allocation.dispatch_line_id=dispatch_line.id
             AND invoice_line.invoice_id<>invoice_id;
          prior_base:=coalesce((dispatch_tracker#>>ARRAY[dispatch_line.id::text,'billed'])::numeric,0);
          prior_value:=coalesce((dispatch_tracker#>>ARRAY[dispatch_line.id::text,'free'])::numeric,0);
          IF existing_billed+prior_base+allocation_billed>dispatch_line.base_billed_quantity
             OR existing_free+prior_value+allocation_free>dispatch_line.base_free_quantity THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice exceeds separate dispatch billed or free ceiling'; END IF;
          dispatch_tracker:=pg_catalog.jsonb_set(dispatch_tracker,ARRAY[dispatch_line.id::text],
            pg_catalog.jsonb_build_object('billed',(prior_base+allocation_billed)::text,'free',(prior_value+allocation_free)::text),true);
          IF (SELECT count(*) FROM (
            SELECT 1 FROM inventory.inventory_document_lines issue_line
            JOIN inventory.inventory_documents issue ON issue.org_id=issue_line.org_id
             AND issue.id=issue_line.inventory_document_id AND issue.sales_dispatch_id=dispatch_header.id
             AND issue.status='posted' AND issue.document_type='sales_issue'
            JOIN finance.accounting_events valuation ON valuation.org_id=issue.org_id
             AND valuation.inventory_document_id=issue.id AND valuation.event_type='inventory_valuation'
           WHERE issue_line.org_id=organization_id AND issue_line.sales_dispatch_line_id=dispatch_line.id
             AND ROW(issue_line.product_id,issue_line.batch_id,issue_line.uom_code)
                 IS NOT DISTINCT FROM ROW(dispatch_line.product_id,dispatch_line.batch_id,dispatch_line.uom_code)
          ) posted_lineage)<>1 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='dispatch invoice allocation lacks posted stock and valuation lineage'; END IF;
          line_number:=line_number+1;
          resolved_allocations:=resolved_allocations||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
            'line_number',line_number,'invoice_dispatch_allocation_id',requested_allocation->>'invoice_dispatch_allocation_id',
            'dispatch_line_id',dispatch_line.id,'dispatch_id',dispatch_header.id,'order_line_id',order_line.id,
            'allocated_base_billed_quantity',allocation_billed::text,'allocated_base_free_quantity',allocation_free::text));
          source_versions:=source_versions||pg_catalog.jsonb_build_array(
            pg_catalog.jsonb_build_object('resource_type','sales_dispatch','id',dispatch_header.id,'row_version',dispatch_header.row_version,'status',dispatch_header.status),
            pg_catalog.jsonb_build_object('resource_type','sales_dispatch_line','id',dispatch_line.id,'source_hash',pg_catalog.encode(extensions.digest(pg_catalog.convert_to(pg_catalog.to_jsonb(dispatch_line)::text,'UTF8'),'sha256'),'hex')),
            pg_catalog.jsonb_build_object('resource_type','sales_order_line','id',order_line.id,'source_hash',pg_catalog.encode(extensions.digest(pg_catalog.convert_to(pg_catalog.to_jsonb(order_line)::text,'UTF8'),'sha256'),'hex')));
          allocated_billed:=allocated_billed+allocation_billed; allocated_free:=allocated_free+allocation_free;
        END LOOP;
        IF allocated_billed IS DISTINCT FROM base_billed OR allocated_free IS DISTINCT FROM base_free THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice dispatch allocations do not reconcile base billed and free quantities separately'; END IF;
      END IF;
      resolved_line:=pg_catalog.jsonb_build_object(
        'line_number',pg_catalog.jsonb_array_length(resolved_lines)+1,'line_kind','product',
        'line_id',requested_line->>'line_id','product_id',product.id,'product_row_version',product.row_version,
        'hsn_code',product.hsn_code,'uom_conversion_id',conversion.id,'uom_code',conversion.from_uom_code,
        'to_uom_code',conversion.to_uom_code,'multiplier',conversion.multiplier::text,
        'uom_valid_from',conversion.valid_from,'uom_valid_until',conversion.valid_until,
        'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
        'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
        'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version,
        'taxability',CASE WHEN supply_type='sez' THEN 'zero_rated' ELSE tax_version.taxability END,
        'gst_rate',CASE WHEN supply_type='sez' OR tax_version.taxability='taxable' THEN tax_version.igst_rate::text ELSE '0' END,
        'cess_rate',CASE WHEN supply_type<>'sez' AND tax_version.taxability='taxable' THEN tax_version.cess_rate::text ELSE '0' END,
        'ruleset_version',tax_version.ruleset_version,'revenue_account_id',revenue_account.id,
        'order_line_id',order_line.id,'fulfillment_source',requested_line->>'fulfillment_source',
        'batch_allocation_mode',CASE WHEN requested_line->>'fulfillment_source'='direct_issue' THEN allocation_mode END,
        CASE WHEN requested_line->>'fulfillment_source'='direct_issue' THEN 'batch_allocations' ELSE 'dispatch_allocations' END,
        resolved_allocations,'input',requested_line);
      resolved_lines:=resolved_lines||pg_catalog.jsonb_build_array(resolved_line);
      source_versions:=source_versions||pg_catalog.jsonb_build_array(
        pg_catalog.jsonb_build_object('resource_type','product','id',product.id,'row_version',product.row_version,
          'uom_conversion_id',conversion.id,'uom_valid_from',conversion.valid_from,'uom_valid_until',conversion.valid_until,
          'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
          'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
          'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version));
    END LOOP;
    FOR requested_line IN SELECT value FROM pg_catalog.jsonb_array_elements(COALESCE(request_document->'charge_lines','[]'::jsonb)) LOOP
      SELECT * INTO STRICT profile FROM catalog.commercial_charge_tax_profiles WHERE org_id=organization_id
       AND direction='sales' AND charge_code=requested_line->>'charge_code' AND status='active'
       AND effective_from<=invoice_date AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_version FROM tax.tax_code_versions WHERE id=profile.tax_code_version_id
       AND code_kind='sac' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_release FROM core.reference_data_releases WHERE id=tax_version.release_id
       AND dataset_kind='hsn_sac_tax' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      IF ruleset_version IS NULL THEN ruleset_version:=tax_version.ruleset_version;
      ELSIF ruleset_version<>tax_version.ruleset_version THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice charge resolves to a different ruleset version'; END IF;
      resolved_lines:=resolved_lines||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'line_number',pg_catalog.jsonb_array_length(resolved_lines)+1,'line_kind','charge','line_id',requested_line->>'line_id',
        'charge_code',profile.charge_code,'charge_tax_profile_id',profile.id,'charge_tax_profile_row_version',profile.row_version,
        'charge_tax_profile_effective_from',profile.effective_from,'charge_tax_profile_effective_to',profile.effective_to,
        'sac_code',tax_version.code,'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
        'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
        'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version,
        'taxability',CASE WHEN supply_type='sez' THEN 'zero_rated' ELSE tax_version.taxability END,
        'gst_rate',CASE WHEN supply_type='sez' OR tax_version.taxability='taxable' THEN tax_version.igst_rate::text ELSE '0' END,
        'cess_rate',CASE WHEN supply_type<>'sez' AND tax_version.taxability='taxable' THEN tax_version.cess_rate::text ELSE '0' END,
        'ruleset_version',tax_version.ruleset_version,'revenue_account_id',revenue_account.id,'input',requested_line));
      source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'resource_type','commercial_charge_tax_profile','id',profile.id,'row_version',profile.row_version,
        'charge_code',profile.charge_code,'effective_from',profile.effective_from,'effective_to',profile.effective_to,
        'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
        'tax_effective_from',tax_version.effective_from,'tax_effective_to',tax_version.effective_to,
        'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version));
    END LOOP;
    IF ruleset_version IS NULL THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invoice has no effective tax ruleset'; END IF;
    IF has_direct THEN
      WITH requested AS (
        SELECT (line.value->>'product_id')::uuid product_id,(allocation.value->>'batch_id')::uuid batch_id,
          sum(pg_catalog.round(((allocation.value->>'billed_quantity')::numeric+(allocation.value->>'free_quantity')::numeric)*conversion.multiplier,6)) requested_base
        FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
        JOIN catalog.uom_conversions conversion ON conversion.org_id=organization_id AND conversion.id=(line.value->>'uom_conversion_id')::uuid
        CROSS JOIN LATERAL pg_catalog.jsonb_array_elements(COALESCE(line.value->'batch_allocations','[]'::jsonb)) allocation(value)
        WHERE line.value->>'fulfillment_source'='direct_issue'
        GROUP BY (line.value->>'product_id')::uuid,(allocation.value->>'batch_id')::uuid
      ), totals AS (SELECT product_id,sum(requested_base) requested_base FROM requested GROUP BY product_id),
      /* sales_invoice_fefo_expiry_date_equivalence_v1 */
      eligible_lots AS (
        SELECT stock.product_id,stock.batch_id,stock.on_hand_quantity,batch_row.expires_on
        FROM inventory.stock_balances stock JOIN inventory.batches batch_row ON batch_row.org_id=stock.org_id AND batch_row.id=stock.batch_id
        JOIN totals ON totals.product_id=stock.product_id WHERE stock.org_id=organization_id AND stock.location_id=from_location_id
          AND stock.on_hand_quantity>0 AND batch_row.lot_kind='manufacturer_batch' AND batch_row.status='released'
          AND batch_row.released_at IS NOT NULL AND batch_row.expires_on IS NOT NULL AND invoice_date<batch_row.expires_on),
      expiry_groups AS (
        SELECT eligible_lot.product_id,eligible_lot.expires_on,
          sum(eligible_lot.on_hand_quantity) expiry_available,
          coalesce(sum(requested.requested_base),0) expiry_requested
        FROM eligible_lots eligible_lot
        LEFT JOIN requested ON requested.product_id=eligible_lot.product_id AND requested.batch_id=eligible_lot.batch_id
        GROUP BY eligible_lot.product_id,eligible_lot.expires_on),
      eligible AS (
        SELECT expiry_group.product_id,expiry_group.expires_on,
          expiry_group.expiry_available,expiry_group.expiry_requested,
          coalesce(sum(expiry_group.expiry_available) OVER (
            PARTITION BY expiry_group.product_id ORDER BY expiry_group.expires_on
            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),0) prior_available
        FROM expiry_groups expiry_group)
      SELECT count(*) INTO bad_count FROM eligible JOIN totals USING(product_id)
       WHERE eligible.expiry_requested IS DISTINCT FROM
         greatest(least(totals.requested_base-eligible.prior_available,eligible.expiry_available),0);
      IF bad_count<>0 THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='direct invoice batches do not follow FEFO'; END IF;
    END IF;
    RETURN pg_catalog.jsonb_build_object(
      'branch_id',branch.id,'branch_row_version',branch.row_version,'invoice_date',invoice_date,
      'place_of_supply_state_code',place_of_supply,'supply_type',supply_type,'zero_rated_payment_mode',zero_mode,
      'tax_charge_mechanism','normal','customer_account_id',customer.id,'customer_account_row_version',customer.row_version,
      'customer_party_id',customer_party.id,'customer_party_row_version',customer_party.row_version,
      'seller_tax_registration_id',seller_registration.id,'seller_tax_registration_row_version',seller_registration.row_version,
      'customer_tax_registration_id',customer_registration.id,'customer_tax_registration_row_version',customer_registration.row_version,
      'customer_taxpayer_type',customer_registration.taxpayer_type,'billing_address_id',billing.id,'billing_address_row_version',billing.row_version,
      'shipping_address_id',shipping.id,'shipping_address_row_version',shipping.row_version,
      'revenue_account_id',revenue_account.id,'revenue_account_row_version',revenue_account.row_version,
      'from_location_id',location.id,'has_direct_issue',has_direct,'has_dispatch_allocated',has_allocated,
      'seller_legal_name',seller_registration.legal_name,'seller_gstin',seller_registration.gstin,
      'seller_address',pg_catalog.concat_ws(', ',branch.address_line1,branch.address_line2,branch.city,branch.state_code,branch.postal_code),
      'buyer_legal_name',COALESCE(customer_registration.registered_legal_name,customer_party.legal_name),'buyer_gstin',customer_registration.registration_number,
      'buyer_address',pg_catalog.concat_ws(', ',billing.line1,billing.line2,billing.city,billing.state_code,billing.postal_code),
      'origin',CASE WHEN has_direct THEN pg_catalog.jsonb_build_object('line1',branch.address_line1,'line2',branch.address_line2,'city',branch.city,'state_code',branch.state_code,'pincode',branch.postal_code) ELSE NULL END,
      'destination',CASE WHEN has_direct THEN pg_catalog.jsonb_build_object('line1',shipping.line1,'line2',shipping.line2,'city',shipping.city,'state_code',shipping.state_code,'pincode',shipping.postal_code) ELSE NULL END,
      'transport_mode',transport_mode,'distance_km',NULLIF(logistics->>'distance_km','')::numeric::text,
      'transporter_party_id',transporter.id,'transporter_name',transporter.legal_name,'transporter_gstin',transporter_registration.registration_number,
      'vehicle_number',NULLIF(logistics->>'vehicle_number',''),'vehicle_type',NULLIF(logistics->>'vehicle_type',''),
      'transport_document_number',NULLIF(logistics->>'transport_document_number',''),
      'transport_document_date',NULLIF(logistics->>'transport_document_date','')::date,
      'ruleset_version',ruleset_version,'lines',resolved_lines,
      'total_abs_base_quantity',total_base::text,'total_inventory_value',total_value::text,
      'legal_scope',pg_catalog.jsonb_build_object('country','IN','currency','INR','outward_rcm_supported',false,
        'export_supported',false,'sez_without_payment_supported',false,'sez_evidence_registration_id',customer_registration.id),
      'source_versions',source_versions);
END
$function$;
ALTER FUNCTION "erp_automation_commands"."resolve_sales_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, invoice_id uuid, request_document jsonb) OWNER TO "erp_migration_owner";
REVOKE ALL ON FUNCTION "erp_automation_commands"."resolve_sales_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, invoice_id uuid, request_document jsonb) FROM PUBLIC, "erp_app", "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."resolve_sales_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, invoice_id uuid, request_document jsonb) TO "erp_runtime";
GRANT EXECUTE ON FUNCTION "erp_automation_commands"."resolve_sales_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, invoice_id uuid, request_document jsonb) TO "erp_calculator";

RESET ROLE;
