-- Generated by backend/scripts/generate_supplier_invoice_transfer_lineage_migration.py.
-- Source owners: canonical trade-v2 and automation command generators.

SET LOCAL ROLE erp_migration_owner;

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_from_receipts"(p_org_id uuid, p_receipt_allocations jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE state jsonb;
        seed_bad_count bigint; malformed_transfer_count bigint;
        foreign_positive_count bigint; unlinked_transfer_count bigint;
        origin_collision_count bigint; balance_bad_count bigint;
        negative_prefix_count bigint; origin_quantity_bad_count bigint;
BEGIN
    IF p_org_id IS NULL OR pg_catalog.jsonb_typeof(p_receipt_allocations)<>'array'
       OR pg_catalog.jsonb_array_length(p_receipt_allocations)=0
       OR EXISTS (
         SELECT 1 FROM pg_catalog.jsonb_array_elements(p_receipt_allocations) AS allocation(value)
          WHERE NULLIF(allocation.value->>'goods_receipt_line_id','')::uuid IS NULL
             OR NULLIF(allocation.value->>'allocated_base_billed_quantity','')::numeric IS NULL
             OR NULLIF(allocation.value->>'allocated_base_free_quantity','')::numeric IS NULL
             OR NULLIF(allocation.value->>'allocated_base_billed_quantity','')::numeric<0
             OR NULLIF(allocation.value->>'allocated_base_free_quantity','')::numeric<0
             OR COALESCE((allocation.value->>'allocated_base_billed_quantity')::numeric,0)
                +COALESCE((allocation.value->>'allocated_base_free_quantity')::numeric,0)<=0
       ) OR (SELECT count(*) FROM pg_catalog.jsonb_array_elements(p_receipt_allocations))
              <>(SELECT count(DISTINCT value->>'goods_receipt_line_id')
                  FROM pg_catalog.jsonb_array_elements(p_receipt_allocations)) THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='landed-cost receipt lineage input is incomplete or duplicated';
    END IF;

    WITH RECURSIVE raw_seeds AS (
      SELECT receipt.id AS goods_receipt_line_id,
             receipt.goods_receipt_id,receipt.location_id,receipt.product_id,receipt.batch_id,
             receipt.uom_code,
             (requested.value->>'allocated_base_billed_quantity')::numeric AS allocated_billed_quantity,
             (requested.value->>'allocated_base_free_quantity')::numeric AS allocated_free_quantity,
             receipt.base_accepted_quantity AS receipt_billed_quantity,
             receipt.base_free_quantity AS receipt_free_quantity,
             (requested.value->>'allocated_base_billed_quantity')::numeric
               +(requested.value->>'allocated_base_free_quantity')::numeric AS allocated_quantity,
             receipt.base_accepted_quantity+receipt.base_free_quantity AS receipt_quantity,
             pg_catalog.round(
               ((requested.value->>'allocated_base_billed_quantity')::numeric
                 +(requested.value->>'allocated_base_free_quantity')::numeric)
               * receipt.unit_cost,2
             ) AS allocated_value
        FROM pg_catalog.jsonb_array_elements(p_receipt_allocations) AS requested(value)
        JOIN procurement.goods_receipt_lines AS receipt
          ON receipt.org_id=p_org_id
         AND receipt.id=(requested.value->>'goods_receipt_line_id')::uuid
    ), receipt_evidence AS (
      SELECT seed.*,evidence.evidence_count,evidence.exact_count,evidence.receipt_posted_at
        FROM raw_seeds AS seed
        LEFT JOIN LATERAL (
          SELECT count(*) AS evidence_count,
                 count(*) FILTER (WHERE document.status='posted'
                    AND document.document_type='purchase_receipt'
                    AND document.goods_receipt_id=seed.goods_receipt_id
                    AND document_line.movement_kind='receipt'
                    AND document_line.product_id=seed.product_id
                    AND document_line.batch_id=seed.batch_id
                    AND document_line.to_location_id=seed.location_id
                    AND document_line.from_location_id IS NULL
                    AND document_line.base_quantity=seed.receipt_quantity
                    AND entry.entry_kind='receipt'
                    AND entry.location_id=seed.location_id
                    AND entry.product_id=seed.product_id
                    AND entry.batch_id=seed.batch_id
                    AND entry.quantity_delta=seed.receipt_quantity
                    AND entry.value_delta=document_line.extended_cost) AS exact_count,
                 max(entry.posted_at) AS receipt_posted_at
            FROM inventory.inventory_document_lines AS document_line
            JOIN inventory.inventory_documents AS document
              ON document.org_id=document_line.org_id AND document.id=document_line.inventory_document_id
            JOIN inventory.stock_ledger_entries AS entry
              ON entry.org_id=document_line.org_id AND entry.inventory_document_line_id=document_line.id
           WHERE document_line.org_id=p_org_id
             AND document_line.goods_receipt_line_id=seed.goods_receipt_line_id
        ) AS evidence ON true
    ), seed_groups AS (
      SELECT location_id AS origin_location_id,product_id AS origin_product_id,batch_id AS origin_batch_id,
             min(uom_code) AS uom_code,sum(allocated_quantity) AS allocated_quantity,
             sum(allocated_value) AS allocated_value,
             bool_and(allocated_billed_quantity=receipt_billed_quantity
               AND allocated_free_quantity=receipt_free_quantity
               AND allocated_quantity=receipt_quantity) AS fully_allocated_receipt,
             bool_and(evidence_count=1 AND exact_count=1 AND receipt_posted_at IS NOT NULL) AS exact_receipt_evidence,
             max(receipt_posted_at) AS arrived_at,
             array_agg(goods_receipt_line_id ORDER BY goods_receipt_line_id) AS goods_receipt_line_ids
        FROM receipt_evidence
       GROUP BY location_id,product_id,batch_id
    ), transfer_pairs AS (
      SELECT line.id AS transfer_line_id,line.from_location_id,line.to_location_id,
             line.product_id,line.batch_id,line.base_quantity,line.extended_cost,
             max(entry.posted_at) AS posted_at,
             count(entry.id) AS ledger_count,
             count(entry.id) FILTER (WHERE entry.entry_kind='transfer_out') AS transfer_out_count,
             count(entry.id) FILTER (WHERE entry.entry_kind='transfer_in') AS transfer_in_count,
             COALESCE(bool_and(
               entry.product_id=line.product_id AND entry.batch_id=line.batch_id
               AND ((entry.entry_kind='transfer_out' AND entry.location_id=line.from_location_id
                     AND entry.quantity_delta=-line.base_quantity AND entry.value_delta=-line.extended_cost)
                 OR (entry.entry_kind='transfer_in' AND entry.location_id=line.to_location_id
                     AND entry.quantity_delta=line.base_quantity AND entry.value_delta=line.extended_cost))
             ),false) AS entries_exact,
             COALESCE(sum(entry.quantity_delta),0) AS quantity_net,
             COALESCE(sum(entry.value_delta),0) AS value_net
        FROM inventory.inventory_document_lines AS line
        JOIN inventory.inventory_documents AS document
          ON document.org_id=line.org_id AND document.id=line.inventory_document_id
        LEFT JOIN inventory.stock_ledger_entries AS entry
          ON entry.org_id=line.org_id AND entry.inventory_document_line_id=line.id
       WHERE line.org_id=p_org_id AND line.movement_kind='transfer'
         AND document.document_type='transfer' AND document.status='posted'
       GROUP BY line.id,line.from_location_id,line.to_location_id,
                line.product_id,line.batch_id,line.base_quantity,line.extended_cost
    ), exact_transfers AS (
      SELECT pair.* FROM transfer_pairs AS pair
       WHERE pair.from_location_id IS NOT NULL AND pair.to_location_id IS NOT NULL
         AND pair.from_location_id<>pair.to_location_id
         AND pair.base_quantity>0 AND pair.extended_cost>=0
         AND pair.ledger_count=2 AND pair.transfer_out_count=1 AND pair.transfer_in_count=1
         AND pair.entries_exact AND pair.quantity_net=0 AND pair.value_net=0
         AND pair.posted_at IS NOT NULL
    ), arrivals(
      origin_location_id,origin_product_id,origin_batch_id,location_id,product_id,batch_id,arrived_at
    ) AS (
      SELECT origin_location_id,origin_product_id,origin_batch_id,
             origin_location_id,origin_product_id,origin_batch_id,arrived_at
        FROM seed_groups
       WHERE fully_allocated_receipt AND exact_receipt_evidence
      UNION
      SELECT arrival.origin_location_id,arrival.origin_product_id,arrival.origin_batch_id,
             transfer.to_location_id,transfer.product_id,transfer.batch_id,transfer.posted_at
        FROM arrivals AS arrival
        JOIN exact_transfers AS transfer
          ON transfer.from_location_id=arrival.location_id
         AND transfer.product_id=arrival.product_id AND transfer.batch_id=arrival.batch_id
         AND transfer.posted_at>=arrival.arrived_at
    ), lineage_transfers AS (
      SELECT DISTINCT transfer.transfer_line_id
        FROM exact_transfers AS transfer
        JOIN arrivals AS arrival
          ON transfer.from_location_id=arrival.location_id
         AND transfer.product_id=arrival.product_id AND transfer.batch_id=arrival.batch_id
         AND transfer.posted_at>=arrival.arrived_at
    ), origin_targets AS (
      SELECT DISTINCT origin_location_id,origin_product_id,origin_batch_id,
             location_id,product_id,batch_id
        FROM arrivals
    ), targets AS (
      SELECT target.location_id,target.product_id,target.batch_id,
             count(*) AS origin_count,
             (array_agg(target.origin_location_id ORDER BY target.origin_location_id,
                        target.origin_product_id,target.origin_batch_id))[1] AS origin_location_id,
             (array_agg(target.origin_product_id ORDER BY target.origin_location_id,
                        target.origin_product_id,target.origin_batch_id))[1] AS origin_product_id,
             (array_agg(target.origin_batch_id ORDER BY target.origin_location_id,
                        target.origin_product_id,target.origin_batch_id))[1] AS origin_batch_id
        FROM origin_targets AS target
       GROUP BY target.location_id,target.product_id,target.batch_id
    ), allowed_receipt_entries AS (
      SELECT DISTINCT entry.id
        FROM receipt_evidence AS seed
        JOIN inventory.inventory_document_lines AS line
          ON line.org_id=p_org_id AND line.goods_receipt_line_id=seed.goods_receipt_line_id
        JOIN inventory.stock_ledger_entries AS entry
          ON entry.org_id=line.org_id AND entry.inventory_document_line_id=line.id
       WHERE seed.evidence_count=1 AND seed.exact_count=1 AND entry.entry_kind='receipt'
    ), reachable_events AS (
      SELECT entry.*,
             sum(entry.quantity_delta) OVER (
               PARTITION BY entry.location_id,entry.product_id,entry.batch_id
               ORDER BY entry.posted_at,entry.created_at,entry.id
               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
             ) AS running_quantity
        FROM inventory.stock_ledger_entries AS entry
        JOIN targets AS target
          ON target.location_id=entry.location_id AND target.product_id=entry.product_id
         AND target.batch_id=entry.batch_id
       WHERE entry.org_id=p_org_id
    ), origin_remaining AS (
      SELECT target.origin_location_id,target.origin_product_id,target.origin_batch_id,
             sum(COALESCE(balance.on_hand_quantity,0)) AS remaining_quantity
        FROM targets AS target
        LEFT JOIN inventory.stock_balances AS balance
          ON balance.org_id=p_org_id AND balance.location_id=target.location_id
         AND balance.product_id=target.product_id AND balance.batch_id=target.batch_id
       WHERE target.origin_count=1
       GROUP BY target.origin_location_id,target.origin_product_id,target.origin_batch_id
    ), target_rows AS (
      SELECT target.location_id,balance.branch_id,target.product_id,target.batch_id,seed.uom_code,
             balance.on_hand_quantity,balance.inventory_value,balance.average_unit_cost,
             balance.row_version AS stock_row_version,balance.last_ledger_entry_id,
             target.origin_location_id,target.origin_product_id,target.origin_batch_id,
             seed.allocated_quantity AS origin_allocated_quantity,
             seed.allocated_value AS origin_allocated_value
        FROM targets AS target
        JOIN seed_groups AS seed
          ON seed.origin_location_id=target.origin_location_id
         AND seed.origin_product_id=target.origin_product_id
         AND seed.origin_batch_id=target.origin_batch_id
        JOIN inventory.stock_balances AS balance
          ON balance.org_id=p_org_id AND balance.location_id=target.location_id
         AND balance.product_id=target.product_id AND balance.batch_id=target.batch_id
       WHERE target.origin_count=1 AND balance.on_hand_quantity>0
    )
    SELECT
      (SELECT count(*) FROM seed_groups
        WHERE fully_allocated_receipt IS DISTINCT FROM true OR exact_receipt_evidence IS DISTINCT FROM true),
      (SELECT count(*) FROM transfer_pairs AS transfer
        JOIN arrivals AS arrival ON transfer.from_location_id=arrival.location_id
         AND transfer.product_id=arrival.product_id AND transfer.batch_id=arrival.batch_id
         AND transfer.posted_at>=arrival.arrived_at
       WHERE NOT (transfer.ledger_count=2 AND transfer.transfer_out_count=1 AND transfer.transfer_in_count=1
         AND transfer.entries_exact AND transfer.quantity_net=0 AND transfer.value_net=0)),
      (SELECT count(*) FROM reachable_events AS event
       WHERE event.quantity_delta>0
         AND NOT EXISTS (SELECT 1 FROM allowed_receipt_entries allowed WHERE allowed.id=event.id)
         AND NOT (event.entry_kind='transfer_in' AND EXISTS (
           SELECT 1 FROM lineage_transfers linked WHERE linked.transfer_line_id=event.inventory_document_line_id))),
      (SELECT count(*) FROM reachable_events AS event
       WHERE event.entry_kind='transfer_out' AND NOT EXISTS (
         SELECT 1 FROM lineage_transfers linked WHERE linked.transfer_line_id=event.inventory_document_line_id)),
      (SELECT count(*) FROM targets WHERE origin_count<>1),
      (SELECT count(*) FROM targets AS target
        LEFT JOIN inventory.stock_balances AS balance
          ON balance.org_id=p_org_id AND balance.location_id=target.location_id
         AND balance.product_id=target.product_id AND balance.batch_id=target.batch_id
       WHERE balance.location_id IS NULL OR balance.on_hand_quantity<0 OR balance.inventory_value<0
          OR balance.on_hand_quantity IS DISTINCT FROM (
            SELECT COALESCE(sum(entry.quantity_delta),0) FROM inventory.stock_ledger_entries AS entry
             WHERE entry.org_id=p_org_id AND entry.location_id=target.location_id
               AND entry.product_id=target.product_id AND entry.batch_id=target.batch_id)
          OR balance.inventory_value IS DISTINCT FROM (
            SELECT COALESCE(sum(entry.value_delta),0) FROM inventory.stock_ledger_entries AS entry
             WHERE entry.org_id=p_org_id AND entry.location_id=target.location_id
               AND entry.product_id=target.product_id AND entry.batch_id=target.batch_id)),
      (SELECT count(*) FROM reachable_events WHERE running_quantity<0),
      (SELECT count(*) FROM origin_remaining AS remaining
        JOIN seed_groups AS seed ON seed.origin_location_id=remaining.origin_location_id
         AND seed.origin_product_id=remaining.origin_product_id
         AND seed.origin_batch_id=remaining.origin_batch_id
       WHERE remaining.remaining_quantity<0 OR remaining.remaining_quantity>seed.allocated_quantity),
      pg_catalog.jsonb_build_object(
        'contract_version','supplier_invoice_landed_cost_lineage_v1',
        'source_identity_count',(SELECT count(*) FROM seed_groups),
        'target_identity_count',(SELECT count(*) FROM target_rows),
        'source_quantity_basis',COALESCE((SELECT sum(allocated_quantity) FROM seed_groups),0)::text,
        'source_value_basis',COALESCE((SELECT sum(allocated_value) FROM seed_groups),0)::text,
        'remaining_quantity_basis',COALESCE((SELECT sum(remaining_quantity) FROM origin_remaining),0)::text,
        'remaining_value_basis',COALESCE((
          SELECT sum(pg_catalog.round(
            remaining.remaining_quantity*seed.allocated_value/seed.allocated_quantity,2))
            FROM origin_remaining AS remaining
            JOIN seed_groups AS seed ON seed.origin_location_id=remaining.origin_location_id
             AND seed.origin_product_id=remaining.origin_product_id
             AND seed.origin_batch_id=remaining.origin_batch_id
        ),0)::text,
        'goods_receipt_line_ids',COALESCE((
          SELECT pg_catalog.jsonb_agg(seed.goods_receipt_line_id ORDER BY seed.goods_receipt_line_id)
            FROM (SELECT DISTINCT goods_receipt_line_id FROM receipt_evidence) AS seed
        ),'[]'::jsonb),
        'transfer_line_ids',COALESCE((
          SELECT pg_catalog.jsonb_agg(transfer.transfer_line_id ORDER BY transfer.transfer_line_id)
            FROM lineage_transfers AS transfer
        ),'[]'::jsonb),
        'targets',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
          'location_id',target.location_id,'branch_id',target.branch_id,
          'product_id',target.product_id,'batch_id',target.batch_id,'uom_code',target.uom_code,
          'on_hand_quantity',target.on_hand_quantity::text,'inventory_value',target.inventory_value::text,
          'average_unit_cost',target.average_unit_cost::text,
          'stock_row_version',target.stock_row_version,
          'last_ledger_entry_id',target.last_ledger_entry_id,
          'origin_location_id',target.origin_location_id,
          'origin_product_id',target.origin_product_id,'origin_batch_id',target.origin_batch_id,
          'origin_allocated_quantity',target.origin_allocated_quantity::text,
          'origin_allocated_value',target.origin_allocated_value::text
        ) ORDER BY target.location_id,target.product_id,target.batch_id) FROM target_rows AS target),'[]'::jsonb)
      )
      INTO seed_bad_count,malformed_transfer_count,foreign_positive_count,unlinked_transfer_count,
           origin_collision_count,balance_bad_count,negative_prefix_count,origin_quantity_bad_count,state;

    IF state IS NULL OR (state->>'source_identity_count')::bigint=0
       OR (state->>'source_quantity_basis')::numeric<=0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='capitalized supplier line has no exact receipt allocation basis';
    END IF;
    IF seed_bad_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost receipt lineage is incomplete, partial, or lacks exact posted ledger evidence';
    END IF;
    IF malformed_transfer_count<>0 OR unlinked_transfer_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost transfer lineage is unbalanced, malformed, or unlinked';
    END IF;
    IF foreign_positive_count<>0 OR origin_collision_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost remaining stock is ambiguous because receipt lineage is co-mingled';
    END IF;
    IF balance_bad_count<>0 OR negative_prefix_count<>0 OR origin_quantity_bad_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost transfer lineage does not reconcile to authoritative stock balances';
    END IF;
    RETURN state;
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_from_receipts"(uuid,jsonb) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_from_receipts"(uuid,jsonb) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."landed_cost_receipt_lineage_state"(p_org_id uuid, p_goods_receipt_line_id uuid, p_allocated_base_billed_quantity numeric, p_allocated_base_free_quantity numeric)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
    RETURN erp_trade_commands_v2.landed_cost_lineage_from_receipts(
      p_org_id,
      pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'goods_receipt_line_id',p_goods_receipt_line_id,
        'allocated_base_billed_quantity',p_allocated_base_billed_quantity::text,
        'allocated_base_free_quantity',p_allocated_base_free_quantity::text
      ))
    );
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."landed_cost_receipt_lineage_state"(uuid,uuid,numeric,numeric) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."landed_cost_receipt_lineage_state"(uuid,uuid,numeric,numeric) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_state"(p_org_id uuid, p_supplier_invoice_line_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE source procurement.supplier_invoice_lines%ROWTYPE;
        receipt_allocations jsonb;
BEGIN
    SELECT line.* INTO source
      FROM procurement.supplier_invoice_lines AS line
      JOIN procurement.supplier_invoices AS invoice
        ON invoice.org_id=line.org_id AND invoice.id=line.supplier_invoice_id
     WHERE line.org_id=p_org_id AND line.id=p_supplier_invoice_line_id
       AND invoice.status IN ('approved','posted')
     FOR SHARE OF line,invoice;
    IF source.id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost lineage requires an approved or posted supplier invoice line';
    END IF;
    SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
             'goods_receipt_line_id',allocation.goods_receipt_line_id,
             'allocated_base_billed_quantity',allocation.allocated_base_billed_quantity::text,
             'allocated_base_free_quantity',allocation.allocated_base_free_quantity::text
           ) ORDER BY allocation.goods_receipt_line_id)
      INTO receipt_allocations
      FROM procurement.supplier_invoice_receipt_allocations AS allocation
      JOIN procurement.supplier_invoice_lines AS product_line
        ON product_line.org_id=allocation.org_id AND product_line.id=allocation.supplier_invoice_line_id
     WHERE allocation.org_id=p_org_id
       AND product_line.supplier_invoice_id=source.supplier_invoice_id
       AND (source.line_kind='charge' OR product_line.id=source.id);
    RETURN erp_trade_commands_v2.landed_cost_lineage_from_receipts(
      p_org_id,receipt_allocations
    );
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_state"(uuid,uuid) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."landed_cost_lineage_state"(uuid,uuid) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."eligible_landed_cost_pool"(p_org_id uuid, p_supplier_invoice_line_id uuid)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE source procurement.supplier_invoice_lines%ROWTYPE;
        total_pool numeric(20,2); source_basis numeric; remaining_basis numeric;
        lineage jsonb;
BEGIN
    SELECT * INTO STRICT source FROM procurement.supplier_invoice_lines
     WHERE org_id=p_org_id AND id=p_supplier_invoice_line_id FOR SHARE;
    total_pool:=erp_trade_commands_v2.total_landed_cost_pool(p_org_id,p_supplier_invoice_line_id);
    IF total_pool=0 OR source.inventory_cost_treatment<>'capitalize' THEN RETURN 0; END IF;
    IF source.landed_cost_allocation_method NOT IN ('direct','quantity_weighted','value_weighted') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='capitalized supplier line lacks a reviewed landed-cost allocation method';
    END IF;

    lineage:=erp_trade_commands_v2.landed_cost_lineage_state(p_org_id,p_supplier_invoice_line_id);
    IF source.landed_cost_allocation_method='direct'
       AND (lineage->>'source_identity_count')::bigint<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='direct landed-cost allocation requires exactly one receipt stock identity';
    END IF;
    source_basis:=CASE source.landed_cost_allocation_method
      WHEN 'value_weighted' THEN (lineage->>'source_value_basis')::numeric
      ELSE (lineage->>'source_quantity_basis')::numeric END;
    remaining_basis:=CASE source.landed_cost_allocation_method
      WHEN 'value_weighted' THEN (lineage->>'remaining_value_basis')::numeric
      ELSE (lineage->>'remaining_quantity_basis')::numeric END;
    IF source_basis<=0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='capitalized supplier line has no exact receipt allocation basis';
    END IF;
    IF remaining_basis<=0 THEN RETURN 0; END IF;
    RETURN pg_catalog.round(total_pool*remaining_basis/source_basis,2);
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."eligible_landed_cost_pool"(uuid,uuid) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."eligible_landed_cost_pool"(uuid,uuid) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."assert_landed_cost_document"(p_org_id uuid, p_document_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE doc inventory.inventory_documents%ROWTYPE;
        source_line record;
        bad_count bigint;
        source_count bigint;
        expected_count bigint;
        pool numeric;
        locked_supplier_invoice_id uuid;
BEGIN
    SELECT * INTO STRICT doc FROM inventory.inventory_documents
     WHERE org_id=p_org_id AND id=p_document_id FOR UPDATE;
    IF doc.status NOT IN ('approved','posted') OR doc.document_type<>'cost_adjustment'
       OR doc.supplier_invoice_id IS NULL
       OR doc.costing_method_snapshot<>'moving_weighted_average' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost command requires an approved or posted typed MWA cost adjustment';
    END IF;
    SELECT id INTO locked_supplier_invoice_id FROM procurement.supplier_invoices
     WHERE org_id=p_org_id AND id=doc.supplier_invoice_id AND status='posted'
     FOR SHARE;
    IF locked_supplier_invoice_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost source supplier invoice is not posted';
    END IF;
    SELECT count(*) INTO source_count FROM inventory.inventory_document_lines
     WHERE org_id=p_org_id AND inventory_document_id=p_document_id;
    IF source_count=0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost document has no allocation lines';
    END IF;

    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(p_org_id::text||':landed-cost:'||p_document_id::text,82410617)
    );
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(lock_key,82410618))
      FROM (
        SELECT DISTINCT p_org_id::text||':'||line.from_location_id::text||':'||line.product_id::text||':'||line.batch_id::text AS lock_key
          FROM inventory.inventory_document_lines AS line
         WHERE line.org_id=p_org_id AND line.inventory_document_id=p_document_id
         ORDER BY lock_key
      ) AS locked;
    PERFORM balance.location_id
      FROM inventory.stock_balances AS balance
      JOIN (
        SELECT DISTINCT from_location_id,product_id,batch_id
          FROM inventory.inventory_document_lines
         WHERE org_id=p_org_id AND inventory_document_id=p_document_id
      ) AS target
        ON target.from_location_id=balance.location_id
       AND target.product_id=balance.product_id AND target.batch_id=balance.batch_id
     WHERE balance.org_id=p_org_id
     ORDER BY balance.location_id,balance.product_id,balance.batch_id
     FOR UPDATE OF balance;

    SELECT count(*) INTO bad_count
      FROM inventory.inventory_document_lines AS line
      JOIN inventory.batches AS batch
        ON batch.org_id=line.org_id AND batch.id=line.batch_id
      JOIN inventory.locations AS location
        ON location.org_id=line.org_id AND location.id=line.from_location_id
      LEFT JOIN inventory.stock_balances AS balance
        ON balance.org_id=line.org_id AND balance.location_id=line.from_location_id
       AND balance.product_id=line.product_id AND balance.batch_id=line.batch_id
      JOIN procurement.supplier_invoice_lines AS supplier_line
        ON supplier_line.org_id=line.org_id AND supplier_line.id=line.supplier_invoice_line_id
     WHERE line.org_id=p_org_id AND line.inventory_document_id=p_document_id
       AND (line.movement_kind<>'value_adjustment'
         OR supplier_line.supplier_invoice_id IS DISTINCT FROM doc.supplier_invoice_id
         OR supplier_line.inventory_cost_treatment<>'capitalize'
         OR line.cost_allocation_method IS DISTINCT FROM supplier_line.landed_cost_allocation_method
         OR batch.product_id IS DISTINCT FROM line.product_id
         OR balance.branch_id IS DISTINCT FROM location.branch_id
         OR balance.on_hand_quantity IS NULL OR balance.on_hand_quantity<=0
         OR balance.inventory_value+line.extended_cost<0
         OR (line.cost_allocation_method='quantity_weighted'
             AND line.cost_allocation_basis_quantity IS DISTINCT FROM balance.on_hand_quantity)
         OR (line.cost_allocation_method='value_weighted'
             AND line.cost_allocation_basis_value IS DISTINCT FROM
               balance.inventory_value-COALESCE((
                 SELECT sum(entry.value_delta) FROM inventory.stock_ledger_entries entry
                  WHERE entry.org_id=line.org_id AND entry.inventory_document_id=line.inventory_document_id
                    AND entry.location_id=line.from_location_id AND entry.product_id=line.product_id
                    AND entry.batch_id=line.batch_id AND entry.entry_kind='value_adjustment'
               ),0))
         OR NOT EXISTS (
             SELECT 1
               FROM pg_catalog.jsonb_array_elements(
                 erp_trade_commands_v2.landed_cost_lineage_state(line.org_id,supplier_line.id)->'targets'
               ) AS target(value)
              WHERE (target.value->>'location_id')::uuid=line.from_location_id
                AND (target.value->>'product_id')::uuid=line.product_id
                AND (target.value->>'batch_id')::uuid=line.batch_id
         ));
    IF bad_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost target is not positive on-hand stock from the supplier invoice receipt lineage';
    END IF;

    FOR source_line IN
        SELECT supplier_line.id,
               count(line.id) AS allocation_count,
               min(line.cost_allocation_method) AS allocation_method,
               max(line.cost_allocation_method) AS max_allocation_method,
               sum(line.cost_allocation_weight) AS weight_total
          FROM procurement.supplier_invoice_lines AS supplier_line
          JOIN inventory.inventory_document_lines AS line
            ON line.org_id=supplier_line.org_id AND line.supplier_invoice_line_id=supplier_line.id
         WHERE supplier_line.org_id=p_org_id
           AND supplier_line.supplier_invoice_id=doc.supplier_invoice_id
           AND line.inventory_document_id=p_document_id
         GROUP BY supplier_line.id
         ORDER BY supplier_line.id
    LOOP
        pool := erp_trade_commands_v2.eligible_landed_cost_pool(p_org_id,source_line.id);
        IF pool=0 OR source_line.allocation_method IS DISTINCT FROM source_line.max_allocation_method
           OR source_line.weight_total IS DISTINCT FROM 1 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost source pool, method, or exact weight total is invalid';
        END IF;

        SELECT count(*) INTO bad_count
          FROM (
            SELECT line.id,line.line_number,line.extended_cost,line.cost_allocation_method,
                   line.cost_allocation_weight,
                   CASE line.cost_allocation_method
                     WHEN 'direct' THEN balance.on_hand_quantity
                     WHEN 'quantity_weighted' THEN line.cost_allocation_basis_quantity
                     WHEN 'value_weighted' THEN line.cost_allocation_basis_value
                   END AS basis,
                   sum(CASE line.cost_allocation_method
                         WHEN 'direct' THEN balance.on_hand_quantity
                         WHEN 'quantity_weighted' THEN line.cost_allocation_basis_quantity
                         WHEN 'value_weighted' THEN line.cost_allocation_basis_value
                       END) OVER () AS basis_total,
                   row_number() OVER (ORDER BY line.line_number,line.id) AS allocation_position,
                   count(*) OVER () AS allocation_total
              FROM inventory.inventory_document_lines AS line
              JOIN inventory.stock_balances AS balance
                ON balance.org_id=line.org_id AND balance.location_id=line.from_location_id
               AND balance.product_id=line.product_id AND balance.batch_id=line.batch_id
             WHERE line.org_id=p_org_id AND line.inventory_document_id=p_document_id
               AND line.supplier_invoice_line_id=source_line.id
          ) AS allocation
         WHERE allocation.cost_allocation_weight IS DISTINCT FROM
                 CASE WHEN allocation.allocation_position<allocation.allocation_total
                      THEN pg_catalog.round(allocation.basis/allocation.basis_total,12)
                      ELSE 1-COALESCE((
                          SELECT sum(pg_catalog.round(prior.basis/prior.basis_total,12))
                            FROM (
                              SELECT CASE earlier.cost_allocation_method
                                       WHEN 'direct' THEN earlier_balance.on_hand_quantity
                                       WHEN 'quantity_weighted' THEN earlier.cost_allocation_basis_quantity
                                       WHEN 'value_weighted' THEN earlier.cost_allocation_basis_value
                                     END AS basis,
                                     sum(CASE earlier.cost_allocation_method
                                           WHEN 'direct' THEN earlier_balance.on_hand_quantity
                                           WHEN 'quantity_weighted' THEN earlier.cost_allocation_basis_quantity
                                           WHEN 'value_weighted' THEN earlier.cost_allocation_basis_value
                                         END) OVER () AS basis_total,
                                     row_number() OVER (ORDER BY earlier.line_number,earlier.id) AS position
                                FROM inventory.inventory_document_lines AS earlier
                                JOIN inventory.stock_balances AS earlier_balance
                                  ON earlier_balance.org_id=earlier.org_id
                                 AND earlier_balance.location_id=earlier.from_location_id
                                 AND earlier_balance.product_id=earlier.product_id
                                 AND earlier_balance.batch_id=earlier.batch_id
                               WHERE earlier.org_id=p_org_id
                                 AND earlier.inventory_document_id=p_document_id
                                 AND earlier.supplier_invoice_line_id=source_line.id
                            ) AS prior
                           WHERE prior.position<allocation.allocation_total
                      ),0) END
            OR allocation.extended_cost IS DISTINCT FROM
                 CASE WHEN allocation.allocation_position<allocation.allocation_total
                      THEN pg_catalog.round(pool*allocation.cost_allocation_weight,2)
                      ELSE pool-COALESCE((
                          SELECT sum(pg_catalog.round(pool*prior.cost_allocation_weight,2))
                            FROM (
                              SELECT earlier.cost_allocation_weight,
                                     row_number() OVER (ORDER BY earlier.line_number,earlier.id) AS position
                                FROM inventory.inventory_document_lines AS earlier
                               WHERE earlier.org_id=p_org_id
                                 AND earlier.inventory_document_id=p_document_id
                                 AND earlier.supplier_invoice_line_id=source_line.id
                            ) AS prior
                           WHERE prior.position<allocation.allocation_total
                      ),0) END;
        IF bad_count<>0 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost weights or deterministic final-paise allocation do not match the eligible pool';
        END IF;
    END LOOP;

    SELECT count(*) INTO source_count
      FROM (
        SELECT DISTINCT supplier_invoice_line_id
          FROM inventory.inventory_document_lines
         WHERE org_id=p_org_id AND inventory_document_id=p_document_id
      ) AS sources;
    SELECT count(*) INTO expected_count
      FROM procurement.supplier_invoice_lines AS line
     WHERE line.org_id=p_org_id AND line.supplier_invoice_id=doc.supplier_invoice_id
       AND line.inventory_cost_treatment='capitalize'
       AND erp_trade_commands_v2.eligible_landed_cost_pool(p_org_id,line.id)<>0;
    IF source_count<>expected_count THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost document does not allocate every and only nonzero capitalized source pool';
    END IF;
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."assert_landed_cost_document"(uuid,uuid) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."assert_landed_cost_document"(uuid,uuid) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_trade_commands_v2"."prepare_supplier_invoice_landed_cost_adjustment"(p_org_id uuid, p_supplier_invoice_id uuid, p_document_id uuid, p_actor_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE invoice procurement.supplier_invoices%ROWTYPE;
        source_line procurement.supplier_invoice_lines%ROWTYPE; target record;
        lineage jsonb;
        pool numeric(20,2); basis numeric; basis_total numeric;
        weight numeric(20,12); allocated_weight numeric(20,12):=0;
        allocated_value numeric(20,2):=0; line_value numeric(20,2);
        line_number integer:=0; target_count bigint; target_position bigint;
        document_value numeric(20,2);
BEGIN
    PERFORM erp_trade_commands.assert_context(p_org_id,p_actor_id);
    SELECT * INTO STRICT invoice FROM procurement.supplier_invoices
     WHERE org_id=p_org_id AND id=p_supplier_invoice_id AND status IN ('approved','posted') FOR UPDATE;
    PERFORM erp_trade_commands.assert_permission('procurement.invoice.post',invoice.branch_id);
    IF p_document_id IS NULL OR EXISTS (
      SELECT 1 FROM inventory.inventory_documents
       WHERE org_id=p_org_id AND supplier_invoice_id=p_supplier_invoice_id
    ) THEN
      RAISE EXCEPTION USING ERRCODE='23505', MESSAGE='supplier invoice landed-cost document identity already exists';
    END IF;
    PERFORM balance.location_id
      FROM procurement.supplier_invoice_lines AS supplier_line
      CROSS JOIN LATERAL pg_catalog.jsonb_array_elements(
        erp_trade_commands_v2.landed_cost_lineage_state(p_org_id,supplier_line.id)->'targets'
      ) AS source_target(value)
      JOIN inventory.stock_balances AS balance
        ON balance.org_id=p_org_id
       AND balance.location_id=(source_target.value->>'location_id')::uuid
       AND balance.product_id=(source_target.value->>'product_id')::uuid
       AND balance.batch_id=(source_target.value->>'batch_id')::uuid
     WHERE balance.org_id=p_org_id
       AND supplier_line.org_id=p_org_id
       AND supplier_line.supplier_invoice_id=p_supplier_invoice_id
       AND supplier_line.inventory_cost_treatment='capitalize'
     ORDER BY balance.location_id,balance.product_id,balance.batch_id
     FOR UPDATE OF balance;
    SELECT COALESCE(sum(pg_catalog.abs(erp_trade_commands_v2.eligible_landed_cost_pool(p_org_id,line.id))),0)
      INTO document_value FROM procurement.supplier_invoice_lines line
     WHERE line.org_id=p_org_id AND line.supplier_invoice_id=p_supplier_invoice_id
       AND line.inventory_cost_treatment='capitalize';
    IF document_value=0 THEN RETURN NULL; END IF;

    INSERT INTO inventory.inventory_documents(
      org_id,id,branch_id,physical_movement_required,document_type,document_number,
      fiscal_year,document_date,status,reason_code,currency_code,costing_method_snapshot,
      total_abs_base_quantity,total_value,supplier_invoice_id,approved_at,approved_by_membership_id
    ) VALUES (
      p_org_id,p_document_id,invoice.branch_id,false,'cost_adjustment',invoice.supplier_invoice_number,
      invoice.fiscal_year,invoice.supplier_invoice_date,'approved','supplier_invoice_landed_cost',
      invoice.currency_code,'moving_weighted_average',0,document_value,p_supplier_invoice_id,
      pg_catalog.transaction_timestamp(),p_actor_id
    );

    FOR source_line IN SELECT * FROM procurement.supplier_invoice_lines
      WHERE org_id=p_org_id AND supplier_invoice_id=p_supplier_invoice_id
        AND inventory_cost_treatment='capitalize' ORDER BY line_number,id
    LOOP
      pool:=erp_trade_commands_v2.eligible_landed_cost_pool(p_org_id,source_line.id);
      IF pool=0 THEN CONTINUE; END IF;
      lineage:=erp_trade_commands_v2.landed_cost_lineage_state(p_org_id,source_line.id);
      allocated_weight:=0; allocated_value:=0;
      SELECT count(*),sum(CASE source_line.landed_cost_allocation_method
               WHEN 'value_weighted' THEN (stock_target.value->>'inventory_value')::numeric
               ELSE (stock_target.value->>'on_hand_quantity')::numeric END)
        INTO target_count,basis_total
        FROM pg_catalog.jsonb_array_elements(lineage->'targets') AS stock_target(value);
      IF target_count=0 OR basis_total<=0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost source has no exact positive reviewed allocation basis';
      END IF;

      target_position:=0;
      FOR target IN
        SELECT (stock_target.value->>'location_id')::uuid AS location_id,
               (stock_target.value->>'product_id')::uuid AS product_id,
               (stock_target.value->>'batch_id')::uuid AS batch_id,
               stock_target.value->>'uom_code' AS uom_code,
               (stock_target.value->>'on_hand_quantity')::numeric AS on_hand_quantity,
               (stock_target.value->>'inventory_value')::numeric AS inventory_value,
               (stock_target.value->>'average_unit_cost')::numeric AS average_unit_cost
          FROM pg_catalog.jsonb_array_elements(lineage->'targets') AS stock_target(value)
         ORDER BY (stock_target.value->>'location_id')::uuid,
                  (stock_target.value->>'product_id')::uuid,
                  (stock_target.value->>'batch_id')::uuid
      LOOP
        target_position:=target_position+1;
        basis:=CASE source_line.landed_cost_allocation_method
          WHEN 'value_weighted' THEN target.inventory_value ELSE target.on_hand_quantity END;
        weight:=CASE WHEN target_position<target_count THEN pg_catalog.round(basis/basis_total,12)
          ELSE 1-allocated_weight END;
        line_value:=CASE WHEN target_position<target_count THEN pg_catalog.round(pool*weight,2)
          ELSE pool-allocated_value END;
        line_number:=line_number+1;
        INSERT INTO inventory.inventory_document_lines(
          org_id,id,inventory_document_id,line_number,movement_kind,product_id,batch_id,uom_code,
          entered_quantity,base_quantity,from_location_id,unit_cost,extended_cost,
          cost_allocation_method,cost_allocation_basis_quantity,cost_allocation_basis_value,
          cost_allocation_weight,supplier_invoice_line_id
        ) VALUES (
          p_org_id,pg_catalog.gen_random_uuid(),p_document_id,line_number,'value_adjustment',
          target.product_id,target.batch_id,target.uom_code,0,0,target.location_id,
          target.average_unit_cost,line_value,source_line.landed_cost_allocation_method,
          CASE WHEN source_line.landed_cost_allocation_method='quantity_weighted' THEN target.on_hand_quantity END,
          CASE WHEN source_line.landed_cost_allocation_method='value_weighted' THEN target.inventory_value END,
          weight,source_line.id
        );
        allocated_weight:=allocated_weight+weight; allocated_value:=allocated_value+line_value;
      END LOOP;
      IF allocated_weight<>1 OR allocated_value<>pool THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='landed-cost allocation residual did not reconcile exactly';
      END IF;
    END LOOP;
    RETURN p_document_id;
END
$function$;

ALTER FUNCTION "erp_trade_commands_v2"."prepare_supplier_invoice_landed_cost_adjustment"(uuid,uuid,uuid,uuid) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_trade_commands_v2"."prepare_supplier_invoice_landed_cost_adjustment"(uuid,uuid,uuid,uuid) FROM PUBLIC, "erp_app", "erp_runtime";

CREATE OR REPLACE FUNCTION "erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, request_document jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
#variable_conflict use_variable
DECLARE requested_branch_id uuid:=NULLIF(request_document->>'branch_id','')::uuid;
        requested_supplier_id uuid:=NULLIF(request_document->>'supplier_account_id','')::uuid;
        requested_registration_id uuid:=NULLIF(request_document->>'supplier_tax_registration_id','')::uuid;
        requested_portal_line_id uuid:=NULLIF(request_document->>'portal_document_line_id','')::uuid;
        invoice_date date:=NULLIF(request_document->>'invoice_date','')::date;
        received_date date:=NULLIF(request_document->>'received_date','')::date;
        organization core.organizations%ROWTYPE; branch core.branches%ROWTYPE;
        buyer_registration tax.registrations%ROWTYPE; buyer_scope tax.registration_branches%ROWTYPE;
        supplier parties.supplier_accounts%ROWTYPE; supplier_party parties.parties%ROWTYPE;
        supplier_registration parties.tax_registrations%ROWTYPE; supplier_address parties.addresses%ROWTYPE;
        portal_line tax.portal_document_lines%ROWTYPE; portal_document tax.portal_documents%ROWTYPE;
        portal_period tax.return_periods%ROWTYPE; inventory_account finance.accounts%ROWTYPE;
        payable_account finance.accounts%ROWTYPE; input_cgst_account finance.accounts%ROWTYPE;
        input_sgst_account finance.accounts%ROWTYPE; input_igst_account finance.accounts%ROWTYPE;
        input_cess_account finance.accounts%ROWTYPE; rounding_gain_account finance.accounts%ROWTYPE;
        rounding_loss_account finance.accounts%ROWTYPE; variance_account finance.accounts%ROWTYPE;
        receipt_line procurement.goods_receipt_lines%ROWTYPE; receipt procurement.goods_receipts%ROWTYPE;
        order_line procurement.purchase_order_lines%ROWTYPE; purchase_order procurement.purchase_orders%ROWTYPE;
        product catalog.products%ROWTYPE;
        tax_version tax.tax_code_versions%ROWTYPE; tax_release core.reference_data_releases%ROWTYPE;
        profile catalog.commercial_charge_tax_profiles%ROWTYPE; expense_account finance.accounts%ROWTYPE;
        requested_line jsonb; requested_allocation jsonb; resolved_allocations jsonb;
        landed_cost_lineage jsonb; landed_cost_target jsonb;
        resolved_lines jsonb:='[]'::jsonb; source_versions jsonb:='[]'::jsonb;
        resolved_receipt_ids jsonb:='[]'::jsonb; source_purchase_order_id uuid;
        base_billed numeric(20,6); base_free numeric(20,6); prior_billed numeric(20,6); prior_free numeric(20,6);
        receipt_cost numeric(20,2); line_product_id uuid; line_purchase_order_line_id uuid;
        line_uom text; line_factor numeric(20,6); receipt_business_date date;
        ruleset_version text; supply_type text; candidate_count integer; address_count integer;
        allocation_count integer; distinct_allocation_count integer;
BEGIN
    IF organization_id IS NULL OR membership_id IS NULL OR auth_user_id IS NULL OR application_user_id IS NULL
       OR grant_id IS NULL OR supplier_invoice_id IS NULL OR requested_branch_id IS NULL
       OR requested_supplier_id IS NULL OR requested_registration_id IS NULL OR requested_portal_line_id IS NULL
       OR invoice_date IS NULL OR received_date<invoice_date OR pg_catalog.btrim(COALESCE(request_document->>'supplier_invoice_number',''))=''
       OR request_document->>'tax_charge_mechanism'<>'normal'
       OR request_document->>'zero_rated_payment_mode'<>'not_applicable'
       OR pg_catalog.jsonb_typeof(request_document->'lines')<>'array'
       OR pg_catalog.jsonb_array_length(request_document->'lines') NOT BETWEEN 1 AND 500
       OR pg_catalog.jsonb_typeof(request_document->'goods_receipt_ids')<>'array'
       OR pg_catalog.jsonb_array_length(request_document->'goods_receipt_ids')<1
       OR pg_catalog.jsonb_typeof(COALESCE(request_document->'expense_charge_lines','[]'::jsonb))<>'array' THEN
      RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier-invoice input is incomplete or outside the domestic normal-charge pilot'; END IF;
    SELECT count(*),count(DISTINCT line.value->>'goods_receipt_line_id')
      INTO allocation_count,distinct_allocation_count
      FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value);
    IF allocation_count<>distinct_allocation_count OR allocation_count=0
       OR (SELECT count(*) FROM pg_catalog.jsonb_array_elements_text(request_document->'goods_receipt_ids'))
          <>(SELECT count(DISTINCT value) FROM pg_catalog.jsonb_array_elements_text(request_document->'goods_receipt_ids')) THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice requires unique receipt lines and a unique exact GRN set'; END IF;
    IF EXISTS (SELECT 1 FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
      WHERE line.value->>'product_inventory_cost_treatment'<>'capitalize'
         OR line.value->>'landed_cost_allocation_method' NOT IN ('direct','quantity_weighted','value_weighted')
         OR line.value->>'itc_eligibility'<>'eligible'
         OR line.value->>'itc_eligibility_basis'<>'taxable_resale_not_blocked_under_section_17')
       OR EXISTS (SELECT 1 FROM pg_catalog.jsonb_array_elements(COALESCE(request_document->'expense_charge_lines','[]'::jsonb)) line(value)
      WHERE line.value->>'charge_inventory_cost_treatment' NOT IN ('expense','capitalize')
         OR (line.value->>'charge_inventory_cost_treatment'='capitalize'
             AND line.value->>'landed_cost_allocation_method' NOT IN ('direct','quantity_weighted','value_weighted'))
         OR (line.value->>'charge_inventory_cost_treatment'='expense'
             AND line.value ? 'landed_cost_allocation_method')
         OR line.value->>'itc_eligibility'<>'eligible'
         OR line.value->>'itc_eligibility_basis'<>'taxable_resale_not_blocked_under_section_17'
         OR line.value->>'expense_charge_code' NOT IN ('freight','packing','insurance','handling')) THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='supplier-invoice requires reviewed ITC and explicit product or charge landed-cost treatment'; END IF;
    PERFORM 1 FROM core.memberships membership JOIN core.users user_row ON user_row.id=membership.user_id
      JOIN core.organizations organization_row ON organization_row.id=membership.org_id
      JOIN automation.agent_grants grant_row ON grant_row.org_id=membership.org_id AND grant_row.subject_membership_id=membership.id
      JOIN automation.agent_grant_capabilities capability ON capability.org_id=grant_row.org_id AND capability.agent_grant_id=grant_row.id
     WHERE membership.org_id=organization_id AND membership.id=membership_id AND membership.user_id=application_user_id
       AND membership.status='active' AND user_row.auth_user_id=auth_user_id AND user_row.status='active'
       AND organization_row.status='active' AND grant_row.id=grant_id AND grant_row.client_id=caller_client_id
       AND grant_row.status='active' AND grant_row.expires_at>pg_catalog.transaction_timestamp()
       AND (grant_row.branch_id IS NULL OR grant_row.branch_id=requested_branch_id)
       AND capability.capability_code='procurement.supplier_invoice.prepare'
       AND capability.operation_mode='write' AND capability.status='active';
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-invoice delegated authority is inactive'; END IF;
    PERFORM erp_security.activate_context(auth_user_id,organization_id);
    IF erp_security.current_membership_id() IS DISTINCT FROM membership_id THEN
      RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-invoice verified auth context resolved a different membership'; END IF;
    IF erp_security.can_access_branch(requested_branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('procurement.supplier_invoice.create',requested_branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('procurement.invoice.post',requested_branch_id) IS DISTINCT FROM true
       OR erp_security.has_permission('finance.journal.post',NULL::uuid) IS DISTINCT FROM true
       OR erp_security.has_permission('automation.command.execute',requested_branch_id) IS DISTINCT FROM true THEN
      RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='supplier-invoice cross-domain permission is inactive'; END IF;
    SELECT * INTO STRICT organization FROM core.organizations WHERE id=organization_id AND status='active' FOR SHARE;
    SELECT * INTO STRICT branch FROM core.branches WHERE org_id=organization_id AND id=requested_branch_id AND status='active' FOR SHARE;
    IF invoice_date>"erp_core_commands"."current_organization_business_date"()
       OR received_date>"erp_core_commands"."current_organization_business_date"() THEN
      RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='supplier invoice or received date cannot be in the future'; END IF;
    IF organization.country_code<>'IN' OR organization.base_currency<>'INR' THEN
      RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='supplier-invoice pilot supports only Indian INR organizations'; END IF;
    SELECT count(*) INTO candidate_count FROM tax.registration_branches association JOIN tax.registrations registration
      ON registration.org_id=association.org_id AND registration.id=association.registration_id
     WHERE association.org_id=organization_id AND association.branch_id=branch.id AND association.status='active'
       AND association.effective_from<=invoice_date AND (association.effective_to IS NULL OR association.effective_to>=invoice_date)
       AND registration.state_code=branch.state_code AND registration.registration_type='regular' AND registration.status='active'
       AND registration.effective_from<=invoice_date AND (registration.effective_to IS NULL OR registration.effective_to>=invoice_date);
    IF candidate_count<>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='buyer requires one exact effective regular branch GST registration'; END IF;
    SELECT registration.* INTO STRICT buyer_registration FROM tax.registration_branches association JOIN tax.registrations registration
      ON registration.org_id=association.org_id AND registration.id=association.registration_id
     WHERE association.org_id=organization_id AND association.branch_id=branch.id AND association.status='active'
       AND association.effective_from<=invoice_date AND (association.effective_to IS NULL OR association.effective_to>=invoice_date)
       AND registration.state_code=branch.state_code AND registration.registration_type='regular' AND registration.status='active'
       AND registration.effective_from<=invoice_date AND (registration.effective_to IS NULL OR registration.effective_to>=invoice_date)
     FOR SHARE OF association,registration;
    SELECT * INTO STRICT buyer_scope FROM tax.registration_branches association
     WHERE association.org_id=organization_id AND association.registration_id=buyer_registration.id
       AND association.branch_id=branch.id AND association.status='active'
       AND association.effective_from<=invoice_date AND (association.effective_to IS NULL OR association.effective_to>=invoice_date) FOR SHARE;
    SELECT * INTO STRICT supplier FROM parties.supplier_accounts
     WHERE org_id=organization_id AND id=requested_supplier_id AND status='active' FOR SHARE;
    SELECT * INTO STRICT supplier_party FROM parties.parties
     WHERE org_id=organization_id AND id=supplier.party_id AND status='active' FOR SHARE;
    SELECT * INTO STRICT supplier_registration FROM parties.tax_registrations
     WHERE org_id=organization_id AND id=requested_registration_id AND party_id=supplier.party_id
       AND registration_type='GSTIN' AND status='active' AND verified_at IS NOT NULL
       AND taxpayer_type IN ('regular','casual') AND (valid_from IS NULL OR valid_from<=invoice_date)
       AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
    SELECT count(*) INTO address_count FROM parties.addresses WHERE org_id=organization_id AND party_id=supplier.party_id
       AND address_kind='registered' AND is_primary AND status='active' AND state_code=supplier_registration.state_code
       AND valid_from<=invoice_date AND (valid_until IS NULL OR valid_until>=invoice_date);
    IF address_count<>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='supplier GSTIN requires one exact effective registered address'; END IF;
    SELECT * INTO STRICT supplier_address FROM parties.addresses WHERE org_id=organization_id AND party_id=supplier.party_id
       AND address_kind='registered' AND is_primary AND status='active' AND state_code=supplier_registration.state_code
       AND valid_from<=invoice_date AND (valid_until IS NULL OR valid_until>=invoice_date) FOR SHARE;
    IF supplier_address.country_code<>'IN' THEN RAISE EXCEPTION USING ERRCODE='0A000', MESSAGE='import supplier invoices remain fail-closed'; END IF;
    supply_type:=CASE WHEN buyer_registration.state_code=supplier_registration.state_code THEN 'intra_state' ELSE 'inter_state' END;
    SELECT * INTO STRICT portal_line FROM tax.portal_document_lines
     WHERE org_id=organization_id AND id=requested_portal_line_id AND document_type='invoice'
       AND supplier_gstin=supplier_registration.registration_number
       AND invoice_number=request_document->>'supplier_invoice_number' AND invoice_date=invoice_date
       AND place_of_supply_state_code=buyer_registration.state_code FOR SHARE;
    SELECT * INTO STRICT portal_document FROM tax.portal_documents
     WHERE org_id=organization_id AND id=portal_line.portal_document_id AND registration_id=buyer_registration.id
       AND portal_document_type='gstr2b' AND status='parsed' AND parsed_at IS NOT NULL FOR SHARE;
    SELECT * INTO STRICT portal_period FROM tax.return_periods
     WHERE org_id=organization_id AND id=portal_document.return_period_id AND registration_id=buyer_registration.id
       AND period_start<=invoice_date AND period_end>=invoice_date FOR SHARE;
    SELECT count(*) INTO candidate_count FROM tax.portal_document_lines line JOIN tax.portal_documents document
      ON document.org_id=line.org_id AND document.id=line.portal_document_id
     WHERE line.org_id=organization_id AND line.supplier_gstin=supplier_registration.registration_number
       AND line.invoice_number=request_document->>'supplier_invoice_number' AND line.invoice_date=invoice_date
       AND line.document_type='invoice' AND document.registration_id=buyer_registration.id
       AND document.portal_document_type='gstr2b' AND document.status='parsed';
    IF candidate_count<>1 THEN RAISE EXCEPTION USING ERRCODE='21000', MESSAGE='supplier invoice requires one unique parsed GSTR-2B row'; END IF;
    SELECT * INTO STRICT inventory_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'inventory_asset','asset','INR',false) FOR SHARE;
    SELECT * INTO STRICT payable_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'accounts_payable','liability','INR',true) FOR SHARE;
    IF supplier.default_payable_account_id IS DISTINCT FROM payable_account.id THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier default payable account differs from the reviewed branch account role'; END IF;
    SELECT * INTO STRICT input_cgst_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'input_cgst','asset','INR',false) FOR SHARE;
    SELECT * INTO STRICT input_sgst_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'input_sgst','asset','INR',false) FOR SHARE;
    SELECT * INTO STRICT input_igst_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'input_igst','asset','INR',false) FOR SHARE;
    SELECT * INTO STRICT input_cess_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'input_cess','asset','INR',false) FOR SHARE;
    SELECT * INTO STRICT rounding_gain_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'rounding_gain','income','INR',false) FOR SHARE;
    SELECT * INTO STRICT rounding_loss_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'rounding_loss','expense','INR',false) FOR SHARE;
    SELECT * INTO STRICT variance_account FROM finance.accounts WHERE org_id=organization_id
       AND id=erp_commercial_commands.resolve_role_account(organization_id,branch.id,'purchase_price_variance','expense','INR',false) FOR SHARE;
    source_versions:=pg_catalog.jsonb_build_array(
      pg_catalog.jsonb_build_object('resource_type','organization','id',organization.id,'row_version',organization.row_version),
      pg_catalog.jsonb_build_object('resource_type','branch','id',branch.id,'row_version',branch.row_version),
      pg_catalog.jsonb_build_object('resource_type','buyer_tax_registration','id',buyer_registration.id,'row_version',buyer_registration.row_version),
      pg_catalog.jsonb_build_object('resource_type','buyer_registration_branch','registration_id',buyer_scope.registration_id,'branch_id',buyer_scope.branch_id,'effective_from',buyer_scope.effective_from,'effective_to',buyer_scope.effective_to),
      pg_catalog.jsonb_build_object('resource_type','supplier_account','id',supplier.id,'row_version',supplier.row_version,'payment_days',supplier.payment_days),
      pg_catalog.jsonb_build_object('resource_type','supplier_party','id',supplier_party.id,'row_version',supplier_party.row_version),
      pg_catalog.jsonb_build_object('resource_type','supplier_tax_registration','id',supplier_registration.id,'row_version',supplier_registration.row_version,'registration_number',supplier_registration.registration_number,'taxpayer_type',supplier_registration.taxpayer_type,'verified_at',supplier_registration.verified_at),
      pg_catalog.jsonb_build_object('resource_type','supplier_registered_address','id',supplier_address.id,'row_version',supplier_address.row_version),
      pg_catalog.jsonb_build_object('resource_type','gstr2b_portal_document','id',portal_document.id,'status',portal_document.status,'parsed_at',portal_document.parsed_at,'source_sha256',pg_catalog.encode(portal_document.source_sha256,'hex')),
      pg_catalog.jsonb_build_object('resource_type','gstr2b_portal_line','id',portal_line.id,'source_row_hash',pg_catalog.encode(portal_line.source_row_hash,'hex')),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','inventory_asset','id',inventory_account.id,'row_version',inventory_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','accounts_payable','id',payable_account.id,'row_version',payable_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','input_cgst','id',input_cgst_account.id,'row_version',input_cgst_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','input_sgst','id',input_sgst_account.id,'row_version',input_sgst_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','input_igst','id',input_igst_account.id,'row_version',input_igst_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','input_cess','id',input_cess_account.id,'row_version',input_cess_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','rounding_gain','id',rounding_gain_account.id,'row_version',rounding_gain_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','rounding_loss','id',rounding_loss_account.id,'row_version',rounding_loss_account.row_version),
      pg_catalog.jsonb_build_object('resource_type','finance_account','role','purchase_price_variance','id',variance_account.id,'row_version',variance_account.row_version));
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
        organization_id::text||':supplier-receipt:'||locked.goods_receipt_line_id,630195401))
      FROM (
        SELECT DISTINCT line.value->>'goods_receipt_line_id' AS goods_receipt_line_id
          FROM pg_catalog.jsonb_array_elements(request_document->'lines') line(value)
         ORDER BY goods_receipt_line_id
      ) locked;
    FOR requested_line IN SELECT value FROM pg_catalog.jsonb_array_elements(request_document->'lines') LOOP
      IF NULLIF(requested_line->>'line_id','')::uuid IS NULL OR NULLIF(requested_line->>'allocation_id','')::uuid IS NULL
         OR NULLIF(requested_line->>'goods_receipt_line_id','')::uuid IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='supplier product line requires identity and one explicit receipt line'; END IF;
      base_billed:=0; base_free:=0; receipt_cost:=0; line_product_id:=NULL; line_purchase_order_line_id:=NULL;
      line_uom:=NULL; line_factor:=NULL; resolved_allocations:='[]'::jsonb;
      FOR requested_allocation IN SELECT pg_catalog.jsonb_build_object(
        'allocation_id',requested_line->>'allocation_id',
        'goods_receipt_line_id',requested_line->>'goods_receipt_line_id',
        'allocated_base_billed_quantity',requested_line->>'allocated_base_billed_quantity',
        'allocated_base_free_quantity',requested_line->>'allocated_base_free_quantity') LOOP
        PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(organization_id::text||':supplier-receipt:'||(requested_allocation->>'goods_receipt_line_id'),630195401));
        SELECT line.* INTO STRICT receipt_line FROM procurement.goods_receipt_lines line JOIN procurement.goods_receipts header
          ON header.org_id=line.org_id AND header.id=line.goods_receipt_id
         WHERE line.org_id=organization_id AND line.id=NULLIF(requested_allocation->>'goods_receipt_line_id','')::uuid
           AND header.status='posted' AND header.branch_id=branch.id AND header.supplier_account_id=supplier.id
           AND line.purchase_order_line_id IS NOT NULL FOR SHARE OF line,header;
        SELECT * INTO STRICT receipt FROM procurement.goods_receipts
         WHERE org_id=organization_id AND id=receipt_line.goods_receipt_id AND status='posted' FOR SHARE;
        receipt_business_date:=(receipt.received_at AT TIME ZONE organization.timezone)::date;
        IF received_date<receipt_business_date THEN
          RAISE EXCEPTION USING ERRCODE='22007', MESSAGE='supplier invoice received date cannot precede the organization-local goods receipt date'; END IF;
        SELECT * INTO STRICT order_line FROM procurement.purchase_order_lines
         WHERE org_id=organization_id AND id=receipt_line.purchase_order_line_id AND line_kind='product' FOR SHARE;
        SELECT * INTO STRICT purchase_order FROM procurement.purchase_orders
         WHERE org_id=organization_id AND id=order_line.purchase_order_id
           AND branch_id=branch.id AND supplier_account_id=supplier.id
           AND status IN ('partially_received','received') FOR SHARE;
        IF source_purchase_order_id IS NULL THEN source_purchase_order_id:=purchase_order.id;
        ELSIF source_purchase_order_id IS DISTINCT FROM purchase_order.id THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice receipt allocations must belong to one purchase order'; END IF;
        IF receipt_line.uom_code IS DISTINCT FROM order_line.uom_code THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='posted receipt UOM differs from its locked purchase-order line'; END IF;
        SELECT * INTO STRICT product FROM catalog.products
         WHERE org_id=organization_id AND id=receipt_line.product_id AND id=order_line.product_id
           AND product_kind IN ('medicine','medical_device','consumable') AND status='active' FOR SHARE;
        IF line_product_id IS NULL THEN line_product_id:=product.id; line_purchase_order_line_id:=order_line.id;
          line_uom:=receipt_line.uom_code; line_factor:=order_line.uom_conversion_factor;
        ELSIF ROW(line_product_id,line_purchase_order_line_id,line_uom,line_factor)
          IS DISTINCT FROM ROW(product.id,order_line.id,receipt_line.uom_code,order_line.uom_conversion_factor) THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='one supplier invoice line cannot mix PO line, product, or UOM receipt facts'; END IF;
        PERFORM allocation.id
          FROM procurement.supplier_invoice_receipt_allocations allocation
          JOIN procurement.supplier_invoice_lines invoice_line
            ON invoice_line.org_id=allocation.org_id AND invoice_line.id=allocation.supplier_invoice_line_id
         WHERE allocation.org_id=organization_id AND allocation.goods_receipt_line_id=receipt_line.id
           AND invoice_line.supplier_invoice_id<>supplier_invoice_id
         ORDER BY allocation.id FOR SHARE OF allocation,invoice_line;
        prior_billed:=COALESCE((SELECT sum(allocation.allocated_base_billed_quantity)
          FROM procurement.supplier_invoice_receipt_allocations allocation JOIN procurement.supplier_invoice_lines invoice_line
            ON invoice_line.org_id=allocation.org_id AND invoice_line.id=allocation.supplier_invoice_line_id
         WHERE allocation.org_id=organization_id AND allocation.goods_receipt_line_id=receipt_line.id
           AND invoice_line.supplier_invoice_id<>supplier_invoice_id),0);
        prior_free:=COALESCE((SELECT sum(allocation.allocated_base_free_quantity)
          FROM procurement.supplier_invoice_receipt_allocations allocation JOIN procurement.supplier_invoice_lines invoice_line
            ON invoice_line.org_id=allocation.org_id AND invoice_line.id=allocation.supplier_invoice_line_id
         WHERE allocation.org_id=organization_id AND allocation.goods_receipt_line_id=receipt_line.id
           AND invoice_line.supplier_invoice_id<>supplier_invoice_id),0);
        IF (requested_allocation->>'allocated_base_billed_quantity')::numeric<0
           OR (requested_allocation->>'allocated_base_free_quantity')::numeric<0
           OR (requested_allocation->>'allocated_base_billed_quantity')::numeric+(requested_allocation->>'allocated_base_free_quantity')::numeric<=0
           OR prior_billed+(requested_allocation->>'allocated_base_billed_quantity')::numeric>receipt_line.base_accepted_quantity
           OR prior_free+(requested_allocation->>'allocated_base_free_quantity')::numeric>receipt_line.base_free_quantity THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice exceeds separate posted receipt billed or free ceiling'; END IF;
        landed_cost_lineage:=erp_trade_commands_v2.landed_cost_receipt_lineage_state(
          organization_id,receipt_line.id,
          (requested_allocation->>'allocated_base_billed_quantity')::numeric,
          (requested_allocation->>'allocated_base_free_quantity')::numeric);
        IF landed_cost_lineage->>'contract_version'<>'supplier_invoice_landed_cost_lineage_v1'
           OR (landed_cost_lineage->>'source_identity_count')::integer<>1
           OR pg_catalog.jsonb_typeof(landed_cost_lineage->'targets')<>'array' THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice landed-cost lineage contract is invalid'; END IF;
        base_billed:=base_billed+(requested_allocation->>'allocated_base_billed_quantity')::numeric;
        base_free:=base_free+(requested_allocation->>'allocated_base_free_quantity')::numeric;
        receipt_cost:=receipt_cost+pg_catalog.round(((requested_allocation->>'allocated_base_billed_quantity')::numeric+
          (requested_allocation->>'allocated_base_free_quantity')::numeric)*receipt_line.unit_cost,2);
        resolved_allocations:=resolved_allocations||pg_catalog.jsonb_build_array(requested_allocation||pg_catalog.jsonb_build_object(
          'goods_receipt_id',receipt.id,'goods_receipt_row_version',receipt.row_version,'goods_receipt_line_row_id',receipt_line.id,
          'goods_receipt_received_at',receipt.received_at,'goods_receipt_business_date',receipt_business_date,
          'product_id',product.id,'receipt_unit_cost',receipt_line.unit_cost::text,'receipt_base_accepted_quantity',receipt_line.base_accepted_quantity::text,
          'receipt_base_free_quantity',receipt_line.base_free_quantity::text,'prior_allocated_base_billed_quantity',prior_billed::text,
          'prior_allocated_base_free_quantity',prior_free::text,'location_id',receipt_line.location_id,'batch_id',receipt_line.batch_id,
          'landed_cost_lineage',landed_cost_lineage));
        resolved_receipt_ids:=resolved_receipt_ids||pg_catalog.jsonb_build_array(receipt.id::text);
        source_versions:=source_versions||pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_object('resource_type','purchase_order','id',purchase_order.id,'row_version',purchase_order.row_version,
            'status',purchase_order.status,'order_date',purchase_order.order_date),
          pg_catalog.jsonb_build_object('resource_type','purchase_order_line','id',order_line.id,'purchase_order_id',purchase_order.id),
          pg_catalog.jsonb_build_object('resource_type','goods_receipt','id',receipt.id,'row_version',receipt.row_version,
            'status',receipt.status,'received_at',receipt.received_at,'business_date',receipt_business_date),
          pg_catalog.jsonb_build_object('resource_type','goods_receipt_line','id',receipt_line.id,'goods_receipt_line_id',receipt_line.id,'base_accepted_quantity',receipt_line.base_accepted_quantity::text,'base_free_quantity',receipt_line.base_free_quantity::text,'unit_cost',receipt_line.unit_cost::text),
          pg_catalog.jsonb_build_object('resource_type','receipt_invoice_ceiling','goods_receipt_line_id',receipt_line.id,'allocated_base_billed_quantity',prior_billed::text,'allocated_base_free_quantity',prior_free::text));
        FOR landed_cost_target IN SELECT value FROM pg_catalog.jsonb_array_elements(landed_cost_lineage->'targets') LOOP
          source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
            'resource_type','landed_cost_stock_target','goods_receipt_line_id',receipt_line.id,
            'location_id',landed_cost_target->>'location_id','branch_id',landed_cost_target->>'branch_id',
            'product_id',landed_cost_target->>'product_id','batch_id',landed_cost_target->>'batch_id',
            'row_version',(landed_cost_target->>'stock_row_version')::bigint,
            'last_ledger_entry_id',landed_cost_target->>'last_ledger_entry_id',
            'on_hand_quantity',landed_cost_target->>'on_hand_quantity',
            'inventory_value',landed_cost_target->>'inventory_value'));
        END LOOP;
      END LOOP;
      IF base_billed IS DISTINCT FROM pg_catalog.round((requested_line->>'billed_quantity')::numeric*line_factor,6)
         OR base_free IS DISTINCT FROM pg_catalog.round((requested_line->>'free_quantity')::numeric*line_factor,6) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice billed and free quantities do not reconcile exact receipt base allocations'; END IF;
      SELECT * INTO STRICT tax_version FROM tax.tax_code_versions WHERE code=product.hsn_code AND code_kind='hsn'
       AND status='active' AND taxability='taxable' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_release FROM core.reference_data_releases WHERE id=tax_version.release_id
       AND dataset_kind='hsn_sac_tax' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      IF ruleset_version IS NULL THEN ruleset_version:=tax_version.ruleset_version;
      ELSIF ruleset_version<>tax_version.ruleset_version THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice tax rulesets differ'; END IF;
      resolved_lines:=resolved_lines||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'line_number',pg_catalog.jsonb_array_length(resolved_lines)+1,'line_kind','product','line_id',requested_line->>'line_id',
        'purchase_order_line_id',line_purchase_order_line_id,'product_id',product.id,'hsn_code',product.hsn_code,'uom_code',line_uom,'multiplier',line_factor::text,
        'tax_code_version_id',tax_version.id,'taxability','taxable','gst_rate',tax_version.igst_rate::text,'cess_rate',tax_version.cess_rate::text,
        'ruleset_version',tax_version.ruleset_version,'net_value_account_id',inventory_account.id,'inventory_cost_treatment','capitalize',
        'landed_cost_allocation_method',requested_line->>'landed_cost_allocation_method',
        'itc_eligibility','eligible','receipt_cost',receipt_cost::text,'receipt_allocations',resolved_allocations,'input',requested_line));
      source_versions:=source_versions||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'resource_type','supplier_invoice_product_tax','product_id',product.id,'product_row_version',product.row_version,
        'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,'tax_release_id',tax_release.id,
        'tax_release_ruleset_version',tax_release.ruleset_version));
    END LOOP;
    FOR requested_line IN SELECT value FROM pg_catalog.jsonb_array_elements(COALESCE(request_document->'expense_charge_lines','[]'::jsonb)) LOOP
      SELECT * INTO STRICT profile FROM catalog.commercial_charge_tax_profiles WHERE org_id=organization_id
       AND direction='procurement' AND charge_code=requested_line->>'expense_charge_code' AND status='active'
       AND effective_from<=invoice_date AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_version FROM tax.tax_code_versions WHERE id=profile.tax_code_version_id AND code_kind='sac'
       AND status='active' AND taxability='taxable' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      SELECT * INTO STRICT tax_release FROM core.reference_data_releases WHERE id=tax_version.release_id
       AND dataset_kind='hsn_sac_tax' AND status='active' AND effective_from<=invoice_date
       AND (effective_to IS NULL OR effective_to>=invoice_date) FOR SHARE;
      IF requested_line->>'charge_inventory_cost_treatment'='capitalize' THEN
        IF NULLIF(requested_line->>'net_value_account_id','')::uuid IS DISTINCT FROM inventory_account.id THEN
          RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='capitalized supplier charge account differs from the canonical inventory role'; END IF;
        expense_account:=inventory_account;
      ELSE
        SELECT * INTO STRICT expense_account FROM finance.accounts WHERE org_id=organization_id
         AND id=NULLIF(requested_line->>'net_value_account_id','')::uuid AND account_type='expense'
         AND currency_code='INR' AND status='active' AND NOT allows_party_posting FOR SHARE;
      END IF;
      IF ruleset_version IS NULL THEN ruleset_version:=tax_version.ruleset_version;
      ELSIF ruleset_version<>tax_version.ruleset_version THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='supplier invoice tax rulesets differ'; END IF;
      resolved_lines:=resolved_lines||pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'line_number',pg_catalog.jsonb_array_length(resolved_lines)+1,'line_kind','charge','line_id',requested_line->>'line_id',
        'charge_code',profile.charge_code,'sac_code',tax_version.code,'tax_code_version_id',tax_version.id,
        'taxability','taxable','gst_rate',tax_version.igst_rate::text,'cess_rate',tax_version.cess_rate::text,
        'ruleset_version',tax_version.ruleset_version,'net_value_account_id',expense_account.id,
        'inventory_cost_treatment',requested_line->>'charge_inventory_cost_treatment',
        'landed_cost_allocation_method',requested_line->>'landed_cost_allocation_method',
        'itc_eligibility','eligible','input',requested_line||pg_catalog.jsonb_build_object(
          'charge_code',profile.charge_code,'price_basis',requested_line->>'expense_price_basis',
          'document_discount_eligible',requested_line->'expense_document_discount_eligible')));
      source_versions:=source_versions||pg_catalog.jsonb_build_array(
        pg_catalog.jsonb_build_object('resource_type','commercial_charge_tax_profile','id',profile.id,'row_version',profile.row_version,'charge_code',profile.charge_code),
        pg_catalog.jsonb_build_object('resource_type','supplier_invoice_charge_tax','charge_code',profile.charge_code,
          'tax_code_version_id',tax_version.id,'tax_version_number',tax_version.version_number,
          'tax_release_id',tax_release.id,'tax_release_ruleset_version',tax_release.ruleset_version),
        pg_catalog.jsonb_build_object('resource_type','finance_account','id',expense_account.id,'row_version',expense_account.row_version,'account_type',expense_account.account_type));
    END LOOP;
    IF EXISTS (
      (SELECT value FROM pg_catalog.jsonb_array_elements_text(request_document->'goods_receipt_ids') requested(value)
       EXCEPT SELECT value FROM pg_catalog.jsonb_array_elements_text(resolved_receipt_ids) resolved(value))
      UNION ALL
      (SELECT value FROM pg_catalog.jsonb_array_elements_text(resolved_receipt_ids) resolved(value)
       EXCEPT SELECT value FROM pg_catalog.jsonb_array_elements_text(request_document->'goods_receipt_ids') requested(value))
    ) THEN
      RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='requested GRN header set differs from the exact receipt allocation lineage'; END IF;
    RETURN pg_catalog.jsonb_build_object('branch_id',branch.id,'supplier_account_id',supplier.id,
      'purchase_order_id',source_purchase_order_id,'goods_receipt_ids',request_document->'goods_receipt_ids',
      'supplier_party_id',supplier_party.id,'supplier_tax_registration_id',supplier_registration.id,
      'supplier_gstin',supplier_registration.registration_number,'supplier_legal_name',supplier_registration.registered_legal_name,
      'supplier_address',pg_catalog.concat_ws(', ',supplier_address.line1,supplier_address.line2,supplier_address.city,supplier_address.state_code,supplier_address.postal_code),
      'buyer_tax_registration_id',buyer_registration.id,'buyer_gstin',buyer_registration.gstin,
      'buyer_legal_name',organization.legal_name,'buyer_address',pg_catalog.concat_ws(', ',branch.address_line1,branch.address_line2,branch.city,branch.state_code,branch.postal_code),
      'invoice_date',invoice_date,'received_date',received_date,'due_date',invoice_date+supplier.payment_days,
      'supply_type',supply_type,'zero_rated_payment_mode','not_applicable','tax_charge_mechanism','normal',
      'place_of_supply_state_code',buyer_registration.state_code,'portal_document_line_id',portal_line.id,
      'portal_taxable_amount',portal_line.taxable_amount::text,'portal_cgst_amount',portal_line.cgst_amount::text,
      'portal_sgst_amount',portal_line.sgst_amount::text,'portal_igst_amount',portal_line.igst_amount::text,
      'portal_cess_amount',portal_line.cess_amount::text,'ruleset_version',ruleset_version,'lines',resolved_lines,
      'legal_scope',pg_catalog.jsonb_build_object('country','IN','currency','INR','normal_charge',true,
        'posted_grn_match_required',true,'gstr2b_required',true,'itc_business_use_attestation_required',true,
        'landed_cost_supported',true,'landed_cost_methods',pg_catalog.jsonb_build_array('direct','quantity_weighted','value_weighted'),
        'consumed_variance_role','purchase_price_variance','import_supported',false,'sez_supported',false,'reverse_charge_supported',false),
      'source_versions',source_versions);
END
$function$;

ALTER FUNCTION "erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, request_document jsonb) OWNER TO "erp_migration_owner";

REVOKE ALL ON FUNCTION "erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, request_document jsonb) FROM PUBLIC, "erp_app", "erp_runtime";

GRANT EXECUTE ON FUNCTION "erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, request_document jsonb) TO "erp_runtime";

GRANT EXECUTE ON FUNCTION "erp_automation_commands"."resolve_supplier_invoice_prepare"(organization_id uuid, membership_id uuid, auth_user_id uuid, application_user_id uuid, grant_id uuid, caller_client_id varchar, supplier_invoice_id uuid, request_document jsonb) TO "erp_calculator";

RESET ROLE;
